// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/crossplane-contrib/provider-alibabacloud/apis/kms/v1alpha1"
	common "github.com/crossplane-contrib/provider-alibabacloud/config/common"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	resource "github.com/crossplane/upjet/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this LogtailAttachment.
func (mg *LogtailAttachment) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.LogtailConfigName),
		Extract:      common.NameExtractor(),
		Reference:    mg.Spec.ForProvider.LogtailConfigNameRef,
		Selector:     mg.Spec.ForProvider.LogtailConfigNameSelector,
		To: reference.To{
			List:    &LogtailConfigList{},
			Managed: &LogtailConfig{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.LogtailConfigName")
	}
	mg.Spec.ForProvider.LogtailConfigName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.LogtailConfigNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.MachineGroupName),
		Extract:      common.NameExtractor(),
		Reference:    mg.Spec.ForProvider.MachineGroupNameRef,
		Selector:     mg.Spec.ForProvider.MachineGroupNameSelector,
		To: reference.To{
			List:    &MachineGroupList{},
			Managed: &MachineGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.MachineGroupName")
	}
	mg.Spec.ForProvider.MachineGroupName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.MachineGroupNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Project),
		Extract:      common.IdExtractor(),
		Reference:    mg.Spec.ForProvider.ProjectRef,
		Selector:     mg.Spec.ForProvider.ProjectSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Project")
	}
	mg.Spec.ForProvider.Project = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.LogtailConfigName),
		Extract:      common.NameExtractor(),
		Reference:    mg.Spec.InitProvider.LogtailConfigNameRef,
		Selector:     mg.Spec.InitProvider.LogtailConfigNameSelector,
		To: reference.To{
			List:    &LogtailConfigList{},
			Managed: &LogtailConfig{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.LogtailConfigName")
	}
	mg.Spec.InitProvider.LogtailConfigName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.LogtailConfigNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.MachineGroupName),
		Extract:      common.NameExtractor(),
		Reference:    mg.Spec.InitProvider.MachineGroupNameRef,
		Selector:     mg.Spec.InitProvider.MachineGroupNameSelector,
		To: reference.To{
			List:    &MachineGroupList{},
			Managed: &MachineGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.MachineGroupName")
	}
	mg.Spec.InitProvider.MachineGroupName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.MachineGroupNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Project),
		Extract:      common.IdExtractor(),
		Reference:    mg.Spec.InitProvider.ProjectRef,
		Selector:     mg.Spec.InitProvider.ProjectSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Project")
	}
	mg.Spec.InitProvider.Project = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this LogtailConfig.
func (mg *LogtailConfig) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Logstore),
		Extract:      common.LogStoreNameExtractor(),
		Reference:    mg.Spec.ForProvider.LogstoreRef,
		Selector:     mg.Spec.ForProvider.LogstoreSelector,
		To: reference.To{
			List:    &StoreList{},
			Managed: &Store{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Logstore")
	}
	mg.Spec.ForProvider.Logstore = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.LogstoreRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Project),
		Extract:      common.IdExtractor(),
		Reference:    mg.Spec.ForProvider.ProjectRef,
		Selector:     mg.Spec.ForProvider.ProjectSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Project")
	}
	mg.Spec.ForProvider.Project = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Logstore),
		Extract:      common.LogStoreNameExtractor(),
		Reference:    mg.Spec.InitProvider.LogstoreRef,
		Selector:     mg.Spec.InitProvider.LogstoreSelector,
		To: reference.To{
			List:    &StoreList{},
			Managed: &Store{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Logstore")
	}
	mg.Spec.InitProvider.Logstore = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.LogstoreRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Project),
		Extract:      common.IdExtractor(),
		Reference:    mg.Spec.InitProvider.ProjectRef,
		Selector:     mg.Spec.InitProvider.ProjectSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Project")
	}
	mg.Spec.InitProvider.Project = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this MachineGroup.
func (mg *MachineGroup) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Project),
		Extract:      common.IdExtractor(),
		Reference:    mg.Spec.ForProvider.ProjectRef,
		Selector:     mg.Spec.ForProvider.ProjectSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Project")
	}
	mg.Spec.ForProvider.Project = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Project),
		Extract:      common.IdExtractor(),
		Reference:    mg.Spec.InitProvider.ProjectRef,
		Selector:     mg.Spec.InitProvider.ProjectSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Project")
	}
	mg.Spec.InitProvider.Project = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Store.
func (mg *Store) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.EncryptConf); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.EncryptConf[i3].UserCmkInfo); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.EncryptConf[i3].UserCmkInfo[i4].CmkKeyID),
				Extract:      resource.ExtractResourceID(),
				Reference:    mg.Spec.ForProvider.EncryptConf[i3].UserCmkInfo[i4].CmkKeyIDRef,
				Selector:     mg.Spec.ForProvider.EncryptConf[i3].UserCmkInfo[i4].CmkKeyIDSelector,
				To: reference.To{
					List:    &v1alpha1.KeyList{},
					Managed: &v1alpha1.Key{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.EncryptConf[i3].UserCmkInfo[i4].CmkKeyID")
			}
			mg.Spec.ForProvider.EncryptConf[i3].UserCmkInfo[i4].CmkKeyID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.EncryptConf[i3].UserCmkInfo[i4].CmkKeyIDRef = rsp.ResolvedReference

		}
	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectName),
		Extract:      common.IdExtractor(),
		Reference:    mg.Spec.ForProvider.ProjectNameRef,
		Selector:     mg.Spec.ForProvider.ProjectNameSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectName")
	}
	mg.Spec.ForProvider.ProjectName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectNameRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.EncryptConf); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.EncryptConf[i3].UserCmkInfo); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.EncryptConf[i3].UserCmkInfo[i4].CmkKeyID),
				Extract:      resource.ExtractResourceID(),
				Reference:    mg.Spec.InitProvider.EncryptConf[i3].UserCmkInfo[i4].CmkKeyIDRef,
				Selector:     mg.Spec.InitProvider.EncryptConf[i3].UserCmkInfo[i4].CmkKeyIDSelector,
				To: reference.To{
					List:    &v1alpha1.KeyList{},
					Managed: &v1alpha1.Key{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.EncryptConf[i3].UserCmkInfo[i4].CmkKeyID")
			}
			mg.Spec.InitProvider.EncryptConf[i3].UserCmkInfo[i4].CmkKeyID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.EncryptConf[i3].UserCmkInfo[i4].CmkKeyIDRef = rsp.ResolvedReference

		}
	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectName),
		Extract:      common.IdExtractor(),
		Reference:    mg.Spec.InitProvider.ProjectNameRef,
		Selector:     mg.Spec.InitProvider.ProjectNameSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectName")
	}
	mg.Spec.InitProvider.ProjectName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectNameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this StoreIndex.
func (mg *StoreIndex) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Logstore),
		Extract:      common.LogStoreNameExtractor(),
		Reference:    mg.Spec.ForProvider.LogstoreRef,
		Selector:     mg.Spec.ForProvider.LogstoreSelector,
		To: reference.To{
			List:    &StoreList{},
			Managed: &Store{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Logstore")
	}
	mg.Spec.ForProvider.Logstore = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.LogstoreRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Project),
		Extract:      common.IdExtractor(),
		Reference:    mg.Spec.ForProvider.ProjectRef,
		Selector:     mg.Spec.ForProvider.ProjectSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Project")
	}
	mg.Spec.ForProvider.Project = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Logstore),
		Extract:      common.LogStoreNameExtractor(),
		Reference:    mg.Spec.InitProvider.LogstoreRef,
		Selector:     mg.Spec.InitProvider.LogstoreSelector,
		To: reference.To{
			List:    &StoreList{},
			Managed: &Store{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Logstore")
	}
	mg.Spec.InitProvider.Logstore = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.LogstoreRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Project),
		Extract:      common.IdExtractor(),
		Reference:    mg.Spec.InitProvider.ProjectRef,
		Selector:     mg.Spec.InitProvider.ProjectSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Project")
	}
	mg.Spec.InitProvider.Project = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectRef = rsp.ResolvedReference

	return nil
}
