//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptConfInitParameters) DeepCopyInto(out *EncryptConfInitParameters) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.EncryptType != nil {
		in, out := &in.EncryptType, &out.EncryptType
		*out = new(string)
		**out = **in
	}
	if in.UserCmkInfo != nil {
		in, out := &in.UserCmkInfo, &out.UserCmkInfo
		*out = make([]UserCmkInfoInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptConfInitParameters.
func (in *EncryptConfInitParameters) DeepCopy() *EncryptConfInitParameters {
	if in == nil {
		return nil
	}
	out := new(EncryptConfInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptConfObservation) DeepCopyInto(out *EncryptConfObservation) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.EncryptType != nil {
		in, out := &in.EncryptType, &out.EncryptType
		*out = new(string)
		**out = **in
	}
	if in.UserCmkInfo != nil {
		in, out := &in.UserCmkInfo, &out.UserCmkInfo
		*out = make([]UserCmkInfoObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptConfObservation.
func (in *EncryptConfObservation) DeepCopy() *EncryptConfObservation {
	if in == nil {
		return nil
	}
	out := new(EncryptConfObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptConfParameters) DeepCopyInto(out *EncryptConfParameters) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.EncryptType != nil {
		in, out := &in.EncryptType, &out.EncryptType
		*out = new(string)
		**out = **in
	}
	if in.UserCmkInfo != nil {
		in, out := &in.UserCmkInfo, &out.UserCmkInfo
		*out = make([]UserCmkInfoParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptConfParameters.
func (in *EncryptConfParameters) DeepCopy() *EncryptConfParameters {
	if in == nil {
		return nil
	}
	out := new(EncryptConfParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldSearchInitParameters) DeepCopyInto(out *FieldSearchInitParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.CaseSensitive != nil {
		in, out := &in.CaseSensitive, &out.CaseSensitive
		*out = new(bool)
		**out = **in
	}
	if in.EnableAnalytics != nil {
		in, out := &in.EnableAnalytics, &out.EnableAnalytics
		*out = new(bool)
		**out = **in
	}
	if in.IncludeChinese != nil {
		in, out := &in.IncludeChinese, &out.IncludeChinese
		*out = new(bool)
		**out = **in
	}
	if in.JSONKeys != nil {
		in, out := &in.JSONKeys, &out.JSONKeys
		*out = make([]JSONKeysInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldSearchInitParameters.
func (in *FieldSearchInitParameters) DeepCopy() *FieldSearchInitParameters {
	if in == nil {
		return nil
	}
	out := new(FieldSearchInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldSearchObservation) DeepCopyInto(out *FieldSearchObservation) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.CaseSensitive != nil {
		in, out := &in.CaseSensitive, &out.CaseSensitive
		*out = new(bool)
		**out = **in
	}
	if in.EnableAnalytics != nil {
		in, out := &in.EnableAnalytics, &out.EnableAnalytics
		*out = new(bool)
		**out = **in
	}
	if in.IncludeChinese != nil {
		in, out := &in.IncludeChinese, &out.IncludeChinese
		*out = new(bool)
		**out = **in
	}
	if in.JSONKeys != nil {
		in, out := &in.JSONKeys, &out.JSONKeys
		*out = make([]JSONKeysObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldSearchObservation.
func (in *FieldSearchObservation) DeepCopy() *FieldSearchObservation {
	if in == nil {
		return nil
	}
	out := new(FieldSearchObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldSearchParameters) DeepCopyInto(out *FieldSearchParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.CaseSensitive != nil {
		in, out := &in.CaseSensitive, &out.CaseSensitive
		*out = new(bool)
		**out = **in
	}
	if in.EnableAnalytics != nil {
		in, out := &in.EnableAnalytics, &out.EnableAnalytics
		*out = new(bool)
		**out = **in
	}
	if in.IncludeChinese != nil {
		in, out := &in.IncludeChinese, &out.IncludeChinese
		*out = new(bool)
		**out = **in
	}
	if in.JSONKeys != nil {
		in, out := &in.JSONKeys, &out.JSONKeys
		*out = make([]JSONKeysParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldSearchParameters.
func (in *FieldSearchParameters) DeepCopy() *FieldSearchParameters {
	if in == nil {
		return nil
	}
	out := new(FieldSearchParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FullTextInitParameters) DeepCopyInto(out *FullTextInitParameters) {
	*out = *in
	if in.CaseSensitive != nil {
		in, out := &in.CaseSensitive, &out.CaseSensitive
		*out = new(bool)
		**out = **in
	}
	if in.IncludeChinese != nil {
		in, out := &in.IncludeChinese, &out.IncludeChinese
		*out = new(bool)
		**out = **in
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FullTextInitParameters.
func (in *FullTextInitParameters) DeepCopy() *FullTextInitParameters {
	if in == nil {
		return nil
	}
	out := new(FullTextInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FullTextObservation) DeepCopyInto(out *FullTextObservation) {
	*out = *in
	if in.CaseSensitive != nil {
		in, out := &in.CaseSensitive, &out.CaseSensitive
		*out = new(bool)
		**out = **in
	}
	if in.IncludeChinese != nil {
		in, out := &in.IncludeChinese, &out.IncludeChinese
		*out = new(bool)
		**out = **in
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FullTextObservation.
func (in *FullTextObservation) DeepCopy() *FullTextObservation {
	if in == nil {
		return nil
	}
	out := new(FullTextObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FullTextParameters) DeepCopyInto(out *FullTextParameters) {
	*out = *in
	if in.CaseSensitive != nil {
		in, out := &in.CaseSensitive, &out.CaseSensitive
		*out = new(bool)
		**out = **in
	}
	if in.IncludeChinese != nil {
		in, out := &in.IncludeChinese, &out.IncludeChinese
		*out = new(bool)
		**out = **in
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FullTextParameters.
func (in *FullTextParameters) DeepCopy() *FullTextParameters {
	if in == nil {
		return nil
	}
	out := new(FullTextParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JSONKeysInitParameters) DeepCopyInto(out *JSONKeysInitParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.DocValue != nil {
		in, out := &in.DocValue, &out.DocValue
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSONKeysInitParameters.
func (in *JSONKeysInitParameters) DeepCopy() *JSONKeysInitParameters {
	if in == nil {
		return nil
	}
	out := new(JSONKeysInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JSONKeysObservation) DeepCopyInto(out *JSONKeysObservation) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.DocValue != nil {
		in, out := &in.DocValue, &out.DocValue
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSONKeysObservation.
func (in *JSONKeysObservation) DeepCopy() *JSONKeysObservation {
	if in == nil {
		return nil
	}
	out := new(JSONKeysObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JSONKeysParameters) DeepCopyInto(out *JSONKeysParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.DocValue != nil {
		in, out := &in.DocValue, &out.DocValue
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSONKeysParameters.
func (in *JSONKeysParameters) DeepCopy() *JSONKeysParameters {
	if in == nil {
		return nil
	}
	out := new(JSONKeysParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogtailAttachment) DeepCopyInto(out *LogtailAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogtailAttachment.
func (in *LogtailAttachment) DeepCopy() *LogtailAttachment {
	if in == nil {
		return nil
	}
	out := new(LogtailAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogtailAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogtailAttachmentInitParameters) DeepCopyInto(out *LogtailAttachmentInitParameters) {
	*out = *in
	if in.LogtailConfigName != nil {
		in, out := &in.LogtailConfigName, &out.LogtailConfigName
		*out = new(string)
		**out = **in
	}
	if in.LogtailConfigNameRef != nil {
		in, out := &in.LogtailConfigNameRef, &out.LogtailConfigNameRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.LogtailConfigNameSelector != nil {
		in, out := &in.LogtailConfigNameSelector, &out.LogtailConfigNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.MachineGroupName != nil {
		in, out := &in.MachineGroupName, &out.MachineGroupName
		*out = new(string)
		**out = **in
	}
	if in.MachineGroupNameRef != nil {
		in, out := &in.MachineGroupNameRef, &out.MachineGroupNameRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.MachineGroupNameSelector != nil {
		in, out := &in.MachineGroupNameSelector, &out.MachineGroupNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectSelector != nil {
		in, out := &in.ProjectSelector, &out.ProjectSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogtailAttachmentInitParameters.
func (in *LogtailAttachmentInitParameters) DeepCopy() *LogtailAttachmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(LogtailAttachmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogtailAttachmentList) DeepCopyInto(out *LogtailAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LogtailAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogtailAttachmentList.
func (in *LogtailAttachmentList) DeepCopy() *LogtailAttachmentList {
	if in == nil {
		return nil
	}
	out := new(LogtailAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogtailAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogtailAttachmentObservation) DeepCopyInto(out *LogtailAttachmentObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LogtailConfigName != nil {
		in, out := &in.LogtailConfigName, &out.LogtailConfigName
		*out = new(string)
		**out = **in
	}
	if in.MachineGroupName != nil {
		in, out := &in.MachineGroupName, &out.MachineGroupName
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogtailAttachmentObservation.
func (in *LogtailAttachmentObservation) DeepCopy() *LogtailAttachmentObservation {
	if in == nil {
		return nil
	}
	out := new(LogtailAttachmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogtailAttachmentParameters) DeepCopyInto(out *LogtailAttachmentParameters) {
	*out = *in
	if in.LogtailConfigName != nil {
		in, out := &in.LogtailConfigName, &out.LogtailConfigName
		*out = new(string)
		**out = **in
	}
	if in.LogtailConfigNameRef != nil {
		in, out := &in.LogtailConfigNameRef, &out.LogtailConfigNameRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.LogtailConfigNameSelector != nil {
		in, out := &in.LogtailConfigNameSelector, &out.LogtailConfigNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.MachineGroupName != nil {
		in, out := &in.MachineGroupName, &out.MachineGroupName
		*out = new(string)
		**out = **in
	}
	if in.MachineGroupNameRef != nil {
		in, out := &in.MachineGroupNameRef, &out.MachineGroupNameRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.MachineGroupNameSelector != nil {
		in, out := &in.MachineGroupNameSelector, &out.MachineGroupNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectSelector != nil {
		in, out := &in.ProjectSelector, &out.ProjectSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogtailAttachmentParameters.
func (in *LogtailAttachmentParameters) DeepCopy() *LogtailAttachmentParameters {
	if in == nil {
		return nil
	}
	out := new(LogtailAttachmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogtailAttachmentSpec) DeepCopyInto(out *LogtailAttachmentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogtailAttachmentSpec.
func (in *LogtailAttachmentSpec) DeepCopy() *LogtailAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(LogtailAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogtailAttachmentStatus) DeepCopyInto(out *LogtailAttachmentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogtailAttachmentStatus.
func (in *LogtailAttachmentStatus) DeepCopy() *LogtailAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(LogtailAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogtailConfig) DeepCopyInto(out *LogtailConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogtailConfig.
func (in *LogtailConfig) DeepCopy() *LogtailConfig {
	if in == nil {
		return nil
	}
	out := new(LogtailConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogtailConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogtailConfigInitParameters) DeepCopyInto(out *LogtailConfigInitParameters) {
	*out = *in
	if in.InputDetail != nil {
		in, out := &in.InputDetail, &out.InputDetail
		*out = new(string)
		**out = **in
	}
	if in.InputType != nil {
		in, out := &in.InputType, &out.InputType
		*out = new(string)
		**out = **in
	}
	if in.LogSample != nil {
		in, out := &in.LogSample, &out.LogSample
		*out = new(string)
		**out = **in
	}
	if in.Logstore != nil {
		in, out := &in.Logstore, &out.Logstore
		*out = new(string)
		**out = **in
	}
	if in.LogstoreRef != nil {
		in, out := &in.LogstoreRef, &out.LogstoreRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.LogstoreSelector != nil {
		in, out := &in.LogstoreSelector, &out.LogstoreSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OutputType != nil {
		in, out := &in.OutputType, &out.OutputType
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectSelector != nil {
		in, out := &in.ProjectSelector, &out.ProjectSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogtailConfigInitParameters.
func (in *LogtailConfigInitParameters) DeepCopy() *LogtailConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(LogtailConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogtailConfigList) DeepCopyInto(out *LogtailConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LogtailConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogtailConfigList.
func (in *LogtailConfigList) DeepCopy() *LogtailConfigList {
	if in == nil {
		return nil
	}
	out := new(LogtailConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogtailConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogtailConfigObservation) DeepCopyInto(out *LogtailConfigObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InputDetail != nil {
		in, out := &in.InputDetail, &out.InputDetail
		*out = new(string)
		**out = **in
	}
	if in.InputType != nil {
		in, out := &in.InputType, &out.InputType
		*out = new(string)
		**out = **in
	}
	if in.LastModifyTime != nil {
		in, out := &in.LastModifyTime, &out.LastModifyTime
		*out = new(string)
		**out = **in
	}
	if in.LogSample != nil {
		in, out := &in.LogSample, &out.LogSample
		*out = new(string)
		**out = **in
	}
	if in.Logstore != nil {
		in, out := &in.Logstore, &out.Logstore
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OutputType != nil {
		in, out := &in.OutputType, &out.OutputType
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogtailConfigObservation.
func (in *LogtailConfigObservation) DeepCopy() *LogtailConfigObservation {
	if in == nil {
		return nil
	}
	out := new(LogtailConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogtailConfigParameters) DeepCopyInto(out *LogtailConfigParameters) {
	*out = *in
	if in.InputDetail != nil {
		in, out := &in.InputDetail, &out.InputDetail
		*out = new(string)
		**out = **in
	}
	if in.InputType != nil {
		in, out := &in.InputType, &out.InputType
		*out = new(string)
		**out = **in
	}
	if in.LogSample != nil {
		in, out := &in.LogSample, &out.LogSample
		*out = new(string)
		**out = **in
	}
	if in.Logstore != nil {
		in, out := &in.Logstore, &out.Logstore
		*out = new(string)
		**out = **in
	}
	if in.LogstoreRef != nil {
		in, out := &in.LogstoreRef, &out.LogstoreRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.LogstoreSelector != nil {
		in, out := &in.LogstoreSelector, &out.LogstoreSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OutputType != nil {
		in, out := &in.OutputType, &out.OutputType
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectSelector != nil {
		in, out := &in.ProjectSelector, &out.ProjectSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogtailConfigParameters.
func (in *LogtailConfigParameters) DeepCopy() *LogtailConfigParameters {
	if in == nil {
		return nil
	}
	out := new(LogtailConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogtailConfigSpec) DeepCopyInto(out *LogtailConfigSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogtailConfigSpec.
func (in *LogtailConfigSpec) DeepCopy() *LogtailConfigSpec {
	if in == nil {
		return nil
	}
	out := new(LogtailConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogtailConfigStatus) DeepCopyInto(out *LogtailConfigStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogtailConfigStatus.
func (in *LogtailConfigStatus) DeepCopy() *LogtailConfigStatus {
	if in == nil {
		return nil
	}
	out := new(LogtailConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineGroup) DeepCopyInto(out *MachineGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineGroup.
func (in *MachineGroup) DeepCopy() *MachineGroup {
	if in == nil {
		return nil
	}
	out := new(MachineGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineGroupInitParameters) DeepCopyInto(out *MachineGroupInitParameters) {
	*out = *in
	if in.IdentifyList != nil {
		in, out := &in.IdentifyList, &out.IdentifyList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IdentifyType != nil {
		in, out := &in.IdentifyType, &out.IdentifyType
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectSelector != nil {
		in, out := &in.ProjectSelector, &out.ProjectSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Topic != nil {
		in, out := &in.Topic, &out.Topic
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineGroupInitParameters.
func (in *MachineGroupInitParameters) DeepCopy() *MachineGroupInitParameters {
	if in == nil {
		return nil
	}
	out := new(MachineGroupInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineGroupList) DeepCopyInto(out *MachineGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineGroupList.
func (in *MachineGroupList) DeepCopy() *MachineGroupList {
	if in == nil {
		return nil
	}
	out := new(MachineGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineGroupObservation) DeepCopyInto(out *MachineGroupObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IdentifyList != nil {
		in, out := &in.IdentifyList, &out.IdentifyList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IdentifyType != nil {
		in, out := &in.IdentifyType, &out.IdentifyType
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.Topic != nil {
		in, out := &in.Topic, &out.Topic
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineGroupObservation.
func (in *MachineGroupObservation) DeepCopy() *MachineGroupObservation {
	if in == nil {
		return nil
	}
	out := new(MachineGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineGroupParameters) DeepCopyInto(out *MachineGroupParameters) {
	*out = *in
	if in.IdentifyList != nil {
		in, out := &in.IdentifyList, &out.IdentifyList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IdentifyType != nil {
		in, out := &in.IdentifyType, &out.IdentifyType
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectSelector != nil {
		in, out := &in.ProjectSelector, &out.ProjectSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Topic != nil {
		in, out := &in.Topic, &out.Topic
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineGroupParameters.
func (in *MachineGroupParameters) DeepCopy() *MachineGroupParameters {
	if in == nil {
		return nil
	}
	out := new(MachineGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineGroupSpec) DeepCopyInto(out *MachineGroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineGroupSpec.
func (in *MachineGroupSpec) DeepCopy() *MachineGroupSpec {
	if in == nil {
		return nil
	}
	out := new(MachineGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineGroupStatus) DeepCopyInto(out *MachineGroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineGroupStatus.
func (in *MachineGroupStatus) DeepCopy() *MachineGroupStatus {
	if in == nil {
		return nil
	}
	out := new(MachineGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Project.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInitParameters) DeepCopyInto(out *ProjectInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.ProjectName != nil {
		in, out := &in.ProjectName, &out.ProjectName
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupID != nil {
		in, out := &in.ResourceGroupID, &out.ResourceGroupID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInitParameters.
func (in *ProjectInitParameters) DeepCopy() *ProjectInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Project, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectList.
func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectObservation) DeepCopyInto(out *ProjectObservation) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.ProjectName != nil {
		in, out := &in.ProjectName, &out.ProjectName
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupID != nil {
		in, out := &in.ResourceGroupID, &out.ResourceGroupID
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectObservation.
func (in *ProjectObservation) DeepCopy() *ProjectObservation {
	if in == nil {
		return nil
	}
	out := new(ProjectObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectParameters) DeepCopyInto(out *ProjectParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.ProjectName != nil {
		in, out := &in.ProjectName, &out.ProjectName
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupID != nil {
		in, out := &in.ResourceGroupID, &out.ResourceGroupID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectParameters.
func (in *ProjectParameters) DeepCopy() *ProjectParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSpec.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectStatus.
func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardsInitParameters) DeepCopyInto(out *ShardsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardsInitParameters.
func (in *ShardsInitParameters) DeepCopy() *ShardsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ShardsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardsObservation) DeepCopyInto(out *ShardsObservation) {
	*out = *in
	if in.BeginKey != nil {
		in, out := &in.BeginKey, &out.BeginKey
		*out = new(string)
		**out = **in
	}
	if in.EndKey != nil {
		in, out := &in.EndKey, &out.EndKey
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(float64)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardsObservation.
func (in *ShardsObservation) DeepCopy() *ShardsObservation {
	if in == nil {
		return nil
	}
	out := new(ShardsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardsParameters) DeepCopyInto(out *ShardsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardsParameters.
func (in *ShardsParameters) DeepCopy() *ShardsParameters {
	if in == nil {
		return nil
	}
	out := new(ShardsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Store) DeepCopyInto(out *Store) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Store.
func (in *Store) DeepCopy() *Store {
	if in == nil {
		return nil
	}
	out := new(Store)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Store) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreIndex) DeepCopyInto(out *StoreIndex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreIndex.
func (in *StoreIndex) DeepCopy() *StoreIndex {
	if in == nil {
		return nil
	}
	out := new(StoreIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoreIndex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreIndexInitParameters) DeepCopyInto(out *StoreIndexInitParameters) {
	*out = *in
	if in.FieldSearch != nil {
		in, out := &in.FieldSearch, &out.FieldSearch
		*out = make([]FieldSearchInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FullText != nil {
		in, out := &in.FullText, &out.FullText
		*out = make([]FullTextInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LogReduce != nil {
		in, out := &in.LogReduce, &out.LogReduce
		*out = new(bool)
		**out = **in
	}
	if in.LogReduceBlackList != nil {
		in, out := &in.LogReduceBlackList, &out.LogReduceBlackList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LogReduceWhiteList != nil {
		in, out := &in.LogReduceWhiteList, &out.LogReduceWhiteList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Logstore != nil {
		in, out := &in.Logstore, &out.Logstore
		*out = new(string)
		**out = **in
	}
	if in.LogstoreRef != nil {
		in, out := &in.LogstoreRef, &out.LogstoreRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.LogstoreSelector != nil {
		in, out := &in.LogstoreSelector, &out.LogstoreSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxTextLen != nil {
		in, out := &in.MaxTextLen, &out.MaxTextLen
		*out = new(float64)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectSelector != nil {
		in, out := &in.ProjectSelector, &out.ProjectSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreIndexInitParameters.
func (in *StoreIndexInitParameters) DeepCopy() *StoreIndexInitParameters {
	if in == nil {
		return nil
	}
	out := new(StoreIndexInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreIndexList) DeepCopyInto(out *StoreIndexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StoreIndex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreIndexList.
func (in *StoreIndexList) DeepCopy() *StoreIndexList {
	if in == nil {
		return nil
	}
	out := new(StoreIndexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoreIndexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreIndexObservation) DeepCopyInto(out *StoreIndexObservation) {
	*out = *in
	if in.FieldSearch != nil {
		in, out := &in.FieldSearch, &out.FieldSearch
		*out = make([]FieldSearchObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FullText != nil {
		in, out := &in.FullText, &out.FullText
		*out = make([]FullTextObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LogReduce != nil {
		in, out := &in.LogReduce, &out.LogReduce
		*out = new(bool)
		**out = **in
	}
	if in.LogReduceBlackList != nil {
		in, out := &in.LogReduceBlackList, &out.LogReduceBlackList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LogReduceWhiteList != nil {
		in, out := &in.LogReduceWhiteList, &out.LogReduceWhiteList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Logstore != nil {
		in, out := &in.Logstore, &out.Logstore
		*out = new(string)
		**out = **in
	}
	if in.MaxTextLen != nil {
		in, out := &in.MaxTextLen, &out.MaxTextLen
		*out = new(float64)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreIndexObservation.
func (in *StoreIndexObservation) DeepCopy() *StoreIndexObservation {
	if in == nil {
		return nil
	}
	out := new(StoreIndexObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreIndexParameters) DeepCopyInto(out *StoreIndexParameters) {
	*out = *in
	if in.FieldSearch != nil {
		in, out := &in.FieldSearch, &out.FieldSearch
		*out = make([]FieldSearchParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FullText != nil {
		in, out := &in.FullText, &out.FullText
		*out = make([]FullTextParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LogReduce != nil {
		in, out := &in.LogReduce, &out.LogReduce
		*out = new(bool)
		**out = **in
	}
	if in.LogReduceBlackList != nil {
		in, out := &in.LogReduceBlackList, &out.LogReduceBlackList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LogReduceWhiteList != nil {
		in, out := &in.LogReduceWhiteList, &out.LogReduceWhiteList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Logstore != nil {
		in, out := &in.Logstore, &out.Logstore
		*out = new(string)
		**out = **in
	}
	if in.LogstoreRef != nil {
		in, out := &in.LogstoreRef, &out.LogstoreRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.LogstoreSelector != nil {
		in, out := &in.LogstoreSelector, &out.LogstoreSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxTextLen != nil {
		in, out := &in.MaxTextLen, &out.MaxTextLen
		*out = new(float64)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectSelector != nil {
		in, out := &in.ProjectSelector, &out.ProjectSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreIndexParameters.
func (in *StoreIndexParameters) DeepCopy() *StoreIndexParameters {
	if in == nil {
		return nil
	}
	out := new(StoreIndexParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreIndexSpec) DeepCopyInto(out *StoreIndexSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreIndexSpec.
func (in *StoreIndexSpec) DeepCopy() *StoreIndexSpec {
	if in == nil {
		return nil
	}
	out := new(StoreIndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreIndexStatus) DeepCopyInto(out *StoreIndexStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreIndexStatus.
func (in *StoreIndexStatus) DeepCopy() *StoreIndexStatus {
	if in == nil {
		return nil
	}
	out := new(StoreIndexStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreInitParameters) DeepCopyInto(out *StoreInitParameters) {
	*out = *in
	if in.AppendMeta != nil {
		in, out := &in.AppendMeta, &out.AppendMeta
		*out = new(bool)
		**out = **in
	}
	if in.AutoSplit != nil {
		in, out := &in.AutoSplit, &out.AutoSplit
		*out = new(bool)
		**out = **in
	}
	if in.EnableWebTracking != nil {
		in, out := &in.EnableWebTracking, &out.EnableWebTracking
		*out = new(bool)
		**out = **in
	}
	if in.EncryptConf != nil {
		in, out := &in.EncryptConf, &out.EncryptConf
		*out = make([]EncryptConfInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HotTTL != nil {
		in, out := &in.HotTTL, &out.HotTTL
		*out = new(float64)
		**out = **in
	}
	if in.InfrequentAccessTTL != nil {
		in, out := &in.InfrequentAccessTTL, &out.InfrequentAccessTTL
		*out = new(float64)
		**out = **in
	}
	if in.LogstoreName != nil {
		in, out := &in.LogstoreName, &out.LogstoreName
		*out = new(string)
		**out = **in
	}
	if in.MaxSplitShardCount != nil {
		in, out := &in.MaxSplitShardCount, &out.MaxSplitShardCount
		*out = new(float64)
		**out = **in
	}
	if in.MeteringMode != nil {
		in, out := &in.MeteringMode, &out.MeteringMode
		*out = new(string)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.ProjectName != nil {
		in, out := &in.ProjectName, &out.ProjectName
		*out = new(string)
		**out = **in
	}
	if in.ProjectNameRef != nil {
		in, out := &in.ProjectNameRef, &out.ProjectNameRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectNameSelector != nil {
		in, out := &in.ProjectNameSelector, &out.ProjectNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RetentionPeriod != nil {
		in, out := &in.RetentionPeriod, &out.RetentionPeriod
		*out = new(float64)
		**out = **in
	}
	if in.ShardCount != nil {
		in, out := &in.ShardCount, &out.ShardCount
		*out = new(float64)
		**out = **in
	}
	if in.TelemetryType != nil {
		in, out := &in.TelemetryType, &out.TelemetryType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreInitParameters.
func (in *StoreInitParameters) DeepCopy() *StoreInitParameters {
	if in == nil {
		return nil
	}
	out := new(StoreInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreList) DeepCopyInto(out *StoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Store, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreList.
func (in *StoreList) DeepCopy() *StoreList {
	if in == nil {
		return nil
	}
	out := new(StoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreObservation) DeepCopyInto(out *StoreObservation) {
	*out = *in
	if in.AppendMeta != nil {
		in, out := &in.AppendMeta, &out.AppendMeta
		*out = new(bool)
		**out = **in
	}
	if in.AutoSplit != nil {
		in, out := &in.AutoSplit, &out.AutoSplit
		*out = new(bool)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(float64)
		**out = **in
	}
	if in.EnableWebTracking != nil {
		in, out := &in.EnableWebTracking, &out.EnableWebTracking
		*out = new(bool)
		**out = **in
	}
	if in.EncryptConf != nil {
		in, out := &in.EncryptConf, &out.EncryptConf
		*out = make([]EncryptConfObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HotTTL != nil {
		in, out := &in.HotTTL, &out.HotTTL
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InfrequentAccessTTL != nil {
		in, out := &in.InfrequentAccessTTL, &out.InfrequentAccessTTL
		*out = new(float64)
		**out = **in
	}
	if in.LogstoreName != nil {
		in, out := &in.LogstoreName, &out.LogstoreName
		*out = new(string)
		**out = **in
	}
	if in.MaxSplitShardCount != nil {
		in, out := &in.MaxSplitShardCount, &out.MaxSplitShardCount
		*out = new(float64)
		**out = **in
	}
	if in.MeteringMode != nil {
		in, out := &in.MeteringMode, &out.MeteringMode
		*out = new(string)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.ProjectName != nil {
		in, out := &in.ProjectName, &out.ProjectName
		*out = new(string)
		**out = **in
	}
	if in.RetentionPeriod != nil {
		in, out := &in.RetentionPeriod, &out.RetentionPeriod
		*out = new(float64)
		**out = **in
	}
	if in.ShardCount != nil {
		in, out := &in.ShardCount, &out.ShardCount
		*out = new(float64)
		**out = **in
	}
	if in.Shards != nil {
		in, out := &in.Shards, &out.Shards
		*out = make([]ShardsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TelemetryType != nil {
		in, out := &in.TelemetryType, &out.TelemetryType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreObservation.
func (in *StoreObservation) DeepCopy() *StoreObservation {
	if in == nil {
		return nil
	}
	out := new(StoreObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreParameters) DeepCopyInto(out *StoreParameters) {
	*out = *in
	if in.AppendMeta != nil {
		in, out := &in.AppendMeta, &out.AppendMeta
		*out = new(bool)
		**out = **in
	}
	if in.AutoSplit != nil {
		in, out := &in.AutoSplit, &out.AutoSplit
		*out = new(bool)
		**out = **in
	}
	if in.EnableWebTracking != nil {
		in, out := &in.EnableWebTracking, &out.EnableWebTracking
		*out = new(bool)
		**out = **in
	}
	if in.EncryptConf != nil {
		in, out := &in.EncryptConf, &out.EncryptConf
		*out = make([]EncryptConfParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HotTTL != nil {
		in, out := &in.HotTTL, &out.HotTTL
		*out = new(float64)
		**out = **in
	}
	if in.InfrequentAccessTTL != nil {
		in, out := &in.InfrequentAccessTTL, &out.InfrequentAccessTTL
		*out = new(float64)
		**out = **in
	}
	if in.LogstoreName != nil {
		in, out := &in.LogstoreName, &out.LogstoreName
		*out = new(string)
		**out = **in
	}
	if in.MaxSplitShardCount != nil {
		in, out := &in.MaxSplitShardCount, &out.MaxSplitShardCount
		*out = new(float64)
		**out = **in
	}
	if in.MeteringMode != nil {
		in, out := &in.MeteringMode, &out.MeteringMode
		*out = new(string)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.ProjectName != nil {
		in, out := &in.ProjectName, &out.ProjectName
		*out = new(string)
		**out = **in
	}
	if in.ProjectNameRef != nil {
		in, out := &in.ProjectNameRef, &out.ProjectNameRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectNameSelector != nil {
		in, out := &in.ProjectNameSelector, &out.ProjectNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.RetentionPeriod != nil {
		in, out := &in.RetentionPeriod, &out.RetentionPeriod
		*out = new(float64)
		**out = **in
	}
	if in.ShardCount != nil {
		in, out := &in.ShardCount, &out.ShardCount
		*out = new(float64)
		**out = **in
	}
	if in.TelemetryType != nil {
		in, out := &in.TelemetryType, &out.TelemetryType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreParameters.
func (in *StoreParameters) DeepCopy() *StoreParameters {
	if in == nil {
		return nil
	}
	out := new(StoreParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreSpec) DeepCopyInto(out *StoreSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreSpec.
func (in *StoreSpec) DeepCopy() *StoreSpec {
	if in == nil {
		return nil
	}
	out := new(StoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreStatus) DeepCopyInto(out *StoreStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreStatus.
func (in *StoreStatus) DeepCopy() *StoreStatus {
	if in == nil {
		return nil
	}
	out := new(StoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserCmkInfoInitParameters) DeepCopyInto(out *UserCmkInfoInitParameters) {
	*out = *in
	if in.Arn != nil {
		in, out := &in.Arn, &out.Arn
		*out = new(string)
		**out = **in
	}
	if in.CmkKeyID != nil {
		in, out := &in.CmkKeyID, &out.CmkKeyID
		*out = new(string)
		**out = **in
	}
	if in.CmkKeyIDRef != nil {
		in, out := &in.CmkKeyIDRef, &out.CmkKeyIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.CmkKeyIDSelector != nil {
		in, out := &in.CmkKeyIDSelector, &out.CmkKeyIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RegionID != nil {
		in, out := &in.RegionID, &out.RegionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserCmkInfoInitParameters.
func (in *UserCmkInfoInitParameters) DeepCopy() *UserCmkInfoInitParameters {
	if in == nil {
		return nil
	}
	out := new(UserCmkInfoInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserCmkInfoObservation) DeepCopyInto(out *UserCmkInfoObservation) {
	*out = *in
	if in.Arn != nil {
		in, out := &in.Arn, &out.Arn
		*out = new(string)
		**out = **in
	}
	if in.CmkKeyID != nil {
		in, out := &in.CmkKeyID, &out.CmkKeyID
		*out = new(string)
		**out = **in
	}
	if in.RegionID != nil {
		in, out := &in.RegionID, &out.RegionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserCmkInfoObservation.
func (in *UserCmkInfoObservation) DeepCopy() *UserCmkInfoObservation {
	if in == nil {
		return nil
	}
	out := new(UserCmkInfoObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserCmkInfoParameters) DeepCopyInto(out *UserCmkInfoParameters) {
	*out = *in
	if in.Arn != nil {
		in, out := &in.Arn, &out.Arn
		*out = new(string)
		**out = **in
	}
	if in.CmkKeyID != nil {
		in, out := &in.CmkKeyID, &out.CmkKeyID
		*out = new(string)
		**out = **in
	}
	if in.CmkKeyIDRef != nil {
		in, out := &in.CmkKeyIDRef, &out.CmkKeyIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.CmkKeyIDSelector != nil {
		in, out := &in.CmkKeyIDSelector, &out.CmkKeyIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RegionID != nil {
		in, out := &in.RegionID, &out.RegionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserCmkInfoParameters.
func (in *UserCmkInfoParameters) DeepCopy() *UserCmkInfoParameters {
	if in == nil {
		return nil
	}
	out := new(UserCmkInfoParameters)
	in.DeepCopyInto(out)
	return out
}
