// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EncryptConfInitParameters struct {

	// Enable encryption. Default false.
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// Supported encryption type, only supports default(AES), m4.
	EncryptType *string `json:"encryptType,omitempty" tf:"encrypt_type,omitempty"`

	// User bring your own key (BYOK) encryption Refer to details, the format is as follows. See user_cmk_info below. { "cmk_key_id": "your_cmk_key_id", "arn": "your_role_arn", "region_id": "you_cmk_region_id" }. See user_cmk_info below.
	UserCmkInfo []UserCmkInfoInitParameters `json:"userCmkInfo,omitempty" tf:"user_cmk_info,omitempty"`
}

type EncryptConfObservation struct {

	// Enable encryption. Default false.
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// Supported encryption type, only supports default(AES), m4.
	EncryptType *string `json:"encryptType,omitempty" tf:"encrypt_type,omitempty"`

	// User bring your own key (BYOK) encryption Refer to details, the format is as follows. See user_cmk_info below. { "cmk_key_id": "your_cmk_key_id", "arn": "your_role_arn", "region_id": "you_cmk_region_id" }. See user_cmk_info below.
	UserCmkInfo []UserCmkInfoObservation `json:"userCmkInfo,omitempty" tf:"user_cmk_info,omitempty"`
}

type EncryptConfParameters struct {

	// Enable encryption. Default false.
	// +kubebuilder:validation:Optional
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// Supported encryption type, only supports default(AES), m4.
	// +kubebuilder:validation:Optional
	EncryptType *string `json:"encryptType,omitempty" tf:"encrypt_type,omitempty"`

	// User bring your own key (BYOK) encryption Refer to details, the format is as follows. See user_cmk_info below. { "cmk_key_id": "your_cmk_key_id", "arn": "your_role_arn", "region_id": "you_cmk_region_id" }. See user_cmk_info below.
	// +kubebuilder:validation:Optional
	UserCmkInfo []UserCmkInfoParameters `json:"userCmkInfo,omitempty" tf:"user_cmk_info,omitempty"`
}

type ShardsInitParameters struct {
}

type ShardsObservation struct {

	// The begin value of the shard range(MD5), included in the shard range.
	BeginKey *string `json:"beginKey,omitempty" tf:"begin_key,omitempty"`

	// The end value of the shard range(MD5), not included in shard range.
	EndKey *string `json:"endKey,omitempty" tf:"end_key,omitempty"`

	// The ID of the resource supplied above.The value is formulated as <project_name>:<logstore_name>.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`

	// Shard status, only two status of readwrite and readonly.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type ShardsParameters struct {
}

type StoreInitParameters struct {

	// Determines whether to append log meta automatically. The meta includes log receive time and client IP address. Default to true.
	AppendMeta *bool `json:"appendMeta,omitempty" tf:"append_meta,omitempty"`

	// Determines whether to automatically split a shard. Default to false.
	AutoSplit *bool `json:"autoSplit,omitempty" tf:"auto_split,omitempty"`

	// Whether open webtracking. webtracking network tracing, support the collection of HTML log, H5, Ios and android platforms.
	EnableWebTracking *bool `json:"enableWebTracking,omitempty" tf:"enable_web_tracking,omitempty"`

	// Encrypted storage of data, providing data static protection capability, encrypt_conf can be updated since 1.188.0 (only enable change is supported when updating logstore). See encrypt_conf below.
	EncryptConf []EncryptConfInitParameters `json:"encryptConf,omitempty" tf:"encrypt_conf,omitempty"`

	// The ttl of hot storage. Default to 30, at least 30, hot storage ttl must be less than ttl.
	HotTTL *float64 `json:"hotTtl,omitempty" tf:"hot_ttl,omitempty"`

	// Low frequency storage time
	InfrequentAccessTTL *float64 `json:"infrequentAccessTtl,omitempty" tf:"infrequent_access_ttl,omitempty"`

	// The log store, which is unique in the same project. You need to specify one of the attributes: logstore_name, name.
	LogstoreName *string `json:"logstoreName,omitempty" tf:"logstore_name,omitempty"`

	// The maximum number of shards for automatic split, which is in the range of 1 to 256. You must specify this parameter when autoSplit is true.
	MaxSplitShardCount *float64 `json:"maxSplitShardCount,omitempty" tf:"max_split_shard_count,omitempty"`

	// Metering mode. The default metering mode of ChargeByFunction, ChargeByDataIngest traffic mode.
	MeteringMode *string `json:"meteringMode,omitempty" tf:"metering_mode,omitempty"`

	// The mode of storage. Default to standard, must be standard or query, lite.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// The project name to the log store belongs. You need to specify one of the attributes: project_name, project.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/sls/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	ProjectName *string `json:"projectName,omitempty" tf:"project_name,omitempty"`

	// Reference to a Project in sls to populate projectName.
	// +kubebuilder:validation:Optional
	ProjectNameRef *v1.Reference `json:"projectNameRef,omitempty" tf:"-"`

	// Selector for a Project in sls to populate projectName.
	// +kubebuilder:validation:Optional
	ProjectNameSelector *v1.Selector `json:"projectNameSelector,omitempty" tf:"-"`

	// The data retention time (in days). Valid values: [1-3650]. Default to 30. Log store data will be stored permanently when the value is 3650.
	RetentionPeriod *float64 `json:"retentionPeriod,omitempty" tf:"retention_period,omitempty"`

	// The number of shards in this log store. Default to 2. You can modify it by "Split" or "Merge" operations. Refer to details.
	ShardCount *float64 `json:"shardCount,omitempty" tf:"shard_count,omitempty"`

	// Determines whether store type is metric. Metrics means metric store, empty means log store.
	TelemetryType *string `json:"telemetryType,omitempty" tf:"telemetry_type,omitempty"`
}

type StoreObservation struct {

	// Determines whether to append log meta automatically. The meta includes log receive time and client IP address. Default to true.
	AppendMeta *bool `json:"appendMeta,omitempty" tf:"append_meta,omitempty"`

	// Determines whether to automatically split a shard. Default to false.
	AutoSplit *bool `json:"autoSplit,omitempty" tf:"auto_split,omitempty"`

	// Log library creation time. Unix timestamp format that represents the number of seconds from 1970-1-1 00:00:00 UTC calculation.
	CreateTime *float64 `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// Whether open webtracking. webtracking network tracing, support the collection of HTML log, H5, Ios and android platforms.
	EnableWebTracking *bool `json:"enableWebTracking,omitempty" tf:"enable_web_tracking,omitempty"`

	// Encrypted storage of data, providing data static protection capability, encrypt_conf can be updated since 1.188.0 (only enable change is supported when updating logstore). See encrypt_conf below.
	EncryptConf []EncryptConfObservation `json:"encryptConf,omitempty" tf:"encrypt_conf,omitempty"`

	// The ttl of hot storage. Default to 30, at least 30, hot storage ttl must be less than ttl.
	HotTTL *float64 `json:"hotTtl,omitempty" tf:"hot_ttl,omitempty"`

	// The ID of the resource supplied above.The value is formulated as <project_name>:<logstore_name>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Low frequency storage time
	InfrequentAccessTTL *float64 `json:"infrequentAccessTtl,omitempty" tf:"infrequent_access_ttl,omitempty"`

	// The log store, which is unique in the same project. You need to specify one of the attributes: logstore_name, name.
	LogstoreName *string `json:"logstoreName,omitempty" tf:"logstore_name,omitempty"`

	// The maximum number of shards for automatic split, which is in the range of 1 to 256. You must specify this parameter when autoSplit is true.
	MaxSplitShardCount *float64 `json:"maxSplitShardCount,omitempty" tf:"max_split_shard_count,omitempty"`

	// Metering mode. The default metering mode of ChargeByFunction, ChargeByDataIngest traffic mode.
	MeteringMode *string `json:"meteringMode,omitempty" tf:"metering_mode,omitempty"`

	// The mode of storage. Default to standard, must be standard or query, lite.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// The project name to the log store belongs. You need to specify one of the attributes: project_name, project.
	ProjectName *string `json:"projectName,omitempty" tf:"project_name,omitempty"`

	// The data retention time (in days). Valid values: [1-3650]. Default to 30. Log store data will be stored permanently when the value is 3650.
	RetentionPeriod *float64 `json:"retentionPeriod,omitempty" tf:"retention_period,omitempty"`

	// The number of shards in this log store. Default to 2. You can modify it by "Split" or "Merge" operations. Refer to details.
	ShardCount *float64 `json:"shardCount,omitempty" tf:"shard_count,omitempty"`

	// The shard attribute.
	Shards []ShardsObservation `json:"shards,omitempty" tf:"shards,omitempty"`

	// Determines whether store type is metric. Metrics means metric store, empty means log store.
	TelemetryType *string `json:"telemetryType,omitempty" tf:"telemetry_type,omitempty"`
}

type StoreParameters struct {

	// Determines whether to append log meta automatically. The meta includes log receive time and client IP address. Default to true.
	// +kubebuilder:validation:Optional
	AppendMeta *bool `json:"appendMeta,omitempty" tf:"append_meta,omitempty"`

	// Determines whether to automatically split a shard. Default to false.
	// +kubebuilder:validation:Optional
	AutoSplit *bool `json:"autoSplit,omitempty" tf:"auto_split,omitempty"`

	// Whether open webtracking. webtracking network tracing, support the collection of HTML log, H5, Ios and android platforms.
	// +kubebuilder:validation:Optional
	EnableWebTracking *bool `json:"enableWebTracking,omitempty" tf:"enable_web_tracking,omitempty"`

	// Encrypted storage of data, providing data static protection capability, encrypt_conf can be updated since 1.188.0 (only enable change is supported when updating logstore). See encrypt_conf below.
	// +kubebuilder:validation:Optional
	EncryptConf []EncryptConfParameters `json:"encryptConf,omitempty" tf:"encrypt_conf,omitempty"`

	// The ttl of hot storage. Default to 30, at least 30, hot storage ttl must be less than ttl.
	// +kubebuilder:validation:Optional
	HotTTL *float64 `json:"hotTtl,omitempty" tf:"hot_ttl,omitempty"`

	// Low frequency storage time
	// +kubebuilder:validation:Optional
	InfrequentAccessTTL *float64 `json:"infrequentAccessTtl,omitempty" tf:"infrequent_access_ttl,omitempty"`

	// The log store, which is unique in the same project. You need to specify one of the attributes: logstore_name, name.
	// +kubebuilder:validation:Optional
	LogstoreName *string `json:"logstoreName,omitempty" tf:"logstore_name,omitempty"`

	// The maximum number of shards for automatic split, which is in the range of 1 to 256. You must specify this parameter when autoSplit is true.
	// +kubebuilder:validation:Optional
	MaxSplitShardCount *float64 `json:"maxSplitShardCount,omitempty" tf:"max_split_shard_count,omitempty"`

	// Metering mode. The default metering mode of ChargeByFunction, ChargeByDataIngest traffic mode.
	// +kubebuilder:validation:Optional
	MeteringMode *string `json:"meteringMode,omitempty" tf:"metering_mode,omitempty"`

	// The mode of storage. Default to standard, must be standard or query, lite.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// The project name to the log store belongs. You need to specify one of the attributes: project_name, project.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/sls/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	// +kubebuilder:validation:Optional
	ProjectName *string `json:"projectName,omitempty" tf:"project_name,omitempty"`

	// Reference to a Project in sls to populate projectName.
	// +kubebuilder:validation:Optional
	ProjectNameRef *v1.Reference `json:"projectNameRef,omitempty" tf:"-"`

	// Selector for a Project in sls to populate projectName.
	// +kubebuilder:validation:Optional
	ProjectNameSelector *v1.Selector `json:"projectNameSelector,omitempty" tf:"-"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The data retention time (in days). Valid values: [1-3650]. Default to 30. Log store data will be stored permanently when the value is 3650.
	// +kubebuilder:validation:Optional
	RetentionPeriod *float64 `json:"retentionPeriod,omitempty" tf:"retention_period,omitempty"`

	// The number of shards in this log store. Default to 2. You can modify it by "Split" or "Merge" operations. Refer to details.
	// +kubebuilder:validation:Optional
	ShardCount *float64 `json:"shardCount,omitempty" tf:"shard_count,omitempty"`

	// Determines whether store type is metric. Metrics means metric store, empty means log store.
	// +kubebuilder:validation:Optional
	TelemetryType *string `json:"telemetryType,omitempty" tf:"telemetry_type,omitempty"`
}

type UserCmkInfoInitParameters struct {

	// Role arn.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// User master key id.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/kms/v1alpha1.Key
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	CmkKeyID *string `json:"cmkKeyId,omitempty" tf:"cmk_key_id,omitempty"`

	// Reference to a Key in kms to populate cmkKeyId.
	// +kubebuilder:validation:Optional
	CmkKeyIDRef *v1.Reference `json:"cmkKeyIdRef,omitempty" tf:"-"`

	// Selector for a Key in kms to populate cmkKeyId.
	// +kubebuilder:validation:Optional
	CmkKeyIDSelector *v1.Selector `json:"cmkKeyIdSelector,omitempty" tf:"-"`

	// Region id where the user master key id is located.
	RegionID *string `json:"regionId,omitempty" tf:"region_id,omitempty"`
}

type UserCmkInfoObservation struct {

	// Role arn.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// User master key id.
	CmkKeyID *string `json:"cmkKeyId,omitempty" tf:"cmk_key_id,omitempty"`

	// Region id where the user master key id is located.
	RegionID *string `json:"regionId,omitempty" tf:"region_id,omitempty"`
}

type UserCmkInfoParameters struct {

	// Role arn.
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// User master key id.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/kms/v1alpha1.Key
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	CmkKeyID *string `json:"cmkKeyId,omitempty" tf:"cmk_key_id,omitempty"`

	// Reference to a Key in kms to populate cmkKeyId.
	// +kubebuilder:validation:Optional
	CmkKeyIDRef *v1.Reference `json:"cmkKeyIdRef,omitempty" tf:"-"`

	// Selector for a Key in kms to populate cmkKeyId.
	// +kubebuilder:validation:Optional
	CmkKeyIDSelector *v1.Selector `json:"cmkKeyIdSelector,omitempty" tf:"-"`

	// Region id where the user master key id is located.
	// +kubebuilder:validation:Optional
	RegionID *string `json:"regionId,omitempty" tf:"region_id,omitempty"`
}

// StoreSpec defines the desired state of Store
type StoreSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     StoreParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider StoreInitParameters `json:"initProvider,omitempty"`
}

// StoreStatus defines the observed state of Store.
type StoreStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        StoreObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Store is the Schema for the Stores API. Provides a Alicloud SLS Log Store resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type Store struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              StoreSpec   `json:"spec"`
	Status            StoreStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// StoreList contains a list of Stores
type StoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Store `json:"items"`
}

// Repository type metadata.
var (
	Store_Kind             = "Store"
	Store_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Store_Kind}.String()
	Store_KindAPIVersion   = Store_Kind + "." + CRDGroupVersion.String()
	Store_GroupVersionKind = CRDGroupVersion.WithKind(Store_Kind)
)

func init() {
	SchemeBuilder.Register(&Store{}, &StoreList{})
}
