apiVersion: alikafka.alibabacloud.crossplane.io/v1alpha1
kind: SaslACL
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/saslacl
  labels:
    testing.upbound.io/example-name: saslacl
  name: saslacl
spec:
  forProvider:
    region: cn-beijing
    aclOperationType: Write
    aclResourceType: Topic
    aclResourcePatternType: LITERAL
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: saslacl
    usernameSelector:
      matchLabels:
        testing.upbound.io/example-name: saslacl
    aclResourceNameSelector:
      matchLabels:
        testing.upbound.io/example-name: saslacl

---

apiVersion: alikafka.alibabacloud.crossplane.io/v1alpha1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/saslacl
  labels:
    testing.upbound.io/example-name: saslacl
  name: saslacl
spec:
  forProvider:
    region: cn-beijing
    topic: crossplane-example-acl-topic
    remark: topic-remark
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: saslacl

---

apiVersion: alikafka.alibabacloud.crossplane.io/v1alpha1
kind: SaslUser
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/saslacl
  labels:
    testing.upbound.io/example-name: saslacl
  name: saslacl
spec:
  forProvider:
    region: cn-beijing
    username: crossplane-example-acl-user
    passwordSecretRef:
      key: password
      name: alikafka-saslacl-user-password
      namespace: upbound-system
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: saslacl

---

apiVersion: v1
kind: Secret
metadata:
  name: alikafka-saslacl-user-password
  namespace: upbound-system
type: Opaque
stringData:
  password: Crossplane123

---

apiVersion: alikafka.alibabacloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/saslacl
  labels:
    testing.upbound.io/example-name: saslacl
  name: saslacl
spec:
  forProvider:
    region: cn-beijing
    name: crossplane-example-for-alikafka-saslacl
    config: '{"enable.acl":"true"}'
    partitionNum: 50
    diskType: 1
    diskSize: 500
    deployType: 5
    ioMax: 20
    specType: professional
    serviceVersion: 2.2.0
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: saslacl
    securityGroupSelector:
      matchLabels:
        testing.upbound.io/example-name: saslacl

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/saslacl
  labels:
    testing.upbound.io/example-name: saslacl
  name: saslacl
spec:
  forProvider:
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: saslacl

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/saslacl
  labels:
    testing.upbound.io/example-name: saslacl
  name: saslacl
spec:
  forProvider:
    region: cn-beijing
    vpcName: crossplane-example-for-alikafka-saslacl
    cidrBlock: 10.4.0.0/16

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/saslacl
  labels:
    testing.upbound.io/example-name: saslacl
  name: saslacl
spec:
  forProvider:
    region: cn-beijing
    vswitchName: crossplane-example-for-alikafka-saslacl
    cidrBlock: 10.4.0.0/24
    zoneId: cn-beijing-h
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: saslacl
