// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CertificateInitParameters struct {

	// The content of a non-SM certificate in PEM format.
	CertSecretRef *v1.SecretKeySelector `json:"certSecretRef,omitempty" tf:"-"`

	// A custom name for the certificate. The name can be up to 64 characters long and can contain any character type, such as letters, numbers, and underscores. NOTE: From version 1.260.1, certificate_name can be modified.
	CertificateName *string `json:"certificateName,omitempty" tf:"certificate_name,omitempty"`

	// The content of an SM encryption certificate in PEM format.
	EncryptCert *string `json:"encryptCert,omitempty" tf:"encrypt_cert,omitempty"`

	// The private key of an SM encryption certificate in PEM format.
	EncryptPrivateKeySecretRef *v1.SecretKeySelector `json:"encryptPrivateKeySecretRef,omitempty" tf:"-"`

	// The private key of a non-SM certificate in PEM format.
	KeySecretRef *v1.SecretKeySelector `json:"keySecretRef,omitempty" tf:"-"`

	// The ID of the resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The content of an SM signing certificate in PEM format.
	SignCert *string `json:"signCert,omitempty" tf:"sign_cert,omitempty"`

	// The private key of an SM signing certificate in PEM format.
	SignPrivateKeySecretRef *v1.SecretKeySelector `json:"signPrivateKeySecretRef,omitempty" tf:"-"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type CertificateObservation struct {

	// A custom name for the certificate. The name can be up to 64 characters long and can contain any character type, such as letters, numbers, and underscores. NOTE: From version 1.260.1, certificate_name can be modified.
	CertificateName *string `json:"certificateName,omitempty" tf:"certificate_name,omitempty"`

	// The content of an SM encryption certificate in PEM format.
	EncryptCert *string `json:"encryptCert,omitempty" tf:"encrypt_cert,omitempty"`

	// The ID of the resource supplied above.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The content of an SM signing certificate in PEM format.
	SignCert *string `json:"signCert,omitempty" tf:"sign_cert,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type CertificateParameters struct {

	// The content of a non-SM certificate in PEM format.
	// +kubebuilder:validation:Optional
	CertSecretRef *v1.SecretKeySelector `json:"certSecretRef,omitempty" tf:"-"`

	// A custom name for the certificate. The name can be up to 64 characters long and can contain any character type, such as letters, numbers, and underscores. NOTE: From version 1.260.1, certificate_name can be modified.
	// +kubebuilder:validation:Optional
	CertificateName *string `json:"certificateName,omitempty" tf:"certificate_name,omitempty"`

	// The content of an SM encryption certificate in PEM format.
	// +kubebuilder:validation:Optional
	EncryptCert *string `json:"encryptCert,omitempty" tf:"encrypt_cert,omitempty"`

	// The private key of an SM encryption certificate in PEM format.
	// +kubebuilder:validation:Optional
	EncryptPrivateKeySecretRef *v1.SecretKeySelector `json:"encryptPrivateKeySecretRef,omitempty" tf:"-"`

	// The private key of a non-SM certificate in PEM format.
	// +kubebuilder:validation:Optional
	KeySecretRef *v1.SecretKeySelector `json:"keySecretRef,omitempty" tf:"-"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The ID of the resource group.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The content of an SM signing certificate in PEM format.
	// +kubebuilder:validation:Optional
	SignCert *string `json:"signCert,omitempty" tf:"sign_cert,omitempty"`

	// The private key of an SM signing certificate in PEM format.
	// +kubebuilder:validation:Optional
	SignPrivateKeySecretRef *v1.SecretKeySelector `json:"signPrivateKeySecretRef,omitempty" tf:"-"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// CertificateSpec defines the desired state of Certificate
type CertificateSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CertificateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CertificateInitParameters `json:"initProvider,omitempty"`
}

// CertificateStatus defines the observed state of Certificate.
type CertificateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CertificateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Certificate is the Schema for the Certificates API. Provides a Alicloud SSL Certificates Certificate resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type Certificate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CertificateSpec   `json:"spec"`
	Status            CertificateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CertificateList contains a list of Certificates
type CertificateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Certificate `json:"items"`
}

// Repository type metadata.
var (
	Certificate_Kind             = "Certificate"
	Certificate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Certificate_Kind}.String()
	Certificate_KindAPIVersion   = Certificate_Kind + "." + CRDGroupVersion.String()
	Certificate_GroupVersionKind = CRDGroupVersion.WithKind(Certificate_Kind)
)

func init() {
	SchemeBuilder.Register(&Certificate{}, &CertificateList{})
}
