// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

package rds

import (
	"github.com/crossplane/upjet/pkg/config"

	"github.com/crossplane-contrib/provider-alibabacloud/config/common"
)

// Configure configures individual resources by adding custom ResourceConfigurators.
func Configure(p *config.Provider) {
	p.AddResourceConfigurator("alicloud_db_instance", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
		r.UseAsync = true
		r.References["vswitch_id"] = config.Reference{
			TerraformName: "alicloud_vswitch",
			Extractor:     common.PathIdExtractor,
		}
		// Drop the deprecated singular form; it collides with the
		// security_group_ids reference fields generated by KnownReferences.
		delete(r.TerraformResource.Schema, "security_group_id")
	})
	p.AddResourceConfigurator("alicloud_db_readonly_instance", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
		r.UseAsync = true
		r.References["master_db_instance_id"] = config.Reference{
			TerraformName: "alicloud_db_instance",
			Extractor:     common.PathIdExtractor,
		}
		r.References["vswitch_id"] = config.Reference{
			TerraformName: "alicloud_vswitch",
			Extractor:     common.PathIdExtractor,
		}
	})
	// NOTE: alicloud_db_account and alicloud_db_account_privilege (the
	// legacy account resources, superseded by alicloud_rds_account) are
	// intentionally NOT configured here and are excluded from the provider
	// via config/external_name.go (they carry deprecated ConflictsWith
	// field aliases and collide with alicloud_rds_account on kind Account).
	// Use alicloud_rds_account instead.
	p.AddResourceConfigurator("alicloud_db_backup_policy", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
		r.References["instance_id"] = config.Reference{
			TerraformName: "alicloud_db_instance",
			Extractor:     common.PathIdExtractor,
		}
		// Deprecated, computed aliases that collide with their non-deprecated
		// replacements on TF refresh (ConflictsWith). Drop each so only the
		// canonical field is managed.
		delete(r.TerraformResource.Schema, "backup_period")        // -> preferred_backup_period
		delete(r.TerraformResource.Schema, "backup_time")          // -> preferred_backup_time
		delete(r.TerraformResource.Schema, "log_backup")           // -> enable_backup_log
		delete(r.TerraformResource.Schema, "log_retention_period") // -> log_backup_retention_period
		delete(r.TerraformResource.Schema, "retention_period")     // -> backup_retention_period
	})
	p.AddResourceConfigurator("alicloud_db_connection", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
		r.References["instance_id"] = config.Reference{
			TerraformName: "alicloud_db_instance",
			Extractor:     common.PathIdExtractor,
		}
	})
	p.AddResourceConfigurator("alicloud_db_database", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
		r.References["instance_id"] = config.Reference{
			TerraformName: "alicloud_db_instance",
			Extractor:     common.PathIdExtractor,
		}
		// "name" is a deprecated, computed alias of "data_base_name"; both
		// being computed causes TF refresh to fail with a ConflictsWith error
		// ("data_base_name" conflicts with "name"). Drop the deprecated one.
		delete(r.TerraformResource.Schema, "name")
	})
	p.AddResourceConfigurator("alicloud_db_read_write_splitting_connection", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
		r.References["instance_id"] = config.Reference{
			TerraformName: "alicloud_db_instance",
			Extractor:     common.PathIdExtractor,
		}
	})

	p.AddResourceConfigurator("alicloud_rds_account", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
		r.References["db_instance_id"] = config.Reference{
			TerraformName: "alicloud_db_instance",
			Extractor:     common.PathIdExtractor,
		}
		// Same deprecated-alias conflict as alicloud_db_account (see above).
		delete(r.TerraformResource.Schema, "name")        // -> account_name
		delete(r.TerraformResource.Schema, "type")        // -> account_type
		delete(r.TerraformResource.Schema, "instance_id") // -> db_instance_id
		delete(r.TerraformResource.Schema, "description") // -> account_description
		delete(r.TerraformResource.Schema, "password")    // -> account_password
	})
	p.AddResourceConfigurator("alicloud_rds_backup", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
		r.References["db_instance_id"] = config.Reference{
			TerraformName: "alicloud_db_instance",
			Extractor:     common.PathIdExtractor,
		}
	})
	p.AddResourceConfigurator("alicloud_rds_db_instance_endpoint", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
		r.References["db_instance_id"] = config.Reference{
			TerraformName: "alicloud_db_instance",
			Extractor:     common.PathIdExtractor,
		}
	})
	p.AddResourceConfigurator("alicloud_rds_db_instance_endpoint_address", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
		r.References["db_instance_id"] = config.Reference{
			TerraformName: "alicloud_db_instance",
			Extractor:     common.PathIdExtractor,
		}
		r.References["db_instance_endpoint_id"] = config.Reference{
			TerraformName: "alicloud_rds_db_instance_endpoint",
			Extractor:     common.PathIdExtractor,
		}
	})
	p.AddResourceConfigurator("alicloud_rds_db_node", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
		r.References["db_instance_id"] = config.Reference{
			TerraformName: "alicloud_db_instance",
			Extractor:     common.PathIdExtractor,
		}
	})
	p.AddResourceConfigurator("alicloud_rds_db_proxy", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
		r.References["instance_id"] = config.Reference{
			TerraformName: "alicloud_db_instance",
			Extractor:     common.PathIdExtractor,
		}
		r.References["vswitch_id"] = config.Reference{
			TerraformName: "alicloud_vswitch",
			Extractor:     common.PathIdExtractor,
		}
	})
	p.AddResourceConfigurator("alicloud_rds_db_proxy_public", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
		r.References["db_instance_id"] = config.Reference{
			TerraformName: "alicloud_db_instance",
			Extractor:     common.PathIdExtractor,
		}
	})
	p.AddResourceConfigurator("alicloud_rds_instance_cross_backup_policy", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
		r.References["instance_id"] = config.Reference{
			TerraformName: "alicloud_db_instance",
			Extractor:     common.PathIdExtractor,
		}
	})
	p.AddResourceConfigurator("alicloud_rds_parameter_group", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
	})
	p.AddResourceConfigurator("alicloud_rds_service_linked_role", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
	})
	p.AddResourceConfigurator("alicloud_rds_whitelist_template", func(r *config.Resource) {
		r.ShortGroup = string(common.RDS)
	})
}
