apiVersion: rds.alibabacloud.crossplane.io/v1alpha1
kind: InstanceCrossBackupPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/instancecrossbackuppolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    crossBackupRegion: ${data.alicloud_rds_cross_regions.regions.ids.0}
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    region: cn-beijing

---

apiVersion: rds.alibabacloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/instancecrossbackuppolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    category: HighAvailability
    dbInstanceStorageType: local_ssd
    engine: MySQL
    engineVersion: "8.0"
    instanceChargeType: Postpaid
    instanceName: ${var.name}
    instanceStorage: ${data.alicloud_db_instance_classes.default.instance_classes.0.storage_range.min}
    instanceType: ${data.alicloud_db_instance_classes.default.instance_classes.0.instance_class}
    region: cn-beijing
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/instancecrossbackuppolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.16.0.0/16
    region: cn-beijing
    vpcName: ${var.name}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/instancecrossbackuppolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.16.0.0/24
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    vswitchName: ${var.name}
    zoneId: ${data.alicloud_db_zones.default.ids.0}
