// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DBNodeInitParameters struct {

	// The specification information of the node.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/rds/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractParamPath("instance_type",false)
	ClassCode *string `json:"classCode,omitempty" tf:"class_code,omitempty"`

	// Reference to a Instance in rds to populate classCode.
	// +kubebuilder:validation:Optional
	ClassCodeRef *v1.Reference `json:"classCodeRef,omitempty" tf:"-"`

	// Selector for a Instance in rds to populate classCode.
	// +kubebuilder:validation:Optional
	ClassCodeSelector *v1.Selector `json:"classCodeSelector,omitempty" tf:"-"`

	// The Id of instance that can run database.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/rds/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	DBInstanceID *string `json:"dbInstanceId,omitempty" tf:"db_instance_id,omitempty"`

	// Reference to a Instance in rds to populate dbInstanceId.
	// +kubebuilder:validation:Optional
	DBInstanceIDRef *v1.Reference `json:"dbInstanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in rds to populate dbInstanceId.
	// +kubebuilder:validation:Optional
	DBInstanceIDSelector *v1.Selector `json:"dbInstanceIdSelector,omitempty" tf:"-"`

	// The zone ID of the node.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.Vswitch
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractParamPath("zone_id",false)
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Vswitch in vpc to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.Reference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Vswitch in vpc to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.Selector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type DBNodeObservation struct {

	// The specification information of the node.
	ClassCode *string `json:"classCode,omitempty" tf:"class_code,omitempty"`

	// The Id of instance that can run database.
	DBInstanceID *string `json:"dbInstanceId,omitempty" tf:"db_instance_id,omitempty"`

	// The value formats as <db_instance_id>:<node_id>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the node.
	NodeID *string `json:"nodeId,omitempty" tf:"node_id,omitempty"`

	// The region ID of the node.
	NodeRegionID *string `json:"nodeRegionId,omitempty" tf:"node_region_id,omitempty"`

	// The role of node.
	NodeRole *string `json:"nodeRole,omitempty" tf:"node_role,omitempty"`

	// The zone ID of the node.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type DBNodeParameters struct {

	// The specification information of the node.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/rds/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractParamPath("instance_type",false)
	// +kubebuilder:validation:Optional
	ClassCode *string `json:"classCode,omitempty" tf:"class_code,omitempty"`

	// Reference to a Instance in rds to populate classCode.
	// +kubebuilder:validation:Optional
	ClassCodeRef *v1.Reference `json:"classCodeRef,omitempty" tf:"-"`

	// Selector for a Instance in rds to populate classCode.
	// +kubebuilder:validation:Optional
	ClassCodeSelector *v1.Selector `json:"classCodeSelector,omitempty" tf:"-"`

	// The Id of instance that can run database.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/rds/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	// +kubebuilder:validation:Optional
	DBInstanceID *string `json:"dbInstanceId,omitempty" tf:"db_instance_id,omitempty"`

	// Reference to a Instance in rds to populate dbInstanceId.
	// +kubebuilder:validation:Optional
	DBInstanceIDRef *v1.Reference `json:"dbInstanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in rds to populate dbInstanceId.
	// +kubebuilder:validation:Optional
	DBInstanceIDSelector *v1.Selector `json:"dbInstanceIdSelector,omitempty" tf:"-"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The zone ID of the node.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.Vswitch
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractParamPath("zone_id",false)
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Vswitch in vpc to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.Reference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Vswitch in vpc to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.Selector `json:"zoneIdSelector,omitempty" tf:"-"`
}

// DBNodeSpec defines the desired state of DBNode
type DBNodeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DBNodeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DBNodeInitParameters `json:"initProvider,omitempty"`
}

// DBNodeStatus defines the observed state of DBNode.
type DBNodeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DBNodeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DBNode is the Schema for the DBNodes API. Provide RDS cluster instance to increase node resources.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type DBNode struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DBNodeSpec   `json:"spec"`
	Status            DBNodeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DBNodeList contains a list of DBNodes
type DBNodeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DBNode `json:"items"`
}

// Repository type metadata.
var (
	DBNode_Kind             = "DBNode"
	DBNode_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DBNode_Kind}.String()
	DBNode_KindAPIVersion   = DBNode_Kind + "." + CRDGroupVersion.String()
	DBNode_GroupVersionKind = CRDGroupVersion.WithKind(DBNode_Kind)
)

func init() {
	SchemeBuilder.Register(&DBNode{}, &DBNodeList{})
}
