// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DBProxyInitParameters struct {

	// The port number that is associated with the proxy endpoint.
	DBProxyConnectStringPort *float64 `json:"dbProxyConnectStringPort,omitempty" tf:"db_proxy_connect_string_port,omitempty"`

	// The new prefix of the proxy endpoint. Enter a prefix.
	DBProxyConnectionPrefix *string `json:"dbProxyConnectionPrefix,omitempty" tf:"db_proxy_connection_prefix,omitempty"`

	// The read and write attributes of the proxy terminal. Valid values:
	DBProxyEndpointReadWriteMode *string `json:"dbProxyEndpointReadWriteMode,omitempty" tf:"db_proxy_endpoint_read_write_mode,omitempty"`

	// The features that you want to enable for the proxy endpoint. If you specify more than one feature, separate the features with semicolons (;). Format: Feature 1:Status;Feature 2:Status;.... Do not add a semicolon (;) at the end of the last value. Valid feature values:
	DBProxyFeatures *string `json:"dbProxyFeatures,omitempty" tf:"db_proxy_features,omitempty"`

	// The number of proxy instances that are enabled. Valid values: 1 to 60.
	DBProxyInstanceNum *float64 `json:"dbProxyInstanceNum,omitempty" tf:"db_proxy_instance_num,omitempty"`

	// The database proxy type. Valid values:
	DBProxyInstanceType *string `json:"dbProxyInstanceType,omitempty" tf:"db_proxy_instance_type,omitempty"`

	// The SSL configuration setting that you want to apply on the instance. Valid values:
	DBProxySSLEnabled *string `json:"dbProxySslEnabled,omitempty" tf:"db_proxy_ssl_enabled,omitempty"`

	// The point in time at which you want to apply the new database proxy settings. Specify the time in the ISO 8601 standard in the yyyy-MM-ddTHH:mm:ssZ format. The time must be in UTC.
	EffectiveSpecificTime *string `json:"effectiveSpecificTime,omitempty" tf:"effective_specific_time,omitempty"`

	// When modifying the number of proxy instances,The time when you want to apply the new database proxy settings.Valid values:
	EffectiveTime *string `json:"effectiveTime,omitempty" tf:"effective_time,omitempty"`

	// The Id of instance that can run database.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/rds/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in rds to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in rds to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The network type of the instance. Set the value to VPC.
	InstanceNetworkType *string `json:"instanceNetworkType,omitempty" tf:"instance_network_type,omitempty"`

	// The policy that is used to allocate read weights. Valid values:
	ReadOnlyInstanceDistributionType *string `json:"readOnlyInstanceDistributionType,omitempty" tf:"read_only_instance_distribution_type,omitempty"`

	// The maximum latency threshold that is allowed for read/write splitting. If the latency on a read-only instance exceeds the threshold that you specified, ApsaraDB RDS no longer forwards read requests to the read-only instance. If you do not specify this parameter, the default value of this parameter is retained. Unit: seconds. Valid values: 0 to 3600.
	ReadOnlyInstanceMaxDelayTime *float64 `json:"readOnlyInstanceMaxDelayTime,omitempty" tf:"read_only_instance_max_delay_time,omitempty"`

	// A list of the read weights of the instance and its read-only instances.  It contains two sub-fields(instance_id and weight). Read weights increase in increments of 100, and the maximum read weight is 10000. See read_only_instance_weight below.
	ReadOnlyInstanceWeight []ReadOnlyInstanceWeightInitParameters `json:"readOnlyInstanceWeight,omitempty" tf:"read_only_instance_weight,omitempty"`

	// The ID of the resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The point in time at which you want to upgrade the database proxy version of the instance. Specify the time in the ISO 8601 standard in the yyyy-MM-ddTHH:mm:ssZ format. The time must be in UTC.
	SwitchTime *string `json:"switchTime,omitempty" tf:"switch_time,omitempty"`

	// The time when you want to upgrade the database proxy version of the instance. Valid values:
	UpgradeTime *string `json:"upgradeTime,omitempty" tf:"upgrade_time,omitempty"`

	// The ID of the virtual private cloud (VPC) to which the instance belongs.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.VPC
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Reference to a VPC in vpc to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDRef *v1.Reference `json:"vpcIdRef,omitempty" tf:"-"`

	// Selector for a VPC in vpc to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDSelector *v1.Selector `json:"vpcIdSelector,omitempty" tf:"-"`

	// The ID of the vSwitch that is associated with the specified VPC.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.Vswitch
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// Reference to a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDRef *v1.Reference `json:"vswitchIdRef,omitempty" tf:"-"`

	// Selector for a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDSelector *v1.Selector `json:"vswitchIdSelector,omitempty" tf:"-"`
}

type DBProxyObservation struct {

	// The port number that is associated with the proxy endpoint.
	DBProxyConnectStringPort *float64 `json:"dbProxyConnectStringPort,omitempty" tf:"db_proxy_connect_string_port,omitempty"`

	// The new prefix of the proxy endpoint. Enter a prefix.
	DBProxyConnectionPrefix *string `json:"dbProxyConnectionPrefix,omitempty" tf:"db_proxy_connection_prefix,omitempty"`

	// Connection instance string.
	DBProxyConnectionString *string `json:"dbProxyConnectionString,omitempty" tf:"db_proxy_connection_string,omitempty"`

	// Remarks of agent terminal.
	DBProxyEndpointAliases *string `json:"dbProxyEndpointAliases,omitempty" tf:"db_proxy_endpoint_aliases,omitempty"`

	// Proxy connection address ID.
	DBProxyEndpointID *string `json:"dbProxyEndpointId,omitempty" tf:"db_proxy_endpoint_id,omitempty"`

	// The read and write attributes of the proxy terminal. Valid values:
	DBProxyEndpointReadWriteMode *string `json:"dbProxyEndpointReadWriteMode,omitempty" tf:"db_proxy_endpoint_read_write_mode,omitempty"`

	// The features that you want to enable for the proxy endpoint. If you specify more than one feature, separate the features with semicolons (;). Format: Feature 1:Status;Feature 2:Status;.... Do not add a semicolon (;) at the end of the last value. Valid feature values:
	DBProxyFeatures *string `json:"dbProxyFeatures,omitempty" tf:"db_proxy_features,omitempty"`

	// The number of proxy instances that are enabled. Valid values: 1 to 60.
	DBProxyInstanceNum *float64 `json:"dbProxyInstanceNum,omitempty" tf:"db_proxy_instance_num,omitempty"`

	// The database proxy type. Valid values:
	DBProxyInstanceType *string `json:"dbProxyInstanceType,omitempty" tf:"db_proxy_instance_type,omitempty"`

	// The SSL configuration setting that you want to apply on the instance. Valid values:
	DBProxySSLEnabled *string `json:"dbProxySslEnabled,omitempty" tf:"db_proxy_ssl_enabled,omitempty"`

	// The point in time at which you want to apply the new database proxy settings. Specify the time in the ISO 8601 standard in the yyyy-MM-ddTHH:mm:ssZ format. The time must be in UTC.
	EffectiveSpecificTime *string `json:"effectiveSpecificTime,omitempty" tf:"effective_specific_time,omitempty"`

	// When modifying the number of proxy instances,The time when you want to apply the new database proxy settings.Valid values:
	EffectiveTime *string `json:"effectiveTime,omitempty" tf:"effective_time,omitempty"`

	// The Id of DB instance.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The Id of instance that can run database.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The network type of the instance. Set the value to VPC.
	InstanceNetworkType *string `json:"instanceNetworkType,omitempty" tf:"instance_network_type,omitempty"`

	// Network type of proxy connection address.
	NetType *string `json:"netType,omitempty" tf:"net_type,omitempty"`

	// The policy that is used to allocate read weights. Valid values:
	ReadOnlyInstanceDistributionType *string `json:"readOnlyInstanceDistributionType,omitempty" tf:"read_only_instance_distribution_type,omitempty"`

	// The maximum latency threshold that is allowed for read/write splitting. If the latency on a read-only instance exceeds the threshold that you specified, ApsaraDB RDS no longer forwards read requests to the read-only instance. If you do not specify this parameter, the default value of this parameter is retained. Unit: seconds. Valid values: 0 to 3600.
	ReadOnlyInstanceMaxDelayTime *float64 `json:"readOnlyInstanceMaxDelayTime,omitempty" tf:"read_only_instance_max_delay_time,omitempty"`

	// A list of the read weights of the instance and its read-only instances.  It contains two sub-fields(instance_id and weight). Read weights increase in increments of 100, and the maximum read weight is 10000. See read_only_instance_weight below.
	ReadOnlyInstanceWeight []ReadOnlyInstanceWeightObservation `json:"readOnlyInstanceWeight,omitempty" tf:"read_only_instance_weight,omitempty"`

	// The ID of the resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The time when the certificate expires.
	SSLExpiredTime *string `json:"sslExpiredTime,omitempty" tf:"ssl_expired_time,omitempty"`

	// The point in time at which you want to upgrade the database proxy version of the instance. Specify the time in the ISO 8601 standard in the yyyy-MM-ddTHH:mm:ssZ format. The time must be in UTC.
	SwitchTime *string `json:"switchTime,omitempty" tf:"switch_time,omitempty"`

	// The time when you want to upgrade the database proxy version of the instance. Valid values:
	UpgradeTime *string `json:"upgradeTime,omitempty" tf:"upgrade_time,omitempty"`

	// The ID of the virtual private cloud (VPC) to which the instance belongs.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// The ID of the vSwitch that is associated with the specified VPC.
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`
}

type DBProxyParameters struct {

	// The port number that is associated with the proxy endpoint.
	// +kubebuilder:validation:Optional
	DBProxyConnectStringPort *float64 `json:"dbProxyConnectStringPort,omitempty" tf:"db_proxy_connect_string_port,omitempty"`

	// The new prefix of the proxy endpoint. Enter a prefix.
	// +kubebuilder:validation:Optional
	DBProxyConnectionPrefix *string `json:"dbProxyConnectionPrefix,omitempty" tf:"db_proxy_connection_prefix,omitempty"`

	// The read and write attributes of the proxy terminal. Valid values:
	// +kubebuilder:validation:Optional
	DBProxyEndpointReadWriteMode *string `json:"dbProxyEndpointReadWriteMode,omitempty" tf:"db_proxy_endpoint_read_write_mode,omitempty"`

	// The features that you want to enable for the proxy endpoint. If you specify more than one feature, separate the features with semicolons (;). Format: Feature 1:Status;Feature 2:Status;.... Do not add a semicolon (;) at the end of the last value. Valid feature values:
	// +kubebuilder:validation:Optional
	DBProxyFeatures *string `json:"dbProxyFeatures,omitempty" tf:"db_proxy_features,omitempty"`

	// The number of proxy instances that are enabled. Valid values: 1 to 60.
	// +kubebuilder:validation:Optional
	DBProxyInstanceNum *float64 `json:"dbProxyInstanceNum,omitempty" tf:"db_proxy_instance_num,omitempty"`

	// The database proxy type. Valid values:
	// +kubebuilder:validation:Optional
	DBProxyInstanceType *string `json:"dbProxyInstanceType,omitempty" tf:"db_proxy_instance_type,omitempty"`

	// The SSL configuration setting that you want to apply on the instance. Valid values:
	// +kubebuilder:validation:Optional
	DBProxySSLEnabled *string `json:"dbProxySslEnabled,omitempty" tf:"db_proxy_ssl_enabled,omitempty"`

	// The point in time at which you want to apply the new database proxy settings. Specify the time in the ISO 8601 standard in the yyyy-MM-ddTHH:mm:ssZ format. The time must be in UTC.
	// +kubebuilder:validation:Optional
	EffectiveSpecificTime *string `json:"effectiveSpecificTime,omitempty" tf:"effective_specific_time,omitempty"`

	// When modifying the number of proxy instances,The time when you want to apply the new database proxy settings.Valid values:
	// +kubebuilder:validation:Optional
	EffectiveTime *string `json:"effectiveTime,omitempty" tf:"effective_time,omitempty"`

	// The Id of instance that can run database.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/rds/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in rds to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in rds to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The network type of the instance. Set the value to VPC.
	// +kubebuilder:validation:Optional
	InstanceNetworkType *string `json:"instanceNetworkType,omitempty" tf:"instance_network_type,omitempty"`

	// The policy that is used to allocate read weights. Valid values:
	// +kubebuilder:validation:Optional
	ReadOnlyInstanceDistributionType *string `json:"readOnlyInstanceDistributionType,omitempty" tf:"read_only_instance_distribution_type,omitempty"`

	// The maximum latency threshold that is allowed for read/write splitting. If the latency on a read-only instance exceeds the threshold that you specified, ApsaraDB RDS no longer forwards read requests to the read-only instance. If you do not specify this parameter, the default value of this parameter is retained. Unit: seconds. Valid values: 0 to 3600.
	// +kubebuilder:validation:Optional
	ReadOnlyInstanceMaxDelayTime *float64 `json:"readOnlyInstanceMaxDelayTime,omitempty" tf:"read_only_instance_max_delay_time,omitempty"`

	// A list of the read weights of the instance and its read-only instances.  It contains two sub-fields(instance_id and weight). Read weights increase in increments of 100, and the maximum read weight is 10000. See read_only_instance_weight below.
	// +kubebuilder:validation:Optional
	ReadOnlyInstanceWeight []ReadOnlyInstanceWeightParameters `json:"readOnlyInstanceWeight,omitempty" tf:"read_only_instance_weight,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The ID of the resource group.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The point in time at which you want to upgrade the database proxy version of the instance. Specify the time in the ISO 8601 standard in the yyyy-MM-ddTHH:mm:ssZ format. The time must be in UTC.
	// +kubebuilder:validation:Optional
	SwitchTime *string `json:"switchTime,omitempty" tf:"switch_time,omitempty"`

	// The time when you want to upgrade the database proxy version of the instance. Valid values:
	// +kubebuilder:validation:Optional
	UpgradeTime *string `json:"upgradeTime,omitempty" tf:"upgrade_time,omitempty"`

	// The ID of the virtual private cloud (VPC) to which the instance belongs.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.VPC
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Reference to a VPC in vpc to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDRef *v1.Reference `json:"vpcIdRef,omitempty" tf:"-"`

	// Selector for a VPC in vpc to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDSelector *v1.Selector `json:"vpcIdSelector,omitempty" tf:"-"`

	// The ID of the vSwitch that is associated with the specified VPC.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.Vswitch
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	// +kubebuilder:validation:Optional
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// Reference to a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDRef *v1.Reference `json:"vswitchIdRef,omitempty" tf:"-"`

	// Selector for a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDSelector *v1.Selector `json:"vswitchIdSelector,omitempty" tf:"-"`
}

type ReadOnlyInstanceWeightInitParameters struct {

	// The Id of the instance and its read-only instances that can run database.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/rds/v1alpha1.ReadonlyInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a ReadonlyInstance in rds to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a ReadonlyInstance in rds to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Weight of instances that can run the database and their read-only instances. Read weights increase in increments of 100, and the maximum read weight is 10000.
	Weight *string `json:"weight,omitempty" tf:"weight,omitempty"`
}

type ReadOnlyInstanceWeightObservation struct {

	// The Id of the instance and its read-only instances that can run database.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Weight of instances that can run the database and their read-only instances. Read weights increase in increments of 100, and the maximum read weight is 10000.
	Weight *string `json:"weight,omitempty" tf:"weight,omitempty"`
}

type ReadOnlyInstanceWeightParameters struct {

	// The Id of the instance and its read-only instances that can run database.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/rds/v1alpha1.ReadonlyInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a ReadonlyInstance in rds to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a ReadonlyInstance in rds to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Weight of instances that can run the database and their read-only instances. Read weights increase in increments of 100, and the maximum read weight is 10000.
	// +kubebuilder:validation:Optional
	Weight *string `json:"weight" tf:"weight,omitempty"`
}

// DBProxySpec defines the desired state of DBProxy
type DBProxySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DBProxyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DBProxyInitParameters `json:"initProvider,omitempty"`
}

// DBProxyStatus defines the observed state of DBProxy.
type DBProxyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DBProxyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DBProxy is the Schema for the DBProxys API. Provides an RDS instance read write splitting connection resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type DBProxy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dbProxyInstanceNum) || (has(self.initProvider) && has(self.initProvider.dbProxyInstanceNum))",message="spec.forProvider.dbProxyInstanceNum is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.instanceNetworkType) || (has(self.initProvider) && has(self.initProvider.instanceNetworkType))",message="spec.forProvider.instanceNetworkType is a required parameter"
	Spec   DBProxySpec   `json:"spec"`
	Status DBProxyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DBProxyList contains a list of DBProxys
type DBProxyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DBProxy `json:"items"`
}

// Repository type metadata.
var (
	DBProxy_Kind             = "DBProxy"
	DBProxy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DBProxy_Kind}.String()
	DBProxy_KindAPIVersion   = DBProxy_Kind + "." + CRDGroupVersion.String()
	DBProxy_GroupVersionKind = CRDGroupVersion.WithKind(DBProxy_Kind)
)

func init() {
	SchemeBuilder.Register(&DBProxy{}, &DBProxyList{})
}
