// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Account) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Backup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BackupPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Connection) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Database) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DBInstanceEndpoint) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DBInstanceEndpointAddress) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DBNode) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DBProxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DBProxyPublic) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Instance) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *InstanceCrossBackupPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ParameterGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ReadonlyInstance) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ReadWriteSplittingConnection) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServiceLinkedRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WhitelistTemplate) Hub() {}
