// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BabelfishConfigInitParameters struct {

	// specifies whether to enable the Babelfish for the instance. If you set this parameter to true, you enable Babelfish for the instance. If you leave this parameter empty, you disable Babelfish for the instance.
	BabelfishEnabled *string `json:"babelfishEnabled,omitempty" tf:"babelfish_enabled,omitempty"`

	// The password of the administrator account. The password must contain at least three of the following character types: uppercase letters, lowercase letters, digits, and special characters. It must be 8 to 32 characters in length. The password can contain any of the following characters:! @ # $ % ^ & * () _ + - =
	MasterUserPassword *string `json:"masterUserPassword,omitempty" tf:"master_user_password,omitempty"`

	// The name of the administrator account. The name can contain lowercase letters, digits, and underscores (_). It must start with a letter and end with a letter or digit. It can be up to 63 characters in length and cannot start with pg.
	MasterUsername *string `json:"masterUsername,omitempty" tf:"master_username,omitempty"`

	// The migration mode of the instance. Valid values: single-db and multi-db.
	MigrationMode *string `json:"migrationMode,omitempty" tf:"migration_mode,omitempty"`
}

type BabelfishConfigObservation struct {

	// specifies whether to enable the Babelfish for the instance. If you set this parameter to true, you enable Babelfish for the instance. If you leave this parameter empty, you disable Babelfish for the instance.
	BabelfishEnabled *string `json:"babelfishEnabled,omitempty" tf:"babelfish_enabled,omitempty"`

	// The password of the administrator account. The password must contain at least three of the following character types: uppercase letters, lowercase letters, digits, and special characters. It must be 8 to 32 characters in length. The password can contain any of the following characters:! @ # $ % ^ & * () _ + - =
	MasterUserPassword *string `json:"masterUserPassword,omitempty" tf:"master_user_password,omitempty"`

	// The name of the administrator account. The name can contain lowercase letters, digits, and underscores (_). It must start with a letter and end with a letter or digit. It can be up to 63 characters in length and cannot start with pg.
	MasterUsername *string `json:"masterUsername,omitempty" tf:"master_username,omitempty"`

	// The migration mode of the instance. Valid values: single-db and multi-db.
	MigrationMode *string `json:"migrationMode,omitempty" tf:"migration_mode,omitempty"`
}

type BabelfishConfigParameters struct {

	// specifies whether to enable the Babelfish for the instance. If you set this parameter to true, you enable Babelfish for the instance. If you leave this parameter empty, you disable Babelfish for the instance.
	// +kubebuilder:validation:Optional
	BabelfishEnabled *string `json:"babelfishEnabled" tf:"babelfish_enabled,omitempty"`

	// The password of the administrator account. The password must contain at least three of the following character types: uppercase letters, lowercase letters, digits, and special characters. It must be 8 to 32 characters in length. The password can contain any of the following characters:! @ # $ % ^ & * () _ + - =
	// +kubebuilder:validation:Optional
	MasterUserPassword *string `json:"masterUserPassword" tf:"master_user_password,omitempty"`

	// The name of the administrator account. The name can contain lowercase letters, digits, and underscores (_). It must start with a letter and end with a letter or digit. It can be up to 63 characters in length and cannot start with pg.
	// +kubebuilder:validation:Optional
	MasterUsername *string `json:"masterUsername" tf:"master_username,omitempty"`

	// The migration mode of the instance. Valid values: single-db and multi-db.
	// +kubebuilder:validation:Optional
	MigrationMode *string `json:"migrationMode" tf:"migration_mode,omitempty"`
}

type InstanceInitParameters struct {

	// The method that is used to verify the identities of clients. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. In addition, this parameter is available only when the public key of the CA that issues client certificates is enabled. Valid values:
	ACL *string `json:"acl,omitempty" tf:"acl,omitempty"`

	// Whether to renewal a DB instance automatically or not. It is valid when instance_charge_type is PrePaid. Default to false.
	AutoRenew *bool `json:"autoRenew,omitempty" tf:"auto_renew,omitempty"`

	// Auto-renewal period of an instance, in the unit of the month. It is valid when instance_charge_type is PrePaid. Valid value:[1~12], Default to 1.
	AutoRenewPeriod *float64 `json:"autoRenewPeriod,omitempty" tf:"auto_renew_period,omitempty"`

	// The upgrade method to use. Valid values:
	AutoUpgradeMinorVersion *string `json:"autoUpgradeMinorVersion,omitempty" tf:"auto_upgrade_minor_version,omitempty"`

	// (ForceNew, Optional, Available since v1.176.0) The configuration of an ApsaraDB RDS for PostgreSQL instance for which Babelfish is enabled. See babelfish_config below.
	BabelfishConfig []BabelfishConfigInitParameters `json:"babelfishConfig,omitempty" tf:"babelfish_config,omitempty"`

	// The TDS port of the instance for which Babelfish is enabled.
	BabelfishPort *string `json:"babelfishPort,omitempty" tf:"babelfish_port,omitempty"`

	// Specifies whether to enable the I/O burst feature of general
	// ESSDs. Valid values:
	BurstingEnabled *bool `json:"burstingEnabled,omitempty" tf:"bursting_enabled,omitempty"`

	// The type of the server certificate. This parameter is supported only when the instance runs PostgreSQL or MySQL with standard or enhanced SSDs. If you set the SSLEnabled parameter to 1, the default value of this parameter is aliyun. NOTE: From version 1.231.0, ca_type start  support MySQL engine. Value range:
	CAType *string `json:"caType,omitempty" tf:"ca_type,omitempty"`

	// The RDS edition of the instance. If you want to create a serverless instance, you must use this value. Valid values:
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// The public key of the CA that issues client certificates. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. If you set the ClientCAEbabled parameter to 1, you must also specify this parameter.
	ClientCACertSecretRef *v1.SecretKeySelector `json:"clientCaCertSecretRef,omitempty" tf:"-"`

	// Specifies whether to enable the public key of the CA that issues client certificates. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. Valid values:
	ClientCAEnabled *float64 `json:"clientCaEnabled,omitempty" tf:"client_ca_enabled,omitempty"`

	// The CRL that contains revoked client certificates. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. If you set the ClientCrlEnabled parameter to 1, you must also specify this parameter.
	ClientCertRevocationList *string `json:"clientCertRevocationList,omitempty" tf:"client_cert_revocation_list,omitempty"`

	// Specifies whether to enable a certificate revocation list (CRL) that contains revoked client certificates. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. In addition, this parameter is available only when the public key of the CA that issues client certificates is enabled. Valid values:
	ClientCrlEnabled *float64 `json:"clientCrlEnabled,omitempty" tf:"client_crl_enabled,omitempty"`

	// High performance cloud disk data archiving function switch.Example value:
	ColdDataEnabled *bool `json:"coldDataEnabled,omitempty" tf:"cold_data_enabled,omitempty"`

	// The character set collation of the instance. By default, the system does not modify the character set collation of the instance. Valid values:
	Collation *string `json:"collation,omitempty" tf:"collation,omitempty"`

	// Specify the point in time at which the system collects the statistics of the instance.
	CollectStatMode *string `json:"collectStatMode,omitempty" tf:"collect_stat_mode,omitempty"`

	// The private connection string prefix. If you want to update public connection string prefix, please use resource alicloud_db_connection connection_prefix.
	// -> NOTE: The prefix must be 8 to 64 characters in length and can contain letters, digits, and hyphens (-). It cannot contain Chinese characters and special characters ~!#%^&*=+|{};:'",<>/?
	ConnectionStringPrefix *string `json:"connectionStringPrefix,omitempty" tf:"connection_string_prefix,omitempty"`

	// The attribute of the IP address whitelist. By default, this parameter is empty.
	DBInstanceIPArrayAttribute *string `json:"dbInstanceIpArrayAttribute,omitempty" tf:"db_instance_ip_array_attribute,omitempty"`

	// The name of the IP address whitelist. Default value: Default.
	DBInstanceIPArrayName *string `json:"dbInstanceIpArrayName,omitempty" tf:"db_instance_ip_array_name,omitempty"`

	// The storage type of the instance. Serverless instance, only cloud_essd can be selected. Valid values:
	DBInstanceStorageType *string `json:"dbInstanceStorageType,omitempty" tf:"db_instance_storage_type,omitempty"`

	// Specifies whether table names on the instance are case-sensitive. Valid values: true, false.
	DBIsIgnoreCase *bool `json:"dbIsIgnoreCase,omitempty" tf:"db_is_ignore_case,omitempty"`

	// Parameter template ID. Only MySQL and PostgreSQL support this parameter. If this parameter is not specified, the default parameter template is used. You can also customize a parameter template and use it here.
	DBParamGroupID *string `json:"dbParamGroupId,omitempty" tf:"db_param_group_id,omitempty"`

	// The time zone of the instance. This parameter takes effect only when you set the Engine parameter to MySQL or PostgreSQL.
	DBTimeZone *string `json:"dbTimeZone,omitempty" tf:"db_time_zone,omitempty"`

	// The switch of delete protection. Valid values:
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// The instance configuration type. Valid values: ["Up", "Down", "TempUpgrade", "Serverless"]
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// The method to update the engine version and change.  Default value: Immediate. Valid values:
	EffectiveTime *string `json:"effectiveTime,omitempty" tf:"effective_time,omitempty"`

	// The key id of the KMS. Used for encrypting a disk if not null. Only for PostgreSQL, MySQL and SQLServer.
	// When the instance is PostgreSQL, this parameter can be used to enable, modify, and disable cloud disk encryption.Value range:
	EncryptionKey *string `json:"encryptionKey,omitempty" tf:"encryption_key,omitempty"`

	// Database type. Value options: MySQL, SQLServer, PostgreSQL, MariaDB.
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// Database version. Value options can refer to the latest docs CreateDBInstance EngineVersion.
	EngineVersion *string `json:"engineVersion,omitempty" tf:"engine_version,omitempty"`

	// Specifies whether to enable forcible switching. Valid values:
	Force *string `json:"force,omitempty" tf:"force,omitempty"`

	// Specifies whether to enable the forceful SSL encryption feature. This parameter is supported only for ApsaraDB RDS for SQL Server instances.Valid values:
	ForceEncryption *float64 `json:"forceEncryption,omitempty" tf:"force_encryption,omitempty"`

	// Set it to true to make some parameter efficient when modifying them. Default to false.
	ForceRestart *bool `json:"forceRestart,omitempty" tf:"force_restart,omitempty"`

	// The read-only instances to which you want to synchronize the IP address whitelist.
	FreshWhiteListReadins *string `json:"freshWhiteListReadins,omitempty" tf:"fresh_white_list_readins,omitempty"`

	// The primary/secondary switchover mode of the instance. Default value: Auto. Valid values:
	HaConfig *string `json:"haConfig,omitempty" tf:"ha_config,omitempty"`

	// Valid values are Prepaid, Postpaid, Serverless, Default to Postpaid. Currently, the resource only supports PostPaid to PrePaid. For more information, see Overview.
	InstanceChargeType *string `json:"instanceChargeType,omitempty" tf:"instance_charge_type,omitempty"`

	// The name of DB instance. It a string of 2 to 256 characters.
	InstanceName *string `json:"instanceName,omitempty" tf:"instance_name,omitempty"`

	// User-defined DB instance storage space. Value range:
	InstanceStorage *float64 `json:"instanceStorage,omitempty" tf:"instance_storage,omitempty"`

	// DB Instance type. For details, see Instance type table.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// Maintainable time period format of the instance: HH:MMZ-HH:MMZ (UTC time)
	MaintainTime *string `json:"maintainTime,omitempty" tf:"maintain_time,omitempty"`

	// The time after when you want to enable automatic primary/secondary switchover. At most, you can set this parameter to 23:59:59 seven days later. Specify the time in the ISO 8601 standard in the yyyy-MM-ddTHH:mm:ssZ format. The time must be in UTC.
	ManualHaTime *string `json:"manualHaTime,omitempty" tf:"manual_ha_time,omitempty"`

	// The method that is used to modify the IP address whitelist. Default value: Cover. Valid values:
	ModifyMode *string `json:"modifyMode,omitempty" tf:"modify_mode,omitempty"`

	// The monitoring frequency in seconds. Valid values are 5, 10, 60, 300. Defaults to 300.
	MonitoringPeriod *float64 `json:"monitoringPeriod,omitempty" tf:"monitoring_period,omitempty"`

	// The globally unique identifier (GUID) of the secondary instance. You can call the DescribeDBInstanceHAConfig operation to query the GUID of the secondary instance.
	NodeID *string `json:"nodeId,omitempty" tf:"node_id,omitempty"`

	// Write optimization function switch. supported engine type: MySQL. Valid values:
	OptimizedWrites *string `json:"optimizedWrites,omitempty" tf:"optimized_writes,omitempty"`

	// Set of parameters needs to be set after DB instance was launched. Available parameters can refer to the latest docs View database parameter templates . See parameters below.
	Parameters []ParametersInitParameters `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// The duration that you will buy DB instance (in month). It is valid when instance_charge_type is PrePaid. Valid values: [1~9], 12, 24, 36.
	// -> NOTE: The attribute period is only used to create Subscription instance or modify the PayAsYouGo instance to Subscription.
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// Modify the PgBouncer feature of the RDS PostgreSQL instance. Valid values:
	PgBouncerEnabled *bool `json:"pgBouncerEnabled,omitempty" tf:"pg_bouncer_enabled,omitempty"`

	// The configuration of AD domain . See pg_hba_conf below.
	PgHbaConf []PgHbaConfInitParameters `json:"pgHbaConf,omitempty" tf:"pg_hba_conf,omitempty"`

	// The private port of the database service. If you want to update public port, please use resource alicloud_db_connection port.
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// The private IP address of the instance. The private IP address must be within the Classless Inter-Domain Routing (CIDR) block of the vSwitch that is specified by the VSwitchId parameter.
	PrivateIPAddress *string `json:"privateIpAddress,omitempty" tf:"private_ip_address,omitempty"`

	// Enable the Simple Recovery Model for an RDS SQL Server Instance.The Simple Recovery Model feature is only supported by the Basic Series of RDS SQL Server instances. Once this feature is enabled, it cannot be disabled.Valid values:
	RecoveryModel *string `json:"recoveryModel,omitempty" tf:"recovery_model,omitempty"`

	// The policy based on which ApsaraDB RDS retains archived backup files after the instance is released. Valid values:
	ReleasedKeepPolicy *string `json:"releasedKeepPolicy,omitempty" tf:"released_keep_policy,omitempty"`

	// The method that is used to verify the replication permission. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. In addition, this parameter is available only when the public key of the CA that issues client certificates is enabled. Valid values:
	ReplicationACL *string `json:"replicationAcl,omitempty" tf:"replication_acl,omitempty"`

	// The ID of resource group which the DB instance belongs.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The Alibaba Cloud Resource Name (ARN) of the RAM role.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/ram/v1alpha1.Role
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.RoleArnExtractor()
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`

	// Reference to a Role in ram to populate roleArn.
	// +kubebuilder:validation:Optional
	RoleArnRef *v1.Reference `json:"roleArnRef,omitempty" tf:"-"`

	// Selector for a Role in ram to populate roleArn.
	// +kubebuilder:validation:Optional
	RoleArnSelector *v1.Selector `json:"roleArnSelector,omitempty" tf:"-"`

	// The sql collector keep time of the instance. Valid values are 30, 180, 365, 1095, 1825, Default to 30.
	// -> NOTE: This parameter takes effect when sql_collector_status is set to Enabled and does not take effect when sql_collector_status is set to Disabled.
	SQLCollectorConfigValue *float64 `json:"sqlCollectorConfigValue,omitempty" tf:"sql_collector_config_value,omitempty"`

	// The sql collector status of the instance. Valid values are Enabled, Disabled, Default to Disabled.
	SQLCollectorStatus *string `json:"sqlCollectorStatus,omitempty" tf:"sql_collector_status,omitempty"`

	// Actions performed on SSL functions. Valid values:
	// Open: turn on SSL encryption;
	// Close: turn off SSL encryption;
	// Update: update SSL certificate.
	// See more engine and engineVersion limitation.
	SSLAction *string `json:"sslAction,omitempty" tf:"ssl_action,omitempty"`

	// The custom certificate.
	SSLCertificateSecretRef *v1.SecretKeySelector `json:"sslCertificateSecretRef,omitempty" tf:"-"`

	// The internal or public endpoint for which the server certificate needs to be created or updated.
	SSLConnectionString *string `json:"sslConnectionString,omitempty" tf:"ssl_connection_string,omitempty"`

	// The password of the certificate.
	SSLPasswordSecretRef *v1.SecretKeySelector `json:"sslPasswordSecretRef,omitempty" tf:"-"`

	// References to SecurityGroup in ecs to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIDRefs []v1.Reference `json:"securityGroupIdRefs,omitempty" tf:"-"`

	// Selector for a list of SecurityGroup in ecs to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIDSelector *v1.Selector `json:"securityGroupIdSelector,omitempty" tf:"-"`

	// , Available since v1.69.0) The list IDs to join ECS Security Group. At most supports three security groups.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/ecs/v1alpha1.SecurityGroup
	// +crossplane:generate:reference:refFieldName=SecurityGroupIDRefs
	// +crossplane:generate:reference:selectorFieldName=SecurityGroupIDSelector
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// Valid values are normal, safety, Default to normal. support safety switch to high security access mode.
	SecurityIPMode *string `json:"securityIpMode,omitempty" tf:"security_ip_mode,omitempty"`

	// The type of IP address in the IP address whitelist.
	SecurityIPType *string `json:"securityIpType,omitempty" tf:"security_ip_type,omitempty"`

	// List of IP addresses allowed to access all databases of an instance. The list contains up to 1,000 IP addresses, separated by commas. Supported formats include 0.0.0.0/0, 10.23.12.24 (IP), and 10.23.12.24/24 (Classless Inter-Domain Routing (CIDR) mode. /24 represents the length of the prefix in an IP address. The range of the prefix length is [1,32]).
	// +listType=set
	SecurityIps []*string `json:"securityIps,omitempty" tf:"security_ips,omitempty"`

	// The content of the server certificate. This parameter is supported only when the instance runs PostgreSQL or MySQL with standard or enhanced SSDs. If you set the CAType parameter to custom, you must also specify this parameter. NOTE: From version 1.231.0, server_cert start  support MySQL engine.
	ServerCertSecretRef *v1.SecretKeySelector `json:"serverCertSecretRef,omitempty" tf:"-"`

	// The private key of the server certificate. This parameter is supported only when the instance runs PostgreSQL or MySQL with standard or enhanced SSDs. If you set the CAType parameter to custom, you must also specify this parameter. NOTE: From version 1.231.0, server_key start support MySQL engine.
	ServerKey *string `json:"serverKey,omitempty" tf:"server_key,omitempty"`

	// The settings of the serverless instance. This parameter is required when you create a serverless instance. This parameter takes effect only when you create an ApsaraDB RDS for Serverless instance. See serverless_config below.
	ServerlessConfig []ServerlessConfigInitParameters `json:"serverlessConfig,omitempty" tf:"serverless_config,omitempty"`

	// Automatic storage space expansion switch. Valid values:
	StorageAutoScale *string `json:"storageAutoScale,omitempty" tf:"storage_auto_scale,omitempty"`

	// The threshold in percentage based on which an automatic storage expansion is triggered. If the available storage reaches the threshold, ApsaraDB RDS increases the storage capacity of the instance.
	// Valid values: [10, 20, 30, 40, 50].
	StorageThreshold *float64 `json:"storageThreshold,omitempty" tf:"storage_threshold,omitempty"`

	// The upper limit of the total storage space for automatic expansion of the storage space, that is, automatic expansion will not cause the total storage space of the instance to exceed this value. Unit: GB. The value must be ≥0.
	StorageUpperBound *float64 `json:"storageUpperBound,omitempty" tf:"storage_upper_bound,omitempty"`

	// The specific point in time when you want to perform the update. Specify the time in the ISO 8601 standard in the yyyy-MM-ddTHH:mm:ssZ format. It is valid only when target_minor_version is changed. The time must be in UTC.
	SwitchTime *string `json:"switchTime,omitempty" tf:"switch_time,omitempty"`

	// The availability check method of the instance. Valid values:
	TCPConnectionType *string `json:"tcpConnectionType,omitempty" tf:"tcp_connection_type,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The minor engine version to which you want to update the instance. If you do not specify this parameter, the instance is updated to the latest minor engine version. You must specify the minor engine version in one of the following formats:
	TargetMinorVersion *string `json:"targetMinorVersion,omitempty" tf:"target_minor_version,omitempty"`

	// The file that contains the certificate..
	TdeCertificateSecretRef *v1.SecretKeySelector `json:"tdeCertificateSecretRef,omitempty" tf:"-"`

	// The name of the database for which you want to enable TDE. You can specify up to 50 database names in a single request. If you specify multiple database names, separate the database names with commas (,).
	TdeDBName *string `json:"tdeDbName,omitempty" tf:"tde_db_name,omitempty"`

	// The ID of the custom key.
	TdeEncryptionKey *string `json:"tdeEncryptionKey,omitempty" tf:"tde_encryption_key,omitempty"`

	// The password of the certificate.
	TdePasswordSecretRef *v1.SecretKeySelector `json:"tdePasswordSecretRef,omitempty" tf:"-"`

	// The file that contains the private key of the certificate..
	TdePrivateKeySecretRef *v1.SecretKeySelector `json:"tdePrivateKeySecretRef,omitempty" tf:"-"`

	// The TDE(Transparent Data Encryption) status. After TDE is turned on, it cannot be turned off. See more engine and engineVersion limitation.
	TdeStatus *string `json:"tdeStatus,omitempty" tf:"tde_status,omitempty"`

	// Whitelist Template ID List.
	TemplateIDList []*float64 `json:"templateIdList,omitempty" tf:"template_id_list,omitempty"`

	// The time zone of the instance. By default, the system does not modify the time zone.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`

	// (Deprecated from v1.198.0)  Whether to upgrade a minor version of the kernel. Valid values:
	UpgradeDBInstanceKernelVersion *bool `json:"upgradeDbInstanceKernelVersion,omitempty" tf:"upgrade_db_instance_kernel_version,omitempty"`

	// The method to update the minor engine version. Default value: Immediate. It is valid only when target_minor_version is changed. Valid values:
	UpgradeTime *string `json:"upgradeTime,omitempty" tf:"upgrade_time,omitempty"`

	// The VPC ID of the instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.VPC
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Reference to a VPC in vpc to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDRef *v1.Reference `json:"vpcIdRef,omitempty" tf:"-"`

	// Selector for a VPC in vpc to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDSelector *v1.Selector `json:"vpcIdSelector,omitempty" tf:"-"`

	// (ForceNew, Optional) The virtual switch ID to launch DB instances in one VPC. If there are multiple vswitches, separate them with commas.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.Vswitch
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// Reference to a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDRef *v1.Reference `json:"vswitchIdRef,omitempty" tf:"-"`

	// Selector for a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDSelector *v1.Selector `json:"vswitchIdSelector,omitempty" tf:"-"`

	// The network type of the IP address whitelist. Default value: MIX. Valid values:
	WhitelistNetworkType *string `json:"whitelistNetworkType,omitempty" tf:"whitelist_network_type,omitempty"`

	// (ForceNew, Optional) The Zone to launch the DB instance. From version 1.8.1, it supports multiple zone.
	// If it is a multi-zone and vswitch_id is specified, the vswitch must in the one of them.
	// The multiple zone ID can be retrieved by setting multi to "true" in the data source alicloud_zones.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// The region ID of the secondary instance if you create a secondary instance. If you set this parameter to the same value as the ZoneId parameter, the instance is deployed in a single zone. Otherwise, the instance is deployed in multiple zones.
	ZoneIDSlaveA *string `json:"zoneIdSlaveA,omitempty" tf:"zone_id_slave_a,omitempty"`

	// RDS MySQL Cluster series instances support creating 1 to 2 secondary nodes at the same time when establishing a new instance. If you have this requirement, you can use this parameter to specify the availability zone for the second secondary node.
	ZoneIDSlaveB *string `json:"zoneIdSlaveB,omitempty" tf:"zone_id_slave_b,omitempty"`
}

type InstanceObservation struct {

	// The method that is used to verify the identities of clients. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. In addition, this parameter is available only when the public key of the CA that issues client certificates is enabled. Valid values:
	ACL *string `json:"acl,omitempty" tf:"acl,omitempty"`

	// Whether to renewal a DB instance automatically or not. It is valid when instance_charge_type is PrePaid. Default to false.
	AutoRenew *bool `json:"autoRenew,omitempty" tf:"auto_renew,omitempty"`

	// Auto-renewal period of an instance, in the unit of the month. It is valid when instance_charge_type is PrePaid. Valid value:[1~12], Default to 1.
	AutoRenewPeriod *float64 `json:"autoRenewPeriod,omitempty" tf:"auto_renew_period,omitempty"`

	// The upgrade method to use. Valid values:
	AutoUpgradeMinorVersion *string `json:"autoUpgradeMinorVersion,omitempty" tf:"auto_upgrade_minor_version,omitempty"`

	// (ForceNew, Optional, Available since v1.176.0) The configuration of an ApsaraDB RDS for PostgreSQL instance for which Babelfish is enabled. See babelfish_config below.
	BabelfishConfig []BabelfishConfigObservation `json:"babelfishConfig,omitempty" tf:"babelfish_config,omitempty"`

	// The TDS port of the instance for which Babelfish is enabled.
	BabelfishPort *string `json:"babelfishPort,omitempty" tf:"babelfish_port,omitempty"`

	// Specifies whether to enable the I/O burst feature of general
	// ESSDs. Valid values:
	BurstingEnabled *bool `json:"burstingEnabled,omitempty" tf:"bursting_enabled,omitempty"`

	// The type of the server certificate. This parameter is supported only when the instance runs PostgreSQL or MySQL with standard or enhanced SSDs. If you set the SSLEnabled parameter to 1, the default value of this parameter is aliyun. NOTE: From version 1.231.0, ca_type start  support MySQL engine. Value range:
	CAType *string `json:"caType,omitempty" tf:"ca_type,omitempty"`

	// The RDS edition of the instance. If you want to create a serverless instance, you must use this value. Valid values:
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// Specifies whether to enable the public key of the CA that issues client certificates. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. Valid values:
	ClientCAEnabled *float64 `json:"clientCaEnabled,omitempty" tf:"client_ca_enabled,omitempty"`

	// The CRL that contains revoked client certificates. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. If you set the ClientCrlEnabled parameter to 1, you must also specify this parameter.
	ClientCertRevocationList *string `json:"clientCertRevocationList,omitempty" tf:"client_cert_revocation_list,omitempty"`

	// Specifies whether to enable a certificate revocation list (CRL) that contains revoked client certificates. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. In addition, this parameter is available only when the public key of the CA that issues client certificates is enabled. Valid values:
	ClientCrlEnabled *float64 `json:"clientCrlEnabled,omitempty" tf:"client_crl_enabled,omitempty"`

	// High performance cloud disk data archiving function switch.Example value:
	ColdDataEnabled *bool `json:"coldDataEnabled,omitempty" tf:"cold_data_enabled,omitempty"`

	// The character set collation of the instance. By default, the system does not modify the character set collation of the instance. Valid values:
	Collation *string `json:"collation,omitempty" tf:"collation,omitempty"`

	// Specify the point in time at which the system collects the statistics of the instance.
	CollectStatMode *string `json:"collectStatMode,omitempty" tf:"collect_stat_mode,omitempty"`

	// RDS database connection string.
	ConnectionString *string `json:"connectionString,omitempty" tf:"connection_string,omitempty"`

	// The private connection string prefix. If you want to update public connection string prefix, please use resource alicloud_db_connection connection_prefix.
	// -> NOTE: The prefix must be 8 to 64 characters in length and can contain letters, digits, and hyphens (-). It cannot contain Chinese characters and special characters ~!#%^&*=+|{};:'",<>/?
	ConnectionStringPrefix *string `json:"connectionStringPrefix,omitempty" tf:"connection_string_prefix,omitempty"`

	// (Available since v1.204.1) The creation time of db instance.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The attribute of the IP address whitelist. By default, this parameter is empty.
	DBInstanceIPArrayAttribute *string `json:"dbInstanceIpArrayAttribute,omitempty" tf:"db_instance_ip_array_attribute,omitempty"`

	// The name of the IP address whitelist. Default value: Default.
	DBInstanceIPArrayName *string `json:"dbInstanceIpArrayName,omitempty" tf:"db_instance_ip_array_name,omitempty"`

	// The storage type of the instance. Serverless instance, only cloud_essd can be selected. Valid values:
	DBInstanceStorageType *string `json:"dbInstanceStorageType,omitempty" tf:"db_instance_storage_type,omitempty"`

	// (Available since v1.197.0) The type of db instance.
	DBInstanceType *string `json:"dbInstanceType,omitempty" tf:"db_instance_type,omitempty"`

	// Specifies whether table names on the instance are case-sensitive. Valid values: true, false.
	DBIsIgnoreCase *bool `json:"dbIsIgnoreCase,omitempty" tf:"db_is_ignore_case,omitempty"`

	// Parameter template ID. Only MySQL and PostgreSQL support this parameter. If this parameter is not specified, the default parameter template is used. You can also customize a parameter template and use it here.
	DBParamGroupID *string `json:"dbParamGroupId,omitempty" tf:"db_param_group_id,omitempty"`

	// The time zone of the instance. This parameter takes effect only when you set the Engine parameter to MySQL or PostgreSQL.
	DBTimeZone *string `json:"dbTimeZone,omitempty" tf:"db_time_zone,omitempty"`

	// The switch of delete protection. Valid values:
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// The instance configuration type. Valid values: ["Up", "Down", "TempUpgrade", "Serverless"]
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// The method to update the engine version and change.  Default value: Immediate. Valid values:
	EffectiveTime *string `json:"effectiveTime,omitempty" tf:"effective_time,omitempty"`

	// The key id of the KMS. Used for encrypting a disk if not null. Only for PostgreSQL, MySQL and SQLServer.
	// When the instance is PostgreSQL, this parameter can be used to enable, modify, and disable cloud disk encryption.Value range:
	EncryptionKey *string `json:"encryptionKey,omitempty" tf:"encryption_key,omitempty"`

	// Database type. Value options: MySQL, SQLServer, PostgreSQL, MariaDB.
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// Database version. Value options can refer to the latest docs CreateDBInstance EngineVersion.
	EngineVersion *string `json:"engineVersion,omitempty" tf:"engine_version,omitempty"`

	// Specifies whether to enable forcible switching. Valid values:
	Force *string `json:"force,omitempty" tf:"force,omitempty"`

	// Specifies whether to enable the forceful SSL encryption feature. This parameter is supported only for ApsaraDB RDS for SQL Server instances.Valid values:
	ForceEncryption *float64 `json:"forceEncryption,omitempty" tf:"force_encryption,omitempty"`

	// Set it to true to make some parameter efficient when modifying them. Default to false.
	ForceRestart *bool `json:"forceRestart,omitempty" tf:"force_restart,omitempty"`

	// The read-only instances to which you want to synchronize the IP address whitelist.
	FreshWhiteListReadins *string `json:"freshWhiteListReadins,omitempty" tf:"fresh_white_list_readins,omitempty"`

	// The primary/secondary switchover mode of the instance. Default value: Auto. Valid values:
	HaConfig *string `json:"haConfig,omitempty" tf:"ha_config,omitempty"`

	// The RDS instance ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Valid values are Prepaid, Postpaid, Serverless, Default to Postpaid. Currently, the resource only supports PostPaid to PrePaid. For more information, see Overview.
	InstanceChargeType *string `json:"instanceChargeType,omitempty" tf:"instance_charge_type,omitempty"`

	// The name of DB instance. It a string of 2 to 256 characters.
	InstanceName *string `json:"instanceName,omitempty" tf:"instance_name,omitempty"`

	// User-defined DB instance storage space. Value range:
	InstanceStorage *float64 `json:"instanceStorage,omitempty" tf:"instance_storage,omitempty"`

	// DB Instance type. For details, see Instance type table.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// Maintainable time period format of the instance: HH:MMZ-HH:MMZ (UTC time)
	MaintainTime *string `json:"maintainTime,omitempty" tf:"maintain_time,omitempty"`

	// The time after when you want to enable automatic primary/secondary switchover. At most, you can set this parameter to 23:59:59 seven days later. Specify the time in the ISO 8601 standard in the yyyy-MM-ddTHH:mm:ssZ format. The time must be in UTC.
	ManualHaTime *string `json:"manualHaTime,omitempty" tf:"manual_ha_time,omitempty"`

	// The method that is used to modify the IP address whitelist. Default value: Cover. Valid values:
	ModifyMode *string `json:"modifyMode,omitempty" tf:"modify_mode,omitempty"`

	// The monitoring frequency in seconds. Valid values are 5, 10, 60, 300. Defaults to 300.
	MonitoringPeriod *float64 `json:"monitoringPeriod,omitempty" tf:"monitoring_period,omitempty"`

	// The globally unique identifier (GUID) of the secondary instance. You can call the DescribeDBInstanceHAConfig operation to query the GUID of the secondary instance.
	NodeID *string `json:"nodeId,omitempty" tf:"node_id,omitempty"`

	// Write optimization function switch. supported engine type: MySQL. Valid values:
	OptimizedWrites *string `json:"optimizedWrites,omitempty" tf:"optimized_writes,omitempty"`

	// Set of parameters needs to be set after DB instance was launched. Available parameters can refer to the latest docs View database parameter templates . See parameters below.
	Parameters []ParametersObservation `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// The duration that you will buy DB instance (in month). It is valid when instance_charge_type is PrePaid. Valid values: [1~9], 12, 24, 36.
	// -> NOTE: The attribute period is only used to create Subscription instance or modify the PayAsYouGo instance to Subscription.
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// Modify the PgBouncer feature of the RDS PostgreSQL instance. Valid values:
	PgBouncerEnabled *bool `json:"pgBouncerEnabled,omitempty" tf:"pg_bouncer_enabled,omitempty"`

	// The configuration of AD domain . See pg_hba_conf below.
	PgHbaConf []PgHbaConfObservation `json:"pgHbaConf,omitempty" tf:"pg_hba_conf,omitempty"`

	// The private port of the database service. If you want to update public port, please use resource alicloud_db_connection port.
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// The private IP address of the instance. The private IP address must be within the Classless Inter-Domain Routing (CIDR) block of the vSwitch that is specified by the VSwitchId parameter.
	PrivateIPAddress *string `json:"privateIpAddress,omitempty" tf:"private_ip_address,omitempty"`

	// Enable the Simple Recovery Model for an RDS SQL Server Instance.The Simple Recovery Model feature is only supported by the Basic Series of RDS SQL Server instances. Once this feature is enabled, it cannot be disabled.Valid values:
	RecoveryModel *string `json:"recoveryModel,omitempty" tf:"recovery_model,omitempty"`

	// The policy based on which ApsaraDB RDS retains archived backup files after the instance is released. Valid values:
	ReleasedKeepPolicy *string `json:"releasedKeepPolicy,omitempty" tf:"released_keep_policy,omitempty"`

	// The method that is used to verify the replication permission. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. In addition, this parameter is available only when the public key of the CA that issues client certificates is enabled. Valid values:
	ReplicationACL *string `json:"replicationAcl,omitempty" tf:"replication_acl,omitempty"`

	// The ID of resource group which the DB instance belongs.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The Alibaba Cloud Resource Name (ARN) of the RAM role.
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`

	// The sql collector keep time of the instance. Valid values are 30, 180, 365, 1095, 1825, Default to 30.
	// -> NOTE: This parameter takes effect when sql_collector_status is set to Enabled and does not take effect when sql_collector_status is set to Disabled.
	SQLCollectorConfigValue *float64 `json:"sqlCollectorConfigValue,omitempty" tf:"sql_collector_config_value,omitempty"`

	// The sql collector status of the instance. Valid values are Enabled, Disabled, Default to Disabled.
	SQLCollectorStatus *string `json:"sqlCollectorStatus,omitempty" tf:"sql_collector_status,omitempty"`

	// Actions performed on SSL functions. Valid values:
	// Open: turn on SSL encryption;
	// Close: turn off SSL encryption;
	// Update: update SSL certificate.
	// See more engine and engineVersion limitation.
	SSLAction *string `json:"sslAction,omitempty" tf:"ssl_action,omitempty"`

	// The internal or public endpoint for which the server certificate needs to be created or updated.
	SSLConnectionString *string `json:"sslConnectionString,omitempty" tf:"ssl_connection_string,omitempty"`

	// Status of the SSL feature. Yes: SSL is turned on; No: SSL is turned off.
	SSLStatus *string `json:"sslStatus,omitempty" tf:"ssl_status,omitempty"`

	// , Available since v1.69.0) The list IDs to join ECS Security Group. At most supports three security groups.
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// Valid values are normal, safety, Default to normal. support safety switch to high security access mode.
	SecurityIPMode *string `json:"securityIpMode,omitempty" tf:"security_ip_mode,omitempty"`

	// The type of IP address in the IP address whitelist.
	SecurityIPType *string `json:"securityIpType,omitempty" tf:"security_ip_type,omitempty"`

	// List of IP addresses allowed to access all databases of an instance. The list contains up to 1,000 IP addresses, separated by commas. Supported formats include 0.0.0.0/0, 10.23.12.24 (IP), and 10.23.12.24/24 (Classless Inter-Domain Routing (CIDR) mode. /24 represents the length of the prefix in an IP address. The range of the prefix length is [1,32]).
	// +listType=set
	SecurityIps []*string `json:"securityIps,omitempty" tf:"security_ips,omitempty"`

	// The private key of the server certificate. This parameter is supported only when the instance runs PostgreSQL or MySQL with standard or enhanced SSDs. If you set the CAType parameter to custom, you must also specify this parameter. NOTE: From version 1.231.0, server_key start support MySQL engine.
	ServerKey *string `json:"serverKey,omitempty" tf:"server_key,omitempty"`

	// The settings of the serverless instance. This parameter is required when you create a serverless instance. This parameter takes effect only when you create an ApsaraDB RDS for Serverless instance. See serverless_config below.
	ServerlessConfig []ServerlessConfigObservation `json:"serverlessConfig,omitempty" tf:"serverless_config,omitempty"`

	// (Available since v1.204.1) The status of db instance.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Automatic storage space expansion switch. Valid values:
	StorageAutoScale *string `json:"storageAutoScale,omitempty" tf:"storage_auto_scale,omitempty"`

	// The threshold in percentage based on which an automatic storage expansion is triggered. If the available storage reaches the threshold, ApsaraDB RDS increases the storage capacity of the instance.
	// Valid values: [10, 20, 30, 40, 50].
	StorageThreshold *float64 `json:"storageThreshold,omitempty" tf:"storage_threshold,omitempty"`

	// The upper limit of the total storage space for automatic expansion of the storage space, that is, automatic expansion will not cause the total storage space of the instance to exceed this value. Unit: GB. The value must be ≥0.
	StorageUpperBound *float64 `json:"storageUpperBound,omitempty" tf:"storage_upper_bound,omitempty"`

	// The specific point in time when you want to perform the update. Specify the time in the ISO 8601 standard in the yyyy-MM-ddTHH:mm:ssZ format. It is valid only when target_minor_version is changed. The time must be in UTC.
	SwitchTime *string `json:"switchTime,omitempty" tf:"switch_time,omitempty"`

	// The availability check method of the instance. Valid values:
	TCPConnectionType *string `json:"tcpConnectionType,omitempty" tf:"tcp_connection_type,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The minor engine version to which you want to update the instance. If you do not specify this parameter, the instance is updated to the latest minor engine version. You must specify the minor engine version in one of the following formats:
	TargetMinorVersion *string `json:"targetMinorVersion,omitempty" tf:"target_minor_version,omitempty"`

	// The name of the database for which you want to enable TDE. You can specify up to 50 database names in a single request. If you specify multiple database names, separate the database names with commas (,).
	TdeDBName *string `json:"tdeDbName,omitempty" tf:"tde_db_name,omitempty"`

	// The ID of the custom key.
	TdeEncryptionKey *string `json:"tdeEncryptionKey,omitempty" tf:"tde_encryption_key,omitempty"`

	// The TDE(Transparent Data Encryption) status. After TDE is turned on, it cannot be turned off. See more engine and engineVersion limitation.
	TdeStatus *string `json:"tdeStatus,omitempty" tf:"tde_status,omitempty"`

	// Whitelist Template ID List.
	TemplateIDList []*float64 `json:"templateIdList,omitempty" tf:"template_id_list,omitempty"`

	// (Computed, Available since v1.254.0) Whitelist Template Details.
	Templates []map[string]*string `json:"templates,omitempty" tf:"templates,omitempty"`

	// The time zone of the instance. By default, the system does not modify the time zone.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`

	// (Deprecated from v1.198.0)  Whether to upgrade a minor version of the kernel. Valid values:
	UpgradeDBInstanceKernelVersion *bool `json:"upgradeDbInstanceKernelVersion,omitempty" tf:"upgrade_db_instance_kernel_version,omitempty"`

	// The method to update the minor engine version. Default value: Immediate. It is valid only when target_minor_version is changed. Valid values:
	UpgradeTime *string `json:"upgradeTime,omitempty" tf:"upgrade_time,omitempty"`

	// The VPC ID of the instance.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// (ForceNew, Optional) The virtual switch ID to launch DB instances in one VPC. If there are multiple vswitches, separate them with commas.
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// The network type of the IP address whitelist. Default value: MIX. Valid values:
	WhitelistNetworkType *string `json:"whitelistNetworkType,omitempty" tf:"whitelist_network_type,omitempty"`

	// (ForceNew, Optional) The Zone to launch the DB instance. From version 1.8.1, it supports multiple zone.
	// If it is a multi-zone and vswitch_id is specified, the vswitch must in the one of them.
	// The multiple zone ID can be retrieved by setting multi to "true" in the data source alicloud_zones.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// The region ID of the secondary instance if you create a secondary instance. If you set this parameter to the same value as the ZoneId parameter, the instance is deployed in a single zone. Otherwise, the instance is deployed in multiple zones.
	ZoneIDSlaveA *string `json:"zoneIdSlaveA,omitempty" tf:"zone_id_slave_a,omitempty"`

	// RDS MySQL Cluster series instances support creating 1 to 2 secondary nodes at the same time when establishing a new instance. If you have this requirement, you can use this parameter to specify the availability zone for the second secondary node.
	ZoneIDSlaveB *string `json:"zoneIdSlaveB,omitempty" tf:"zone_id_slave_b,omitempty"`
}

type InstanceParameters struct {

	// The method that is used to verify the identities of clients. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. In addition, this parameter is available only when the public key of the CA that issues client certificates is enabled. Valid values:
	// +kubebuilder:validation:Optional
	ACL *string `json:"acl,omitempty" tf:"acl,omitempty"`

	// Whether to renewal a DB instance automatically or not. It is valid when instance_charge_type is PrePaid. Default to false.
	// +kubebuilder:validation:Optional
	AutoRenew *bool `json:"autoRenew,omitempty" tf:"auto_renew,omitempty"`

	// Auto-renewal period of an instance, in the unit of the month. It is valid when instance_charge_type is PrePaid. Valid value:[1~12], Default to 1.
	// +kubebuilder:validation:Optional
	AutoRenewPeriod *float64 `json:"autoRenewPeriod,omitempty" tf:"auto_renew_period,omitempty"`

	// The upgrade method to use. Valid values:
	// +kubebuilder:validation:Optional
	AutoUpgradeMinorVersion *string `json:"autoUpgradeMinorVersion,omitempty" tf:"auto_upgrade_minor_version,omitempty"`

	// (ForceNew, Optional, Available since v1.176.0) The configuration of an ApsaraDB RDS for PostgreSQL instance for which Babelfish is enabled. See babelfish_config below.
	// +kubebuilder:validation:Optional
	BabelfishConfig []BabelfishConfigParameters `json:"babelfishConfig,omitempty" tf:"babelfish_config,omitempty"`

	// The TDS port of the instance for which Babelfish is enabled.
	// +kubebuilder:validation:Optional
	BabelfishPort *string `json:"babelfishPort,omitempty" tf:"babelfish_port,omitempty"`

	// Specifies whether to enable the I/O burst feature of general
	// ESSDs. Valid values:
	// +kubebuilder:validation:Optional
	BurstingEnabled *bool `json:"burstingEnabled,omitempty" tf:"bursting_enabled,omitempty"`

	// The type of the server certificate. This parameter is supported only when the instance runs PostgreSQL or MySQL with standard or enhanced SSDs. If you set the SSLEnabled parameter to 1, the default value of this parameter is aliyun. NOTE: From version 1.231.0, ca_type start  support MySQL engine. Value range:
	// +kubebuilder:validation:Optional
	CAType *string `json:"caType,omitempty" tf:"ca_type,omitempty"`

	// The RDS edition of the instance. If you want to create a serverless instance, you must use this value. Valid values:
	// +kubebuilder:validation:Optional
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// The public key of the CA that issues client certificates. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. If you set the ClientCAEbabled parameter to 1, you must also specify this parameter.
	// +kubebuilder:validation:Optional
	ClientCACertSecretRef *v1.SecretKeySelector `json:"clientCaCertSecretRef,omitempty" tf:"-"`

	// Specifies whether to enable the public key of the CA that issues client certificates. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. Valid values:
	// +kubebuilder:validation:Optional
	ClientCAEnabled *float64 `json:"clientCaEnabled,omitempty" tf:"client_ca_enabled,omitempty"`

	// The CRL that contains revoked client certificates. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. If you set the ClientCrlEnabled parameter to 1, you must also specify this parameter.
	// +kubebuilder:validation:Optional
	ClientCertRevocationList *string `json:"clientCertRevocationList,omitempty" tf:"client_cert_revocation_list,omitempty"`

	// Specifies whether to enable a certificate revocation list (CRL) that contains revoked client certificates. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. In addition, this parameter is available only when the public key of the CA that issues client certificates is enabled. Valid values:
	// +kubebuilder:validation:Optional
	ClientCrlEnabled *float64 `json:"clientCrlEnabled,omitempty" tf:"client_crl_enabled,omitempty"`

	// High performance cloud disk data archiving function switch.Example value:
	// +kubebuilder:validation:Optional
	ColdDataEnabled *bool `json:"coldDataEnabled,omitempty" tf:"cold_data_enabled,omitempty"`

	// The character set collation of the instance. By default, the system does not modify the character set collation of the instance. Valid values:
	// +kubebuilder:validation:Optional
	Collation *string `json:"collation,omitempty" tf:"collation,omitempty"`

	// Specify the point in time at which the system collects the statistics of the instance.
	// +kubebuilder:validation:Optional
	CollectStatMode *string `json:"collectStatMode,omitempty" tf:"collect_stat_mode,omitempty"`

	// The private connection string prefix. If you want to update public connection string prefix, please use resource alicloud_db_connection connection_prefix.
	// -> NOTE: The prefix must be 8 to 64 characters in length and can contain letters, digits, and hyphens (-). It cannot contain Chinese characters and special characters ~!#%^&*=+|{};:'",<>/?
	// +kubebuilder:validation:Optional
	ConnectionStringPrefix *string `json:"connectionStringPrefix,omitempty" tf:"connection_string_prefix,omitempty"`

	// The attribute of the IP address whitelist. By default, this parameter is empty.
	// +kubebuilder:validation:Optional
	DBInstanceIPArrayAttribute *string `json:"dbInstanceIpArrayAttribute,omitempty" tf:"db_instance_ip_array_attribute,omitempty"`

	// The name of the IP address whitelist. Default value: Default.
	// +kubebuilder:validation:Optional
	DBInstanceIPArrayName *string `json:"dbInstanceIpArrayName,omitempty" tf:"db_instance_ip_array_name,omitempty"`

	// The storage type of the instance. Serverless instance, only cloud_essd can be selected. Valid values:
	// +kubebuilder:validation:Optional
	DBInstanceStorageType *string `json:"dbInstanceStorageType,omitempty" tf:"db_instance_storage_type,omitempty"`

	// Specifies whether table names on the instance are case-sensitive. Valid values: true, false.
	// +kubebuilder:validation:Optional
	DBIsIgnoreCase *bool `json:"dbIsIgnoreCase,omitempty" tf:"db_is_ignore_case,omitempty"`

	// Parameter template ID. Only MySQL and PostgreSQL support this parameter. If this parameter is not specified, the default parameter template is used. You can also customize a parameter template and use it here.
	// +kubebuilder:validation:Optional
	DBParamGroupID *string `json:"dbParamGroupId,omitempty" tf:"db_param_group_id,omitempty"`

	// The time zone of the instance. This parameter takes effect only when you set the Engine parameter to MySQL or PostgreSQL.
	// +kubebuilder:validation:Optional
	DBTimeZone *string `json:"dbTimeZone,omitempty" tf:"db_time_zone,omitempty"`

	// The switch of delete protection. Valid values:
	// +kubebuilder:validation:Optional
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// The instance configuration type. Valid values: ["Up", "Down", "TempUpgrade", "Serverless"]
	// +kubebuilder:validation:Optional
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// The method to update the engine version and change.  Default value: Immediate. Valid values:
	// +kubebuilder:validation:Optional
	EffectiveTime *string `json:"effectiveTime,omitempty" tf:"effective_time,omitempty"`

	// The key id of the KMS. Used for encrypting a disk if not null. Only for PostgreSQL, MySQL and SQLServer.
	// When the instance is PostgreSQL, this parameter can be used to enable, modify, and disable cloud disk encryption.Value range:
	// +kubebuilder:validation:Optional
	EncryptionKey *string `json:"encryptionKey,omitempty" tf:"encryption_key,omitempty"`

	// Database type. Value options: MySQL, SQLServer, PostgreSQL, MariaDB.
	// +kubebuilder:validation:Optional
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// Database version. Value options can refer to the latest docs CreateDBInstance EngineVersion.
	// +kubebuilder:validation:Optional
	EngineVersion *string `json:"engineVersion,omitempty" tf:"engine_version,omitempty"`

	// Specifies whether to enable forcible switching. Valid values:
	// +kubebuilder:validation:Optional
	Force *string `json:"force,omitempty" tf:"force,omitempty"`

	// Specifies whether to enable the forceful SSL encryption feature. This parameter is supported only for ApsaraDB RDS for SQL Server instances.Valid values:
	// +kubebuilder:validation:Optional
	ForceEncryption *float64 `json:"forceEncryption,omitempty" tf:"force_encryption,omitempty"`

	// Set it to true to make some parameter efficient when modifying them. Default to false.
	// +kubebuilder:validation:Optional
	ForceRestart *bool `json:"forceRestart,omitempty" tf:"force_restart,omitempty"`

	// The read-only instances to which you want to synchronize the IP address whitelist.
	// +kubebuilder:validation:Optional
	FreshWhiteListReadins *string `json:"freshWhiteListReadins,omitempty" tf:"fresh_white_list_readins,omitempty"`

	// The primary/secondary switchover mode of the instance. Default value: Auto. Valid values:
	// +kubebuilder:validation:Optional
	HaConfig *string `json:"haConfig,omitempty" tf:"ha_config,omitempty"`

	// Valid values are Prepaid, Postpaid, Serverless, Default to Postpaid. Currently, the resource only supports PostPaid to PrePaid. For more information, see Overview.
	// +kubebuilder:validation:Optional
	InstanceChargeType *string `json:"instanceChargeType,omitempty" tf:"instance_charge_type,omitempty"`

	// The name of DB instance. It a string of 2 to 256 characters.
	// +kubebuilder:validation:Optional
	InstanceName *string `json:"instanceName,omitempty" tf:"instance_name,omitempty"`

	// User-defined DB instance storage space. Value range:
	// +kubebuilder:validation:Optional
	InstanceStorage *float64 `json:"instanceStorage,omitempty" tf:"instance_storage,omitempty"`

	// DB Instance type. For details, see Instance type table.
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// Maintainable time period format of the instance: HH:MMZ-HH:MMZ (UTC time)
	// +kubebuilder:validation:Optional
	MaintainTime *string `json:"maintainTime,omitempty" tf:"maintain_time,omitempty"`

	// The time after when you want to enable automatic primary/secondary switchover. At most, you can set this parameter to 23:59:59 seven days later. Specify the time in the ISO 8601 standard in the yyyy-MM-ddTHH:mm:ssZ format. The time must be in UTC.
	// +kubebuilder:validation:Optional
	ManualHaTime *string `json:"manualHaTime,omitempty" tf:"manual_ha_time,omitempty"`

	// The method that is used to modify the IP address whitelist. Default value: Cover. Valid values:
	// +kubebuilder:validation:Optional
	ModifyMode *string `json:"modifyMode,omitempty" tf:"modify_mode,omitempty"`

	// The monitoring frequency in seconds. Valid values are 5, 10, 60, 300. Defaults to 300.
	// +kubebuilder:validation:Optional
	MonitoringPeriod *float64 `json:"monitoringPeriod,omitempty" tf:"monitoring_period,omitempty"`

	// The globally unique identifier (GUID) of the secondary instance. You can call the DescribeDBInstanceHAConfig operation to query the GUID of the secondary instance.
	// +kubebuilder:validation:Optional
	NodeID *string `json:"nodeId,omitempty" tf:"node_id,omitempty"`

	// Write optimization function switch. supported engine type: MySQL. Valid values:
	// +kubebuilder:validation:Optional
	OptimizedWrites *string `json:"optimizedWrites,omitempty" tf:"optimized_writes,omitempty"`

	// Set of parameters needs to be set after DB instance was launched. Available parameters can refer to the latest docs View database parameter templates . See parameters below.
	// +kubebuilder:validation:Optional
	Parameters []ParametersParameters `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// The duration that you will buy DB instance (in month). It is valid when instance_charge_type is PrePaid. Valid values: [1~9], 12, 24, 36.
	// -> NOTE: The attribute period is only used to create Subscription instance or modify the PayAsYouGo instance to Subscription.
	// +kubebuilder:validation:Optional
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// Modify the PgBouncer feature of the RDS PostgreSQL instance. Valid values:
	// +kubebuilder:validation:Optional
	PgBouncerEnabled *bool `json:"pgBouncerEnabled,omitempty" tf:"pg_bouncer_enabled,omitempty"`

	// The configuration of AD domain . See pg_hba_conf below.
	// +kubebuilder:validation:Optional
	PgHbaConf []PgHbaConfParameters `json:"pgHbaConf,omitempty" tf:"pg_hba_conf,omitempty"`

	// The private port of the database service. If you want to update public port, please use resource alicloud_db_connection port.
	// +kubebuilder:validation:Optional
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// The private IP address of the instance. The private IP address must be within the Classless Inter-Domain Routing (CIDR) block of the vSwitch that is specified by the VSwitchId parameter.
	// +kubebuilder:validation:Optional
	PrivateIPAddress *string `json:"privateIpAddress,omitempty" tf:"private_ip_address,omitempty"`

	// Enable the Simple Recovery Model for an RDS SQL Server Instance.The Simple Recovery Model feature is only supported by the Basic Series of RDS SQL Server instances. Once this feature is enabled, it cannot be disabled.Valid values:
	// +kubebuilder:validation:Optional
	RecoveryModel *string `json:"recoveryModel,omitempty" tf:"recovery_model,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The policy based on which ApsaraDB RDS retains archived backup files after the instance is released. Valid values:
	// +kubebuilder:validation:Optional
	ReleasedKeepPolicy *string `json:"releasedKeepPolicy,omitempty" tf:"released_keep_policy,omitempty"`

	// The method that is used to verify the replication permission. This parameter is supported only when the instance runs PostgreSQL with standard or enhanced SSDs. In addition, this parameter is available only when the public key of the CA that issues client certificates is enabled. Valid values:
	// +kubebuilder:validation:Optional
	ReplicationACL *string `json:"replicationAcl,omitempty" tf:"replication_acl,omitempty"`

	// The ID of resource group which the DB instance belongs.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The Alibaba Cloud Resource Name (ARN) of the RAM role.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/ram/v1alpha1.Role
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.RoleArnExtractor()
	// +kubebuilder:validation:Optional
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`

	// Reference to a Role in ram to populate roleArn.
	// +kubebuilder:validation:Optional
	RoleArnRef *v1.Reference `json:"roleArnRef,omitempty" tf:"-"`

	// Selector for a Role in ram to populate roleArn.
	// +kubebuilder:validation:Optional
	RoleArnSelector *v1.Selector `json:"roleArnSelector,omitempty" tf:"-"`

	// The sql collector keep time of the instance. Valid values are 30, 180, 365, 1095, 1825, Default to 30.
	// -> NOTE: This parameter takes effect when sql_collector_status is set to Enabled and does not take effect when sql_collector_status is set to Disabled.
	// +kubebuilder:validation:Optional
	SQLCollectorConfigValue *float64 `json:"sqlCollectorConfigValue,omitempty" tf:"sql_collector_config_value,omitempty"`

	// The sql collector status of the instance. Valid values are Enabled, Disabled, Default to Disabled.
	// +kubebuilder:validation:Optional
	SQLCollectorStatus *string `json:"sqlCollectorStatus,omitempty" tf:"sql_collector_status,omitempty"`

	// Actions performed on SSL functions. Valid values:
	// Open: turn on SSL encryption;
	// Close: turn off SSL encryption;
	// Update: update SSL certificate.
	// See more engine and engineVersion limitation.
	// +kubebuilder:validation:Optional
	SSLAction *string `json:"sslAction,omitempty" tf:"ssl_action,omitempty"`

	// The custom certificate.
	// +kubebuilder:validation:Optional
	SSLCertificateSecretRef *v1.SecretKeySelector `json:"sslCertificateSecretRef,omitempty" tf:"-"`

	// The internal or public endpoint for which the server certificate needs to be created or updated.
	// +kubebuilder:validation:Optional
	SSLConnectionString *string `json:"sslConnectionString,omitempty" tf:"ssl_connection_string,omitempty"`

	// The password of the certificate.
	// +kubebuilder:validation:Optional
	SSLPasswordSecretRef *v1.SecretKeySelector `json:"sslPasswordSecretRef,omitempty" tf:"-"`

	// References to SecurityGroup in ecs to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIDRefs []v1.Reference `json:"securityGroupIdRefs,omitempty" tf:"-"`

	// Selector for a list of SecurityGroup in ecs to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIDSelector *v1.Selector `json:"securityGroupIdSelector,omitempty" tf:"-"`

	// , Available since v1.69.0) The list IDs to join ECS Security Group. At most supports three security groups.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/ecs/v1alpha1.SecurityGroup
	// +crossplane:generate:reference:refFieldName=SecurityGroupIDRefs
	// +crossplane:generate:reference:selectorFieldName=SecurityGroupIDSelector
	// +kubebuilder:validation:Optional
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// Valid values are normal, safety, Default to normal. support safety switch to high security access mode.
	// +kubebuilder:validation:Optional
	SecurityIPMode *string `json:"securityIpMode,omitempty" tf:"security_ip_mode,omitempty"`

	// The type of IP address in the IP address whitelist.
	// +kubebuilder:validation:Optional
	SecurityIPType *string `json:"securityIpType,omitempty" tf:"security_ip_type,omitempty"`

	// List of IP addresses allowed to access all databases of an instance. The list contains up to 1,000 IP addresses, separated by commas. Supported formats include 0.0.0.0/0, 10.23.12.24 (IP), and 10.23.12.24/24 (Classless Inter-Domain Routing (CIDR) mode. /24 represents the length of the prefix in an IP address. The range of the prefix length is [1,32]).
	// +kubebuilder:validation:Optional
	// +listType=set
	SecurityIps []*string `json:"securityIps,omitempty" tf:"security_ips,omitempty"`

	// The content of the server certificate. This parameter is supported only when the instance runs PostgreSQL or MySQL with standard or enhanced SSDs. If you set the CAType parameter to custom, you must also specify this parameter. NOTE: From version 1.231.0, server_cert start  support MySQL engine.
	// +kubebuilder:validation:Optional
	ServerCertSecretRef *v1.SecretKeySelector `json:"serverCertSecretRef,omitempty" tf:"-"`

	// The private key of the server certificate. This parameter is supported only when the instance runs PostgreSQL or MySQL with standard or enhanced SSDs. If you set the CAType parameter to custom, you must also specify this parameter. NOTE: From version 1.231.0, server_key start support MySQL engine.
	// +kubebuilder:validation:Optional
	ServerKey *string `json:"serverKey,omitempty" tf:"server_key,omitempty"`

	// The settings of the serverless instance. This parameter is required when you create a serverless instance. This parameter takes effect only when you create an ApsaraDB RDS for Serverless instance. See serverless_config below.
	// +kubebuilder:validation:Optional
	ServerlessConfig []ServerlessConfigParameters `json:"serverlessConfig,omitempty" tf:"serverless_config,omitempty"`

	// Automatic storage space expansion switch. Valid values:
	// +kubebuilder:validation:Optional
	StorageAutoScale *string `json:"storageAutoScale,omitempty" tf:"storage_auto_scale,omitempty"`

	// The threshold in percentage based on which an automatic storage expansion is triggered. If the available storage reaches the threshold, ApsaraDB RDS increases the storage capacity of the instance.
	// Valid values: [10, 20, 30, 40, 50].
	// +kubebuilder:validation:Optional
	StorageThreshold *float64 `json:"storageThreshold,omitempty" tf:"storage_threshold,omitempty"`

	// The upper limit of the total storage space for automatic expansion of the storage space, that is, automatic expansion will not cause the total storage space of the instance to exceed this value. Unit: GB. The value must be ≥0.
	// +kubebuilder:validation:Optional
	StorageUpperBound *float64 `json:"storageUpperBound,omitempty" tf:"storage_upper_bound,omitempty"`

	// The specific point in time when you want to perform the update. Specify the time in the ISO 8601 standard in the yyyy-MM-ddTHH:mm:ssZ format. It is valid only when target_minor_version is changed. The time must be in UTC.
	// +kubebuilder:validation:Optional
	SwitchTime *string `json:"switchTime,omitempty" tf:"switch_time,omitempty"`

	// The availability check method of the instance. Valid values:
	// +kubebuilder:validation:Optional
	TCPConnectionType *string `json:"tcpConnectionType,omitempty" tf:"tcp_connection_type,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The minor engine version to which you want to update the instance. If you do not specify this parameter, the instance is updated to the latest minor engine version. You must specify the minor engine version in one of the following formats:
	// +kubebuilder:validation:Optional
	TargetMinorVersion *string `json:"targetMinorVersion,omitempty" tf:"target_minor_version,omitempty"`

	// The file that contains the certificate..
	// +kubebuilder:validation:Optional
	TdeCertificateSecretRef *v1.SecretKeySelector `json:"tdeCertificateSecretRef,omitempty" tf:"-"`

	// The name of the database for which you want to enable TDE. You can specify up to 50 database names in a single request. If you specify multiple database names, separate the database names with commas (,).
	// +kubebuilder:validation:Optional
	TdeDBName *string `json:"tdeDbName,omitempty" tf:"tde_db_name,omitempty"`

	// The ID of the custom key.
	// +kubebuilder:validation:Optional
	TdeEncryptionKey *string `json:"tdeEncryptionKey,omitempty" tf:"tde_encryption_key,omitempty"`

	// The password of the certificate.
	// +kubebuilder:validation:Optional
	TdePasswordSecretRef *v1.SecretKeySelector `json:"tdePasswordSecretRef,omitempty" tf:"-"`

	// The file that contains the private key of the certificate..
	// +kubebuilder:validation:Optional
	TdePrivateKeySecretRef *v1.SecretKeySelector `json:"tdePrivateKeySecretRef,omitempty" tf:"-"`

	// The TDE(Transparent Data Encryption) status. After TDE is turned on, it cannot be turned off. See more engine and engineVersion limitation.
	// +kubebuilder:validation:Optional
	TdeStatus *string `json:"tdeStatus,omitempty" tf:"tde_status,omitempty"`

	// Whitelist Template ID List.
	// +kubebuilder:validation:Optional
	TemplateIDList []*float64 `json:"templateIdList,omitempty" tf:"template_id_list,omitempty"`

	// The time zone of the instance. By default, the system does not modify the time zone.
	// +kubebuilder:validation:Optional
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`

	// (Deprecated from v1.198.0)  Whether to upgrade a minor version of the kernel. Valid values:
	// +kubebuilder:validation:Optional
	UpgradeDBInstanceKernelVersion *bool `json:"upgradeDbInstanceKernelVersion,omitempty" tf:"upgrade_db_instance_kernel_version,omitempty"`

	// The method to update the minor engine version. Default value: Immediate. It is valid only when target_minor_version is changed. Valid values:
	// +kubebuilder:validation:Optional
	UpgradeTime *string `json:"upgradeTime,omitempty" tf:"upgrade_time,omitempty"`

	// The VPC ID of the instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.VPC
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Reference to a VPC in vpc to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDRef *v1.Reference `json:"vpcIdRef,omitempty" tf:"-"`

	// Selector for a VPC in vpc to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDSelector *v1.Selector `json:"vpcIdSelector,omitempty" tf:"-"`

	// (ForceNew, Optional) The virtual switch ID to launch DB instances in one VPC. If there are multiple vswitches, separate them with commas.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.Vswitch
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	// +kubebuilder:validation:Optional
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// Reference to a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDRef *v1.Reference `json:"vswitchIdRef,omitempty" tf:"-"`

	// Selector for a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDSelector *v1.Selector `json:"vswitchIdSelector,omitempty" tf:"-"`

	// The network type of the IP address whitelist. Default value: MIX. Valid values:
	// +kubebuilder:validation:Optional
	WhitelistNetworkType *string `json:"whitelistNetworkType,omitempty" tf:"whitelist_network_type,omitempty"`

	// (ForceNew, Optional) The Zone to launch the DB instance. From version 1.8.1, it supports multiple zone.
	// If it is a multi-zone and vswitch_id is specified, the vswitch must in the one of them.
	// The multiple zone ID can be retrieved by setting multi to "true" in the data source alicloud_zones.
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// The region ID of the secondary instance if you create a secondary instance. If you set this parameter to the same value as the ZoneId parameter, the instance is deployed in a single zone. Otherwise, the instance is deployed in multiple zones.
	// +kubebuilder:validation:Optional
	ZoneIDSlaveA *string `json:"zoneIdSlaveA,omitempty" tf:"zone_id_slave_a,omitempty"`

	// RDS MySQL Cluster series instances support creating 1 to 2 secondary nodes at the same time when establishing a new instance. If you have this requirement, you can use this parameter to specify the availability zone for the second secondary node.
	// +kubebuilder:validation:Optional
	ZoneIDSlaveB *string `json:"zoneIdSlaveB,omitempty" tf:"zone_id_slave_b,omitempty"`
}

type ParametersInitParameters struct {

	// The parameter name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The parameter value.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ParametersObservation struct {

	// The parameter name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The parameter value.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ParametersParameters struct {

	// The parameter name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// The parameter value.
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type PgHbaConfInitParameters struct {

	// The IP addresses from which the specified users can access the specified databases. If you set this parameter to 0.0.0.0/0, the specified users are allowed to access the specified databases from all IP addresses.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// The name of the database that the specified users are allowed to access. If you set this parameter to all, the specified users are allowed to access all databases in the instance. If you specify multiple databases, separate the database names with commas (,).
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// The mask of the instance. If the value of the Address parameter is an IP address, you can use this parameter to specify the mask of the IP address.
	Mask *string `json:"mask,omitempty" tf:"mask,omitempty"`

	// The authentication method of Lightweight Directory Access Protocol (LDAP). Valid values: trust, reject, scram-sha-256, md5, password, gss, sspi, ldap, radius, cert, pam.
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// Optional. The value of this parameter is based on the value of the HbaItem.N.Method parameter. In this topic, LDAP is used as an example. You must configure this parameter. For more information, see Authentication Methods.
	Option *string `json:"option,omitempty" tf:"option,omitempty"`

	// The priority of an AD domain. If you set this parameter to 0, the AD domain has the highest priority. Valid values: 0 to 10000. This parameter is used to identify each AD domain. When you add an AD domain, the value of the PriorityId parameter of the new AD domain cannot be the same as the value of the PriorityId parameter for any existing AD domain. When you modify or delete an AD domain, you must also modify or delete the value of the PriorityId parameter for this AD domain.
	PriorityID *float64 `json:"priorityId,omitempty" tf:"priority_id,omitempty"`

	// The type of connection to the instance. Valid values:
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The user that is allowed to access the instance. If you specify multiple users, separate the usernames with commas (,).
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type PgHbaConfObservation struct {

	// The IP addresses from which the specified users can access the specified databases. If you set this parameter to 0.0.0.0/0, the specified users are allowed to access the specified databases from all IP addresses.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// The name of the database that the specified users are allowed to access. If you set this parameter to all, the specified users are allowed to access all databases in the instance. If you specify multiple databases, separate the database names with commas (,).
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// The mask of the instance. If the value of the Address parameter is an IP address, you can use this parameter to specify the mask of the IP address.
	Mask *string `json:"mask,omitempty" tf:"mask,omitempty"`

	// The authentication method of Lightweight Directory Access Protocol (LDAP). Valid values: trust, reject, scram-sha-256, md5, password, gss, sspi, ldap, radius, cert, pam.
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// Optional. The value of this parameter is based on the value of the HbaItem.N.Method parameter. In this topic, LDAP is used as an example. You must configure this parameter. For more information, see Authentication Methods.
	Option *string `json:"option,omitempty" tf:"option,omitempty"`

	// The priority of an AD domain. If you set this parameter to 0, the AD domain has the highest priority. Valid values: 0 to 10000. This parameter is used to identify each AD domain. When you add an AD domain, the value of the PriorityId parameter of the new AD domain cannot be the same as the value of the PriorityId parameter for any existing AD domain. When you modify or delete an AD domain, you must also modify or delete the value of the PriorityId parameter for this AD domain.
	PriorityID *float64 `json:"priorityId,omitempty" tf:"priority_id,omitempty"`

	// The type of connection to the instance. Valid values:
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The user that is allowed to access the instance. If you specify multiple users, separate the usernames with commas (,).
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type PgHbaConfParameters struct {

	// The IP addresses from which the specified users can access the specified databases. If you set this parameter to 0.0.0.0/0, the specified users are allowed to access the specified databases from all IP addresses.
	// +kubebuilder:validation:Optional
	Address *string `json:"address" tf:"address,omitempty"`

	// The name of the database that the specified users are allowed to access. If you set this parameter to all, the specified users are allowed to access all databases in the instance. If you specify multiple databases, separate the database names with commas (,).
	// +kubebuilder:validation:Optional
	Database *string `json:"database" tf:"database,omitempty"`

	// The mask of the instance. If the value of the Address parameter is an IP address, you can use this parameter to specify the mask of the IP address.
	// +kubebuilder:validation:Optional
	Mask *string `json:"mask,omitempty" tf:"mask,omitempty"`

	// The authentication method of Lightweight Directory Access Protocol (LDAP). Valid values: trust, reject, scram-sha-256, md5, password, gss, sspi, ldap, radius, cert, pam.
	// +kubebuilder:validation:Optional
	Method *string `json:"method" tf:"method,omitempty"`

	// Optional. The value of this parameter is based on the value of the HbaItem.N.Method parameter. In this topic, LDAP is used as an example. You must configure this parameter. For more information, see Authentication Methods.
	// +kubebuilder:validation:Optional
	Option *string `json:"option,omitempty" tf:"option,omitempty"`

	// The priority of an AD domain. If you set this parameter to 0, the AD domain has the highest priority. Valid values: 0 to 10000. This parameter is used to identify each AD domain. When you add an AD domain, the value of the PriorityId parameter of the new AD domain cannot be the same as the value of the PriorityId parameter for any existing AD domain. When you modify or delete an AD domain, you must also modify or delete the value of the PriorityId parameter for this AD domain.
	// +kubebuilder:validation:Optional
	PriorityID *float64 `json:"priorityId" tf:"priority_id,omitempty"`

	// The type of connection to the instance. Valid values:
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`

	// The user that is allowed to access the instance. If you specify multiple users, separate the usernames with commas (,).
	// +kubebuilder:validation:Optional
	User *string `json:"user" tf:"user,omitempty"`
}

type ServerlessConfigInitParameters struct {

	// Specifies whether to enable the smart startup and stop feature for the serverless instance. Valid values:
	AutoPause *bool `json:"autoPause,omitempty" tf:"auto_pause,omitempty"`

	// The maximum number of RDS Capacity Units (RCUs). The value of this parameter must be greater than or equal to min_capacity and only supports passing integers. Valid values:
	MaxCapacity *float64 `json:"maxCapacity,omitempty" tf:"max_capacity,omitempty"`

	// The minimum number of RCUs. The value of this parameter must be less than or equal to max_capacity. Valid values:
	MinCapacity *float64 `json:"minCapacity,omitempty" tf:"min_capacity,omitempty"`

	// Specifies whether to enable the forced scaling feature for the serverless instance. Valid values:
	SwitchForce *bool `json:"switchForce,omitempty" tf:"switch_force,omitempty"`
}

type ServerlessConfigObservation struct {

	// Specifies whether to enable the smart startup and stop feature for the serverless instance. Valid values:
	AutoPause *bool `json:"autoPause,omitempty" tf:"auto_pause,omitempty"`

	// The maximum number of RDS Capacity Units (RCUs). The value of this parameter must be greater than or equal to min_capacity and only supports passing integers. Valid values:
	MaxCapacity *float64 `json:"maxCapacity,omitempty" tf:"max_capacity,omitempty"`

	// The minimum number of RCUs. The value of this parameter must be less than or equal to max_capacity. Valid values:
	MinCapacity *float64 `json:"minCapacity,omitempty" tf:"min_capacity,omitempty"`

	// Specifies whether to enable the forced scaling feature for the serverless instance. Valid values:
	SwitchForce *bool `json:"switchForce,omitempty" tf:"switch_force,omitempty"`
}

type ServerlessConfigParameters struct {

	// Specifies whether to enable the smart startup and stop feature for the serverless instance. Valid values:
	// +kubebuilder:validation:Optional
	AutoPause *bool `json:"autoPause,omitempty" tf:"auto_pause,omitempty"`

	// The maximum number of RDS Capacity Units (RCUs). The value of this parameter must be greater than or equal to min_capacity and only supports passing integers. Valid values:
	// +kubebuilder:validation:Optional
	MaxCapacity *float64 `json:"maxCapacity" tf:"max_capacity,omitempty"`

	// The minimum number of RCUs. The value of this parameter must be less than or equal to max_capacity. Valid values:
	// +kubebuilder:validation:Optional
	MinCapacity *float64 `json:"minCapacity" tf:"min_capacity,omitempty"`

	// Specifies whether to enable the forced scaling feature for the serverless instance. Valid values:
	// +kubebuilder:validation:Optional
	SwitchForce *bool `json:"switchForce,omitempty" tf:"switch_force,omitempty"`
}

// InstanceSpec defines the desired state of Instance
type InstanceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     InstanceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InstanceInitParameters `json:"initProvider,omitempty"`
}

// InstanceStatus defines the observed state of Instance.
type InstanceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InstanceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Instance is the Schema for the Instances API. Provides an RDS instance resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type Instance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.engine) || (has(self.initProvider) && has(self.initProvider.engine))",message="spec.forProvider.engine is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.engineVersion) || (has(self.initProvider) && has(self.initProvider.engineVersion))",message="spec.forProvider.engineVersion is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.instanceStorage) || (has(self.initProvider) && has(self.initProvider.instanceStorage))",message="spec.forProvider.instanceStorage is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.instanceType) || (has(self.initProvider) && has(self.initProvider.instanceType))",message="spec.forProvider.instanceType is a required parameter"
	Spec   InstanceSpec   `json:"spec"`
	Status InstanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstanceList contains a list of Instances
type InstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Instance `json:"items"`
}

// Repository type metadata.
var (
	Instance_Kind             = "Instance"
	Instance_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Instance_Kind}.String()
	Instance_KindAPIVersion   = Instance_Kind + "." + CRDGroupVersion.String()
	Instance_GroupVersionKind = CRDGroupVersion.WithKind(Instance_Kind)
)

func init() {
	SchemeBuilder.Register(&Instance{}, &InstanceList{})
}
