// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ParamDetailInitParameters struct {

	// The name of a parameter.
	ParamName *string `json:"paramName,omitempty" tf:"param_name,omitempty"`

	// The value of a parameter.
	ParamValue *string `json:"paramValue,omitempty" tf:"param_value,omitempty"`
}

type ParamDetailObservation struct {

	// The name of a parameter.
	ParamName *string `json:"paramName,omitempty" tf:"param_name,omitempty"`

	// The value of a parameter.
	ParamValue *string `json:"paramValue,omitempty" tf:"param_value,omitempty"`
}

type ParamDetailParameters struct {

	// The name of a parameter.
	// +kubebuilder:validation:Optional
	ParamName *string `json:"paramName" tf:"param_name,omitempty"`

	// The value of a parameter.
	// +kubebuilder:validation:Optional
	ParamValue *string `json:"paramValue" tf:"param_value,omitempty"`
}

type ParameterGroupInitParameters struct {

	// The database engine. Valid values: mysql, mariadb, PostgreSQL.
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// The version of the database engine. Valid values: mysql: 5.1, 5.5, 5.6, 5.7, 8.0; mariadb: 10.3; PostgreSQL: 10.0, 11.0, 12.0, 13.0, 14.0, 15.0.
	EngineVersion *string `json:"engineVersion,omitempty" tf:"engine_version,omitempty"`

	// Parameter list. See param_detail below.
	ParamDetail []ParamDetailInitParameters `json:"paramDetail,omitempty" tf:"param_detail,omitempty"`

	// The description of the parameter template.
	ParameterGroupDesc *string `json:"parameterGroupDesc,omitempty" tf:"parameter_group_desc,omitempty"`

	// The name of the parameter template.
	ParameterGroupName *string `json:"parameterGroupName,omitempty" tf:"parameter_group_name,omitempty"`
}

type ParameterGroupObservation struct {

	// The database engine. Valid values: mysql, mariadb, PostgreSQL.
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// The version of the database engine. Valid values: mysql: 5.1, 5.5, 5.6, 5.7, 8.0; mariadb: 10.3; PostgreSQL: 10.0, 11.0, 12.0, 13.0, 14.0, 15.0.
	EngineVersion *string `json:"engineVersion,omitempty" tf:"engine_version,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Parameter list. See param_detail below.
	ParamDetail []ParamDetailObservation `json:"paramDetail,omitempty" tf:"param_detail,omitempty"`

	// The description of the parameter template.
	ParameterGroupDesc *string `json:"parameterGroupDesc,omitempty" tf:"parameter_group_desc,omitempty"`

	// The name of the parameter template.
	ParameterGroupName *string `json:"parameterGroupName,omitempty" tf:"parameter_group_name,omitempty"`
}

type ParameterGroupParameters struct {

	// The database engine. Valid values: mysql, mariadb, PostgreSQL.
	// +kubebuilder:validation:Optional
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// The version of the database engine. Valid values: mysql: 5.1, 5.5, 5.6, 5.7, 8.0; mariadb: 10.3; PostgreSQL: 10.0, 11.0, 12.0, 13.0, 14.0, 15.0.
	// +kubebuilder:validation:Optional
	EngineVersion *string `json:"engineVersion,omitempty" tf:"engine_version,omitempty"`

	// Parameter list. See param_detail below.
	// +kubebuilder:validation:Optional
	ParamDetail []ParamDetailParameters `json:"paramDetail,omitempty" tf:"param_detail,omitempty"`

	// The description of the parameter template.
	// +kubebuilder:validation:Optional
	ParameterGroupDesc *string `json:"parameterGroupDesc,omitempty" tf:"parameter_group_desc,omitempty"`

	// The name of the parameter template.
	// +kubebuilder:validation:Optional
	ParameterGroupName *string `json:"parameterGroupName,omitempty" tf:"parameter_group_name,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`
}

// ParameterGroupSpec defines the desired state of ParameterGroup
type ParameterGroupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ParameterGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ParameterGroupInitParameters `json:"initProvider,omitempty"`
}

// ParameterGroupStatus defines the observed state of ParameterGroup.
type ParameterGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ParameterGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ParameterGroup is the Schema for the ParameterGroups API. Provides a Alicloud RDS Parameter Group resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type ParameterGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.engine) || (has(self.initProvider) && has(self.initProvider.engine))",message="spec.forProvider.engine is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.engineVersion) || (has(self.initProvider) && has(self.initProvider.engineVersion))",message="spec.forProvider.engineVersion is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.paramDetail) || (has(self.initProvider) && has(self.initProvider.paramDetail))",message="spec.forProvider.paramDetail is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parameterGroupName) || (has(self.initProvider) && has(self.initProvider.parameterGroupName))",message="spec.forProvider.parameterGroupName is a required parameter"
	Spec   ParameterGroupSpec   `json:"spec"`
	Status ParameterGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ParameterGroupList contains a list of ParameterGroups
type ParameterGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ParameterGroup `json:"items"`
}

// Repository type metadata.
var (
	ParameterGroup_Kind             = "ParameterGroup"
	ParameterGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ParameterGroup_Kind}.String()
	ParameterGroup_KindAPIVersion   = ParameterGroup_Kind + "." + CRDGroupVersion.String()
	ParameterGroup_GroupVersionKind = CRDGroupVersion.WithKind(ParameterGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&ParameterGroup{}, &ParameterGroupList{})
}
