// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type WhitelistTemplateInitParameters struct {

	// IP whitelist, multiple IP addresses should be separated by commas (,) and cannot be duplicated.Supports the following two formats:
	IPWhiteList *string `json:"ipWhiteList,omitempty" tf:"ip_white_list,omitempty"`

	// Whitelist template name. Passed in when creating a template, and cannot have the same name under the same account, starting with a letter.
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`
}

type WhitelistTemplateObservation struct {

	// The ID of the resource supplied above.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// IP whitelist, multiple IP addresses should be separated by commas (,) and cannot be duplicated.Supports the following two formats:
	IPWhiteList *string `json:"ipWhiteList,omitempty" tf:"ip_white_list,omitempty"`

	// Whitelist template name. Passed in when creating a template, and cannot have the same name under the same account, starting with a letter.
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`
}

type WhitelistTemplateParameters struct {

	// IP whitelist, multiple IP addresses should be separated by commas (,) and cannot be duplicated.Supports the following two formats:
	// +kubebuilder:validation:Optional
	IPWhiteList *string `json:"ipWhiteList,omitempty" tf:"ip_white_list,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// Whitelist template name. Passed in when creating a template, and cannot have the same name under the same account, starting with a letter.
	// +kubebuilder:validation:Optional
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`
}

// WhitelistTemplateSpec defines the desired state of WhitelistTemplate
type WhitelistTemplateSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     WhitelistTemplateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WhitelistTemplateInitParameters `json:"initProvider,omitempty"`
}

// WhitelistTemplateStatus defines the observed state of WhitelistTemplate.
type WhitelistTemplateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WhitelistTemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WhitelistTemplate is the Schema for the WhitelistTemplates API. Provide a whitelist template.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type WhitelistTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ipWhiteList) || (has(self.initProvider) && has(self.initProvider.ipWhiteList))",message="spec.forProvider.ipWhiteList is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.templateName) || (has(self.initProvider) && has(self.initProvider.templateName))",message="spec.forProvider.templateName is a required parameter"
	Spec   WhitelistTemplateSpec   `json:"spec"`
	Status WhitelistTemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WhitelistTemplateList contains a list of WhitelistTemplates
type WhitelistTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WhitelistTemplate `json:"items"`
}

// Repository type metadata.
var (
	WhitelistTemplate_Kind             = "WhitelistTemplate"
	WhitelistTemplate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WhitelistTemplate_Kind}.String()
	WhitelistTemplate_KindAPIVersion   = WhitelistTemplate_Kind + "." + CRDGroupVersion.String()
	WhitelistTemplate_GroupVersionKind = CRDGroupVersion.WithKind(WhitelistTemplate_Kind)
)

func init() {
	SchemeBuilder.Register(&WhitelistTemplate{}, &WhitelistTemplateList{})
}
