---
apiVersion: cr.alibabacloud.crossplane.io/v1alpha1
kind: RegistryNamespace
metadata:
  annotations:
    meta.crossplane.io/example-id: cr-v1alpha1-region-probe-cn
  labels:
    testing.crossplane.io/example-name: region-probe-cn
  name: test-namespace-cnhz
spec:
  forProvider:
    region: cn-hangzhou
    autoCreate: false
    defaultVisibility: PUBLIC
    name: test-namespace-cnhz
