---
apiVersion: kms.alibabacloud.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.crossplane.io/example-id: kms-v1alpha1-test-secret-1
  labels:
    testing.crossplane.io/example-name: test-secret-1
  name: test-secret-1
spec:
  forProvider:
    description: test-secret-1 created by provider-upjet-alibabacloud
    forceDeleteWithoutRecovery: true
    secretDataSecretRef:
      key: password
      name: login-profile-secret
      namespace: upbound-system
    secretName: test-secret-1
    secretType: Generic
    versionId: v1
    tags:
      createdBy: provider-upjet-alibabacloud
