apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: DiskAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/diskattachment
  labels:
    testing.upbound.io/example-name: ecs_disk_att
  name: ecs-disk-att
spec:
  forProvider:
    diskId: ${alicloud_disk.ecs_disk.id}
    instanceId: ${alicloud_instance.ecs_instance.id}

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Disk
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/diskattachment
  labels:
    testing.upbound.io/example-name: ecs_disk
  name: ecs-disk
spec:
  forProvider:
    availabilityZone: cn-beijing-a
    size: "50"
    tags:
      Name: TerraformTest-disk

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/diskattachment
  labels:
    testing.upbound.io/example-name: ecs_instance
  name: ecs-instance
spec:
  forProvider:
    availabilityZone: cn-beijing-a
    imageId: ubuntu_18_04_64_20G_alibase_20190624.vhd
    instanceName: Hello
    instanceType: ecs.n4.small
    internetChargeType: PayByBandwidth
    securityGroups:
    - ${alicloud_security_group.ecs_sg.id}
    tags:
      Name: TerraformTest-instance

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/diskattachment
  labels:
    testing.upbound.io/example-name: ecs_sg
  name: ecs-sg
spec:
  forProvider:
    description: New security group
    name: terraform-test-group
