apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: LaunchTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/launchtemplate
  labels:
    testing.upbound.io/example-name: template
  name: template
spec:
  forProvider:
    dataDisks:
    - description: test1
      name: disk1
    - description: test2
      name: disk2
    description: test1
    hostName: tf-test-host
    imageId: ${data.alicloud_images.images.images[0].id}
    instanceChargeType: PrePaid
    instanceName: tf-instance-name
    instanceType: ${data.alicloud_instances.instances.instances[0].instance_type}
    internetChargeType: PayByBandwidth
    internetMaxBandwidthIn: 5
    internetMaxBandwidthOut: 0
    ioOptimized: none
    keyPairName: test-key-pair
    name: tf-test-template
    networkInterfaces:
    - description: hello1
      name: eth0
      primaryIp: 10.0.0.2
      securityGroupId: xxxx
      vswitchId: xxxxxxx
    networkType: vpc
    ramRoleName: xxxxx
    resourceGroupId: rg-zkdfjahg9zxncv0
    securityEnhancementStrategy: Active
    securityGroupId: sg-zxcvj0lasdf102350asdf9a
    spotPriceLimit: 5
    spotStrategy: SpotWithPriceLimit
    systemDiskCategory: cloud_ssd
    systemDiskDescription: test disk
    systemDiskName: hello
    systemDiskSize: 40
    tags:
      tag1: hello
      tag2: world
    userdata: xxxxxxxxxxxxxx
    vpcId: vpc-asdfnbg0as8dfk1nb2
    vswitchId: sw-ljkngaksdjfj0nnasdf
    zoneId: beijing-a
