apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: NetworkInterfaceAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/networkinterfaceattachment
  labels:
    testing.upbound.io/example-name: attachment
  name: attachment
spec:
  forProvider:
    count: ${var.number}
    instanceId: ${element(alicloud_instance.instance.*.id, count.index)}
    networkInterfaceId: ${element(alicloud_network_interface.interface.*.id, count.index)}

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/networkinterfaceattachment
  labels:
    testing.upbound.io/example-name: instance
  name: instance
spec:
  forProvider:
    availabilityZone: ${data.alicloud_zones.default.zones[0].id}
    count: ${var.number}
    imageId: ${data.alicloud_images.default.images[0].id}
    instanceName: ${var.name}
    instanceType: ${data.alicloud_instance_types.instance_type.instance_types[0].id}
    internetMaxBandwidthOut: 10
    securityGroups:
    - ${alicloud_security_group.group.id}
    systemDiskCategory: cloud_efficiency
    vswitchId: ${alicloud_vswitch.vswitch.id}

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: NetworkInterface
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/networkinterfaceattachment
  labels:
    testing.upbound.io/example-name: interface
  name: interface
spec:
  forProvider:
    count: ${var.number}
    name: ${var.name}
    securityGroups:
    - ${alicloud_security_group.group.id}
    vswitchId: ${alicloud_vswitch.vswitch.id}

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/networkinterfaceattachment
  labels:
    testing.upbound.io/example-name: group
  name: group
spec:
  forProvider:
    name: ${var.name}
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/networkinterfaceattachment
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 192.168.0.0/24
    name: ${var.name}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/networkinterfaceattachment
  labels:
    testing.upbound.io/example-name: vswitch
  name: vswitch
spec:
  forProvider:
    cidrBlock: 192.168.0.0/24
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc
    vswitchName: ${var.name}
    zoneId: ${data.alicloud_zones.default.zones[0].id}
