apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Snapshot
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: snapshot
  name: snapshot
spec:
  forProvider:
    description: this snapshot is created for testing
    diskId: ${alicloud_disk_attachment.instance-attachment.disk_id}
    name: test-snapshot
    tags:
      version: "1.2"
