---
apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketCors
metadata:
  annotations:
    meta.crossplane.io/example-id: oss-v1alpha1-test-bucketcors-1
  labels:
    testing.crossplane.io/example-name: test-bucketcors-1
  name: test-bucketcors-1
spec:
  forProvider:
    bucket: test-bucket-for-bucketcors-1
    corsRule:
    - allowedHeaders:
        - x-oss-test
        - x-oss-abc
      allowedMethods:
        - GET
      allowedOrigins:
        - '*'
      exposeHeader:
        - x-oss-request-id
      maxAgeSeconds: "1000"
    responseVary: true
---
apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.crossplane.io/example-id: oss-v1alpha1-test-bucket-for-bucketcors-1
  labels:
    testing.crossplane.io/example-name: test-bucket-for-bucketcors-1
  name: test-bucket-for-bucketcors-1
spec:
  forProvider:
    bucket: test-bucket-for-bucketcors-1
    storageClass: Standard
