apiVersion: sls.alibabacloud.crossplane.io/v1alpha1
kind: Store
metadata:
  annotations:
    meta.upbound.io/example-id: sls/v1alpha1/store
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    region: cn-beijing
    logstoreName: crossplane-example-store
    projectNameSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    shardCount: 2
    autoSplit: true
    maxSplitShardCount: 60
    appendMeta: true
    retentionPeriod: 30

---

apiVersion: sls.alibabacloud.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: sls/v1alpha1/store
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    region: cn-beijing
    projectName: crossplane-example-store-project
    description: crossplane example log project
