---
apiVersion: quotas.alibabacloud.crossplane.io/v1alpha1
kind: TemplateQuota
metadata:
  annotations:
    meta.crossplane.io/example-id: quotas-v1alpha1-test-templatequota-1
  labels:
    testing.crossplane.io/example-name: test-templatequota-1
  name: test-templatequota-1
spec:
  forProvider:
    desireValue: 1001
    dimensions:
    - key: regionId
      value: us-west-1
    envLanguage: en
    noticeType: 3
    productCode: gws
    quotaActionCode: q_desktop-count
    quotaCategory: CommonQuota
