---
apiVersion: quotas.alibabacloud.crossplane.io/v1alpha1
kind: TemplateService
metadata:
  annotations:
    meta.crossplane.io/example-id: quotas-v1alpha1-test-templateservice-1
  labels:
    testing.crossplane.io/example-name: test-templateservice-1
  name: test-templateservice-1
spec:
  forProvider:
    serviceStatus: "1"
