// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ACLEntriesInitParameters struct {

	// List of the egress entries of the network acl. The order of the egress entries determines the priority. The details see Block Egress.
	Egress []EgressInitParameters `json:"egress,omitempty" tf:"egress,omitempty"`

	// List of the ingress entries of the network acl. The order of the ingress entries determines the priority. The details see Block Ingress.
	Ingress []IngressInitParameters `json:"ingress,omitempty" tf:"ingress,omitempty"`

	// The id of the network acl, the field can't be changed.
	NetworkACLID *string `json:"networkAclId,omitempty" tf:"network_acl_id,omitempty"`
}

type ACLEntriesObservation struct {

	// List of the egress entries of the network acl. The order of the egress entries determines the priority. The details see Block Egress.
	Egress []EgressObservation `json:"egress,omitempty" tf:"egress,omitempty"`

	// The ID of the network acl entries. It is formatted as <network_acl_id>:<a unique id>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of the ingress entries of the network acl. The order of the ingress entries determines the priority. The details see Block Ingress.
	Ingress []IngressObservation `json:"ingress,omitempty" tf:"ingress,omitempty"`

	// The id of the network acl, the field can't be changed.
	NetworkACLID *string `json:"networkAclId,omitempty" tf:"network_acl_id,omitempty"`
}

type ACLEntriesParameters struct {

	// List of the egress entries of the network acl. The order of the egress entries determines the priority. The details see Block Egress.
	// +kubebuilder:validation:Optional
	Egress []EgressParameters `json:"egress,omitempty" tf:"egress,omitempty"`

	// List of the ingress entries of the network acl. The order of the ingress entries determines the priority. The details see Block Ingress.
	// +kubebuilder:validation:Optional
	Ingress []IngressParameters `json:"ingress,omitempty" tf:"ingress,omitempty"`

	// The id of the network acl, the field can't be changed.
	// +kubebuilder:validation:Optional
	NetworkACLID *string `json:"networkAclId,omitempty" tf:"network_acl_id,omitempty"`
}

type EgressInitParameters struct {

	// The description of the ingress entry.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The destination ip of the egress entry.
	DestinationCidrIP *string `json:"destinationCidrIp,omitempty" tf:"destination_cidr_ip,omitempty"`

	// The entry type of the ingress entry. It must be custom or system. Default value is custom.
	EntryType *string `json:"entryType,omitempty" tf:"entry_type,omitempty"`

	// The name of the ingress entry.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The policy of the ingress entry. It must be accept or drop.
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// The port of the ingress entry.
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// The protocol of the ingress entry.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type EgressObservation struct {

	// The description of the ingress entry.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The destination ip of the egress entry.
	DestinationCidrIP *string `json:"destinationCidrIp,omitempty" tf:"destination_cidr_ip,omitempty"`

	// The entry type of the ingress entry. It must be custom or system. Default value is custom.
	EntryType *string `json:"entryType,omitempty" tf:"entry_type,omitempty"`

	// The name of the ingress entry.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The policy of the ingress entry. It must be accept or drop.
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// The port of the ingress entry.
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// The protocol of the ingress entry.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type EgressParameters struct {

	// The description of the ingress entry.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The destination ip of the egress entry.
	// +kubebuilder:validation:Optional
	DestinationCidrIP *string `json:"destinationCidrIp,omitempty" tf:"destination_cidr_ip,omitempty"`

	// The entry type of the ingress entry. It must be custom or system. Default value is custom.
	// +kubebuilder:validation:Optional
	EntryType *string `json:"entryType,omitempty" tf:"entry_type,omitempty"`

	// The name of the ingress entry.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The policy of the ingress entry. It must be accept or drop.
	// +kubebuilder:validation:Optional
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// The port of the ingress entry.
	// +kubebuilder:validation:Optional
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// The protocol of the ingress entry.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type IngressInitParameters struct {

	// The description of the ingress entry.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The entry type of the ingress entry. It must be custom or system. Default value is custom.
	EntryType *string `json:"entryType,omitempty" tf:"entry_type,omitempty"`

	// The name of the ingress entry.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The policy of the ingress entry. It must be accept or drop.
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// The port of the ingress entry.
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// The protocol of the ingress entry.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The source ip of the ingress entry.
	SourceCidrIP *string `json:"sourceCidrIp,omitempty" tf:"source_cidr_ip,omitempty"`
}

type IngressObservation struct {

	// The description of the ingress entry.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The entry type of the ingress entry. It must be custom or system. Default value is custom.
	EntryType *string `json:"entryType,omitempty" tf:"entry_type,omitempty"`

	// The name of the ingress entry.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The policy of the ingress entry. It must be accept or drop.
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// The port of the ingress entry.
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// The protocol of the ingress entry.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The source ip of the ingress entry.
	SourceCidrIP *string `json:"sourceCidrIp,omitempty" tf:"source_cidr_ip,omitempty"`
}

type IngressParameters struct {

	// The description of the ingress entry.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The entry type of the ingress entry. It must be custom or system. Default value is custom.
	// +kubebuilder:validation:Optional
	EntryType *string `json:"entryType,omitempty" tf:"entry_type,omitempty"`

	// The name of the ingress entry.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The policy of the ingress entry. It must be accept or drop.
	// +kubebuilder:validation:Optional
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// The port of the ingress entry.
	// +kubebuilder:validation:Optional
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// The protocol of the ingress entry.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The source ip of the ingress entry.
	// +kubebuilder:validation:Optional
	SourceCidrIP *string `json:"sourceCidrIp,omitempty" tf:"source_cidr_ip,omitempty"`
}

// ACLEntriesSpec defines the desired state of ACLEntries
type ACLEntriesSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ACLEntriesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ACLEntriesInitParameters `json:"initProvider,omitempty"`
}

// ACLEntriesStatus defines the observed state of ACLEntries.
type ACLEntriesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ACLEntriesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ACLEntries is the Schema for the ACLEntriess API. Provides a Alicloud Network Acl Entries resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alicloud}
type ACLEntries struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.networkAclId) || (has(self.initProvider) && has(self.initProvider.networkAclId))",message="spec.forProvider.networkAclId is a required parameter"
	Spec   ACLEntriesSpec   `json:"spec"`
	Status ACLEntriesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ACLEntriesList contains a list of ACLEntriess
type ACLEntriesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ACLEntries `json:"items"`
}

// Repository type metadata.
var (
	ACLEntries_Kind             = "ACLEntries"
	ACLEntries_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ACLEntries_Kind}.String()
	ACLEntries_KindAPIVersion   = ACLEntries_Kind + "." + CRDGroupVersion.String()
	ACLEntries_GroupVersionKind = CRDGroupVersion.WithKind(ACLEntries_Kind)
)

func init() {
	SchemeBuilder.Register(&ACLEntries{}, &ACLEntriesList{})
}
