// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ACLAttachmentInitParameters struct {

	// The id of the network acl, the field can't be changed.
	NetworkACLID *string `json:"networkAclId,omitempty" tf:"network_acl_id,omitempty"`

	// List of the resources associated with the network acl. The details see Block Resources.
	Resources []ACLAttachmentResourcesInitParameters `json:"resources,omitempty" tf:"resources,omitempty"`
}

type ACLAttachmentObservation struct {

	// The ID of the network acl attachment. It is formatted as <network_acl_id>:<a unique id>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The id of the network acl, the field can't be changed.
	NetworkACLID *string `json:"networkAclId,omitempty" tf:"network_acl_id,omitempty"`

	// List of the resources associated with the network acl. The details see Block Resources.
	Resources []ACLAttachmentResourcesObservation `json:"resources,omitempty" tf:"resources,omitempty"`
}

type ACLAttachmentParameters struct {

	// The id of the network acl, the field can't be changed.
	// +kubebuilder:validation:Optional
	NetworkACLID *string `json:"networkAclId,omitempty" tf:"network_acl_id,omitempty"`

	// List of the resources associated with the network acl. The details see Block Resources.
	// +kubebuilder:validation:Optional
	Resources []ACLAttachmentResourcesParameters `json:"resources,omitempty" tf:"resources,omitempty"`
}

type ACLAttachmentResourcesInitParameters struct {

	// The resource id that the network acl will associate with.
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// The resource id that the network acl will associate with. Only support VSwitch now.
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`
}

type ACLAttachmentResourcesObservation struct {

	// The resource id that the network acl will associate with.
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// The resource id that the network acl will associate with. Only support VSwitch now.
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`
}

type ACLAttachmentResourcesParameters struct {

	// The resource id that the network acl will associate with.
	// +kubebuilder:validation:Optional
	ResourceID *string `json:"resourceId" tf:"resource_id,omitempty"`

	// The resource id that the network acl will associate with. Only support VSwitch now.
	// +kubebuilder:validation:Optional
	ResourceType *string `json:"resourceType" tf:"resource_type,omitempty"`
}

// ACLAttachmentSpec defines the desired state of ACLAttachment
type ACLAttachmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ACLAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ACLAttachmentInitParameters `json:"initProvider,omitempty"`
}

// ACLAttachmentStatus defines the observed state of ACLAttachment.
type ACLAttachmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ACLAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ACLAttachment is the Schema for the ACLAttachments API. Provides a Alicloud Network Acl Attachment resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alicloud}
type ACLAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.networkAclId) || (has(self.initProvider) && has(self.initProvider.networkAclId))",message="spec.forProvider.networkAclId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.resources) || (has(self.initProvider) && has(self.initProvider.resources))",message="spec.forProvider.resources is a required parameter"
	Spec   ACLAttachmentSpec   `json:"spec"`
	Status ACLAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ACLAttachmentList contains a list of ACLAttachments
type ACLAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ACLAttachment `json:"items"`
}

// Repository type metadata.
var (
	ACLAttachment_Kind             = "ACLAttachment"
	ACLAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ACLAttachment_Kind}.String()
	ACLAttachment_KindAPIVersion   = ACLAttachment_Kind + "." + CRDGroupVersion.String()
	ACLAttachment_GroupVersionKind = CRDGroupVersion.WithKind(ACLAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&ACLAttachment{}, &ACLAttachmentList{})
}
