// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type IPv6EgressRuleInitParameters struct {

	// The description of the egress-only rule. The description must be 2 to 256 characters in length. It cannot start with http:// or https://.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the egress-only rule. The name must be 2 to 128 characters in length, and can contain letters, digits, underscores (_), and hyphens (-). The name must start with a letter but cannot start with http:// or https://.
	IPv6EgressRuleName *string `json:"ipv6EgressRuleName,omitempty" tf:"ipv6_egress_rule_name,omitempty"`

	// The ID of the IPv6 gateway.
	IPv6GatewayID *string `json:"ipv6GatewayId,omitempty" tf:"ipv6_gateway_id,omitempty"`

	// The ID of the IPv6 address to which you want to apply the egress-only rule.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The type of instance to which you want to apply the egress-only rule. Valid values: Ipv6Address. Ipv6Address (default): an IPv6 address.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`
}

type IPv6EgressRuleObservation struct {

	// The description of the egress-only rule. The description must be 2 to 256 characters in length. It cannot start with http:// or https://.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the resource supplied above.The value is formulated as <ipv6_gateway_id>:<ipv6_egress_rule_id>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the IPv6 EgressRule.
	IPv6EgressRuleID *string `json:"ipv6EgressRuleId,omitempty" tf:"ipv6_egress_rule_id,omitempty"`

	// The name of the egress-only rule. The name must be 2 to 128 characters in length, and can contain letters, digits, underscores (_), and hyphens (-). The name must start with a letter but cannot start with http:// or https://.
	IPv6EgressRuleName *string `json:"ipv6EgressRuleName,omitempty" tf:"ipv6_egress_rule_name,omitempty"`

	// The ID of the IPv6 gateway.
	IPv6GatewayID *string `json:"ipv6GatewayId,omitempty" tf:"ipv6_gateway_id,omitempty"`

	// The ID of the IPv6 address to which you want to apply the egress-only rule.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The type of instance to which you want to apply the egress-only rule. Valid values: Ipv6Address. Ipv6Address (default): an IPv6 address.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// The status of the resource.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type IPv6EgressRuleParameters struct {

	// The description of the egress-only rule. The description must be 2 to 256 characters in length. It cannot start with http:// or https://.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the egress-only rule. The name must be 2 to 128 characters in length, and can contain letters, digits, underscores (_), and hyphens (-). The name must start with a letter but cannot start with http:// or https://.
	// +kubebuilder:validation:Optional
	IPv6EgressRuleName *string `json:"ipv6EgressRuleName,omitempty" tf:"ipv6_egress_rule_name,omitempty"`

	// The ID of the IPv6 gateway.
	// +kubebuilder:validation:Optional
	IPv6GatewayID *string `json:"ipv6GatewayId,omitempty" tf:"ipv6_gateway_id,omitempty"`

	// The ID of the IPv6 address to which you want to apply the egress-only rule.
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The type of instance to which you want to apply the egress-only rule. Valid values: Ipv6Address. Ipv6Address (default): an IPv6 address.
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`
}

// IPv6EgressRuleSpec defines the desired state of IPv6EgressRule
type IPv6EgressRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IPv6EgressRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IPv6EgressRuleInitParameters `json:"initProvider,omitempty"`
}

// IPv6EgressRuleStatus defines the observed state of IPv6EgressRule.
type IPv6EgressRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IPv6EgressRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IPv6EgressRule is the Schema for the IPv6EgressRules API. Provides a Alicloud VPC Ipv6 Egress Rule resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alicloud}
type IPv6EgressRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.instanceId) || (has(self.initProvider) && has(self.initProvider.instanceId))",message="spec.forProvider.instanceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ipv6GatewayId) || (has(self.initProvider) && has(self.initProvider.ipv6GatewayId))",message="spec.forProvider.ipv6GatewayId is a required parameter"
	Spec   IPv6EgressRuleSpec   `json:"spec"`
	Status IPv6EgressRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IPv6EgressRuleList contains a list of IPv6EgressRules
type IPv6EgressRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IPv6EgressRule `json:"items"`
}

// Repository type metadata.
var (
	IPv6EgressRule_Kind             = "IPv6EgressRule"
	IPv6EgressRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IPv6EgressRule_Kind}.String()
	IPv6EgressRule_KindAPIVersion   = IPv6EgressRule_Kind + "." + CRDGroupVersion.String()
	IPv6EgressRule_GroupVersionKind = CRDGroupVersion.WithKind(IPv6EgressRule_Kind)
)

func init() {
	SchemeBuilder.Register(&IPv6EgressRule{}, &IPv6EgressRuleList{})
}
