// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PeerConnectionInitParameters struct {

	// The ID of the Alibaba Cloud account to which the accepter VPC belongs.
	AcceptingAliUID *float64 `json:"acceptingAliUid,omitempty" tf:"accepting_ali_uid,omitempty"`

	// The region ID of the accepter VPC of the VPC peering connection that you want to create.
	AcceptingRegionID *string `json:"acceptingRegionId,omitempty" tf:"accepting_region_id,omitempty"`

	// The ID of the accepter VPC.
	AcceptingVPCID *string `json:"acceptingVpcId,omitempty" tf:"accepting_vpc_id,omitempty"`

	// The bandwidth of the VPC peering connection. Unit: Mbit/s. The value must be an integer greater than 0. Before you specify this parameter, make sure that you create an inter-region VPC peering connection.
	Bandwidth *float64 `json:"bandwidth,omitempty" tf:"bandwidth,omitempty"`

	// The description of the VPC peering connection.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Specifies whether to perform only a dry run, without performing the actual request. Valid values:
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// Specifies whether to forcefully delete the VPC peering connection. Valid values:
	ForceDelete *bool `json:"forceDelete,omitempty" tf:"force_delete,omitempty"`

	// LinkType. Valid values: Platinum, Gold, Silver.
	LinkType *string `json:"linkType,omitempty" tf:"link_type,omitempty"`

	// The name of the VPC peering connection.
	PeerConnectionName *string `json:"peerConnectionName,omitempty" tf:"peer_connection_name,omitempty"`

	// The ID of the new resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The status of the resource
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The tags of PrefixList.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The ID of the requester VPC or accepter VPC of the VPC peering connection that you want to query.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type PeerConnectionObservation struct {

	// The ID of the Alibaba Cloud account to which the accepter VPC belongs.
	AcceptingAliUID *float64 `json:"acceptingAliUid,omitempty" tf:"accepting_ali_uid,omitempty"`

	// The region ID of the accepter VPC of the VPC peering connection that you want to create.
	AcceptingRegionID *string `json:"acceptingRegionId,omitempty" tf:"accepting_region_id,omitempty"`

	// The ID of the accepter VPC.
	AcceptingVPCID *string `json:"acceptingVpcId,omitempty" tf:"accepting_vpc_id,omitempty"`

	// The bandwidth of the VPC peering connection. Unit: Mbit/s. The value must be an integer greater than 0. Before you specify this parameter, make sure that you create an inter-region VPC peering connection.
	Bandwidth *float64 `json:"bandwidth,omitempty" tf:"bandwidth,omitempty"`

	// The creation time of the VPC peer connection. Use UTC time in the format' YYYY-MM-DDThh:mm:ssZ '.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The description of the VPC peering connection.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Specifies whether to perform only a dry run, without performing the actual request. Valid values:
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// Specifies whether to forcefully delete the VPC peering connection. Valid values:
	ForceDelete *bool `json:"forceDelete,omitempty" tf:"force_delete,omitempty"`

	// The ID of the resource supplied above.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// LinkType. Valid values: Platinum, Gold, Silver.
	LinkType *string `json:"linkType,omitempty" tf:"link_type,omitempty"`

	// The name of the VPC peering connection.
	PeerConnectionName *string `json:"peerConnectionName,omitempty" tf:"peer_connection_name,omitempty"`

	// The region ID of the resource to which you want to create and add tags.
	RegionID *string `json:"regionId,omitempty" tf:"region_id,omitempty"`

	// The ID of the new resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The status of the resource
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The tags of PrefixList.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The ID of the requester VPC or accepter VPC of the VPC peering connection that you want to query.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type PeerConnectionParameters struct {

	// The ID of the Alibaba Cloud account to which the accepter VPC belongs.
	// +kubebuilder:validation:Optional
	AcceptingAliUID *float64 `json:"acceptingAliUid,omitempty" tf:"accepting_ali_uid,omitempty"`

	// The region ID of the accepter VPC of the VPC peering connection that you want to create.
	// +kubebuilder:validation:Optional
	AcceptingRegionID *string `json:"acceptingRegionId,omitempty" tf:"accepting_region_id,omitempty"`

	// The ID of the accepter VPC.
	// +kubebuilder:validation:Optional
	AcceptingVPCID *string `json:"acceptingVpcId,omitempty" tf:"accepting_vpc_id,omitempty"`

	// The bandwidth of the VPC peering connection. Unit: Mbit/s. The value must be an integer greater than 0. Before you specify this parameter, make sure that you create an inter-region VPC peering connection.
	// +kubebuilder:validation:Optional
	Bandwidth *float64 `json:"bandwidth,omitempty" tf:"bandwidth,omitempty"`

	// The description of the VPC peering connection.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Specifies whether to perform only a dry run, without performing the actual request. Valid values:
	// +kubebuilder:validation:Optional
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// Specifies whether to forcefully delete the VPC peering connection. Valid values:
	// +kubebuilder:validation:Optional
	ForceDelete *bool `json:"forceDelete,omitempty" tf:"force_delete,omitempty"`

	// LinkType. Valid values: Platinum, Gold, Silver.
	// +kubebuilder:validation:Optional
	LinkType *string `json:"linkType,omitempty" tf:"link_type,omitempty"`

	// The name of the VPC peering connection.
	// +kubebuilder:validation:Optional
	PeerConnectionName *string `json:"peerConnectionName,omitempty" tf:"peer_connection_name,omitempty"`

	// The ID of the new resource group.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The status of the resource
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The tags of PrefixList.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The ID of the requester VPC or accepter VPC of the VPC peering connection that you want to query.
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

// PeerConnectionSpec defines the desired state of PeerConnection
type PeerConnectionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PeerConnectionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PeerConnectionInitParameters `json:"initProvider,omitempty"`
}

// PeerConnectionStatus defines the observed state of PeerConnection.
type PeerConnectionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PeerConnectionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PeerConnection is the Schema for the PeerConnections API. Provides a Alicloud Vpc Peer Peer Connection resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alicloud}
type PeerConnection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.acceptingRegionId) || (has(self.initProvider) && has(self.initProvider.acceptingRegionId))",message="spec.forProvider.acceptingRegionId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.acceptingVpcId) || (has(self.initProvider) && has(self.initProvider.acceptingVpcId))",message="spec.forProvider.acceptingVpcId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vpcId) || (has(self.initProvider) && has(self.initProvider.vpcId))",message="spec.forProvider.vpcId is a required parameter"
	Spec   PeerConnectionSpec   `json:"spec"`
	Status PeerConnectionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PeerConnectionList contains a list of PeerConnections
type PeerConnectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PeerConnection `json:"items"`
}

// Repository type metadata.
var (
	PeerConnection_Kind             = "PeerConnection"
	PeerConnection_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PeerConnection_Kind}.String()
	PeerConnection_KindAPIVersion   = PeerConnection_Kind + "." + CRDGroupVersion.String()
	PeerConnection_GroupVersionKind = CRDGroupVersion.WithKind(PeerConnection_Kind)
)

func init() {
	SchemeBuilder.Register(&PeerConnection{}, &PeerConnectionList{})
}
