// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type TrafficMirrorSessionInitParameters struct {

	// Whether to PreCheck only this request, value:
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// Specifies whether to enable traffic mirror sessions. default to false.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Maximum Transmission Unit (MTU).
	PacketLength *float64 `json:"packetLength,omitempty" tf:"packet_length,omitempty"`

	// The priority of the traffic mirror session. Valid values: 1 to 32766. A smaller value indicates a higher priority. You cannot specify the same priority for traffic mirror sessions that are created in the same region with the same Alibaba Cloud account.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// The ID of the resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The tags of this resource.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The ID of the filter.
	TrafficMirrorFilterID *string `json:"trafficMirrorFilterId,omitempty" tf:"traffic_mirror_filter_id,omitempty"`

	// The description of the traffic mirror session. The description must be 2 to 256 characters in length and cannot start with http:// or https://.
	TrafficMirrorSessionDescription *string `json:"trafficMirrorSessionDescription,omitempty" tf:"traffic_mirror_session_description,omitempty"`

	// The name of the traffic mirror session. The name must be 2 to 128 characters in length and can contain digits, underscores (_), and hyphens (-). It must start with a letter.
	TrafficMirrorSessionName *string `json:"trafficMirrorSessionName,omitempty" tf:"traffic_mirror_session_name,omitempty"`

	// The ID of the image source instance. Currently, the Eni is supported as the image source. The default value of N is 1, that is, only one mirror source can be added to a mirror session.
	TrafficMirrorSourceIds []*string `json:"trafficMirrorSourceIds,omitempty" tf:"traffic_mirror_source_ids,omitempty"`

	// The ID of the mirror destination. You can specify only an ENI or a Server Load Balancer (SLB) instance as a mirror destination.
	TrafficMirrorTargetID *string `json:"trafficMirrorTargetId,omitempty" tf:"traffic_mirror_target_id,omitempty"`

	// The type of the mirror destination. Valid values: NetworkInterface or SLB. NetworkInterface: an ENI. SLB: an internal-facing SLB instance.
	TrafficMirrorTargetType *string `json:"trafficMirrorTargetType,omitempty" tf:"traffic_mirror_target_type,omitempty"`

	// The VXLAN network identifier (VNI) that is used to distinguish different mirrored traffic. Valid values: 0 to 16777215. You can specify VNIs for the traffic mirror destination to identify mirrored traffic from different sessions. If you do not specify a VNI, the system randomly allocates a VNI. If you want the system to randomly allocate a VNI, ignore this parameter.
	VirtualNetworkID *float64 `json:"virtualNetworkId,omitempty" tf:"virtual_network_id,omitempty"`
}

type TrafficMirrorSessionObservation struct {

	// Whether to PreCheck only this request, value:
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// Specifies whether to enable traffic mirror sessions. default to false.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID of the resource supplied above.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Maximum Transmission Unit (MTU).
	PacketLength *float64 `json:"packetLength,omitempty" tf:"packet_length,omitempty"`

	// The priority of the traffic mirror session. Valid values: 1 to 32766. A smaller value indicates a higher priority. You cannot specify the same priority for traffic mirror sessions that are created in the same region with the same Alibaba Cloud account.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// The ID of the resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The status of the resource.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The tags of this resource.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The ID of the filter.
	TrafficMirrorFilterID *string `json:"trafficMirrorFilterId,omitempty" tf:"traffic_mirror_filter_id,omitempty"`

	// The description of the traffic mirror session. The description must be 2 to 256 characters in length and cannot start with http:// or https://.
	TrafficMirrorSessionDescription *string `json:"trafficMirrorSessionDescription,omitempty" tf:"traffic_mirror_session_description,omitempty"`

	// The name of the traffic mirror session. The name must be 2 to 128 characters in length and can contain digits, underscores (_), and hyphens (-). It must start with a letter.
	TrafficMirrorSessionName *string `json:"trafficMirrorSessionName,omitempty" tf:"traffic_mirror_session_name,omitempty"`

	// The ID of the image source instance. Currently, the Eni is supported as the image source. The default value of N is 1, that is, only one mirror source can be added to a mirror session.
	TrafficMirrorSourceIds []*string `json:"trafficMirrorSourceIds,omitempty" tf:"traffic_mirror_source_ids,omitempty"`

	// The ID of the mirror destination. You can specify only an ENI or a Server Load Balancer (SLB) instance as a mirror destination.
	TrafficMirrorTargetID *string `json:"trafficMirrorTargetId,omitempty" tf:"traffic_mirror_target_id,omitempty"`

	// The type of the mirror destination. Valid values: NetworkInterface or SLB. NetworkInterface: an ENI. SLB: an internal-facing SLB instance.
	TrafficMirrorTargetType *string `json:"trafficMirrorTargetType,omitempty" tf:"traffic_mirror_target_type,omitempty"`

	// The VXLAN network identifier (VNI) that is used to distinguish different mirrored traffic. Valid values: 0 to 16777215. You can specify VNIs for the traffic mirror destination to identify mirrored traffic from different sessions. If you do not specify a VNI, the system randomly allocates a VNI. If you want the system to randomly allocate a VNI, ignore this parameter.
	VirtualNetworkID *float64 `json:"virtualNetworkId,omitempty" tf:"virtual_network_id,omitempty"`
}

type TrafficMirrorSessionParameters struct {

	// Whether to PreCheck only this request, value:
	// +kubebuilder:validation:Optional
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// Specifies whether to enable traffic mirror sessions. default to false.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Maximum Transmission Unit (MTU).
	// +kubebuilder:validation:Optional
	PacketLength *float64 `json:"packetLength,omitempty" tf:"packet_length,omitempty"`

	// The priority of the traffic mirror session. Valid values: 1 to 32766. A smaller value indicates a higher priority. You cannot specify the same priority for traffic mirror sessions that are created in the same region with the same Alibaba Cloud account.
	// +kubebuilder:validation:Optional
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// The ID of the resource group.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The tags of this resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The ID of the filter.
	// +kubebuilder:validation:Optional
	TrafficMirrorFilterID *string `json:"trafficMirrorFilterId,omitempty" tf:"traffic_mirror_filter_id,omitempty"`

	// The description of the traffic mirror session. The description must be 2 to 256 characters in length and cannot start with http:// or https://.
	// +kubebuilder:validation:Optional
	TrafficMirrorSessionDescription *string `json:"trafficMirrorSessionDescription,omitempty" tf:"traffic_mirror_session_description,omitempty"`

	// The name of the traffic mirror session. The name must be 2 to 128 characters in length and can contain digits, underscores (_), and hyphens (-). It must start with a letter.
	// +kubebuilder:validation:Optional
	TrafficMirrorSessionName *string `json:"trafficMirrorSessionName,omitempty" tf:"traffic_mirror_session_name,omitempty"`

	// The ID of the image source instance. Currently, the Eni is supported as the image source. The default value of N is 1, that is, only one mirror source can be added to a mirror session.
	// +kubebuilder:validation:Optional
	TrafficMirrorSourceIds []*string `json:"trafficMirrorSourceIds,omitempty" tf:"traffic_mirror_source_ids,omitempty"`

	// The ID of the mirror destination. You can specify only an ENI or a Server Load Balancer (SLB) instance as a mirror destination.
	// +kubebuilder:validation:Optional
	TrafficMirrorTargetID *string `json:"trafficMirrorTargetId,omitempty" tf:"traffic_mirror_target_id,omitempty"`

	// The type of the mirror destination. Valid values: NetworkInterface or SLB. NetworkInterface: an ENI. SLB: an internal-facing SLB instance.
	// +kubebuilder:validation:Optional
	TrafficMirrorTargetType *string `json:"trafficMirrorTargetType,omitempty" tf:"traffic_mirror_target_type,omitempty"`

	// The VXLAN network identifier (VNI) that is used to distinguish different mirrored traffic. Valid values: 0 to 16777215. You can specify VNIs for the traffic mirror destination to identify mirrored traffic from different sessions. If you do not specify a VNI, the system randomly allocates a VNI. If you want the system to randomly allocate a VNI, ignore this parameter.
	// +kubebuilder:validation:Optional
	VirtualNetworkID *float64 `json:"virtualNetworkId,omitempty" tf:"virtual_network_id,omitempty"`
}

// TrafficMirrorSessionSpec defines the desired state of TrafficMirrorSession
type TrafficMirrorSessionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TrafficMirrorSessionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TrafficMirrorSessionInitParameters `json:"initProvider,omitempty"`
}

// TrafficMirrorSessionStatus defines the observed state of TrafficMirrorSession.
type TrafficMirrorSessionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TrafficMirrorSessionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TrafficMirrorSession is the Schema for the TrafficMirrorSessions API. Provides a Alicloud VPC Traffic Mirror Session resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alicloud}
type TrafficMirrorSession struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.priority) || (has(self.initProvider) && has(self.initProvider.priority))",message="spec.forProvider.priority is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.trafficMirrorFilterId) || (has(self.initProvider) && has(self.initProvider.trafficMirrorFilterId))",message="spec.forProvider.trafficMirrorFilterId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.trafficMirrorSourceIds) || (has(self.initProvider) && has(self.initProvider.trafficMirrorSourceIds))",message="spec.forProvider.trafficMirrorSourceIds is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.trafficMirrorTargetId) || (has(self.initProvider) && has(self.initProvider.trafficMirrorTargetId))",message="spec.forProvider.trafficMirrorTargetId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.trafficMirrorTargetType) || (has(self.initProvider) && has(self.initProvider.trafficMirrorTargetType))",message="spec.forProvider.trafficMirrorTargetType is a required parameter"
	Spec   TrafficMirrorSessionSpec   `json:"spec"`
	Status TrafficMirrorSessionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TrafficMirrorSessionList contains a list of TrafficMirrorSessions
type TrafficMirrorSessionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TrafficMirrorSession `json:"items"`
}

// Repository type metadata.
var (
	TrafficMirrorSession_Kind             = "TrafficMirrorSession"
	TrafficMirrorSession_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TrafficMirrorSession_Kind}.String()
	TrafficMirrorSession_KindAPIVersion   = TrafficMirrorSession_Kind + "." + CRDGroupVersion.String()
	TrafficMirrorSession_GroupVersionKind = CRDGroupVersion.WithKind(TrafficMirrorSession_Kind)
)

func init() {
	SchemeBuilder.Register(&TrafficMirrorSession{}, &TrafficMirrorSessionList{})
}
