apiVersion: cs.alibabacloud.crossplane.io/v1alpha1
kind: ManagedKubernetes
metadata:
  annotations:
    meta.upbound.io/example-id: cs/v1alpha1/managedkubernetes
  labels:
    testing.upbound.io/example-name: k8s
  name: k8s
spec:
  forProvider:
    addons:
    - name: terway-eniip
    - name: csi-plugin
    - name: csi-provisioner
    - config: |-
        ${jsonencode({
              IngressDashboardEnabled = "true"
            })}
      name: logtail-ds
    - config: |-
        ${jsonencode({
              IngressSlbNetworkType = "internet"
            })}
      name: nginx-ingress-controller
    - name: arms-prometheus
    - config: |-
        ${jsonencode({
              # sls_project_name = "your-sls-project"
            })}
      name: ack-node-problem-detector
    clusterSpec: ack.pro.small
    name: ${var.name}
    newNatGateway: true
    nodeCidrMask: ${var.node_cidr_mask}
    podVswitchIds: '${length(var.terway_vswitch_ids) > 0 ? split(",", join(",", var.terway_vswitch_ids))
      : length(var.terway_vswitch_cidrs) < 1 ? [] : split(",", join(",", alicloud_vswitch.terway_vswitches.*.id))}'
    proxyMode: ${var.proxy_mode}
    serviceCidr: ${var.service_cidr}
    vswitchIds: '${length(var.vswitch_ids) > 0 ? split(",", join(",", var.vswitch_ids))
      : length(var.vswitch_cidrs) < 1 ? [] : split(",", join(",", alicloud_vswitch.vswitches.*.id))}'

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: cs/v1alpha1/managedkubernetes
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: ${var.vpc_cidr}
    count: '${var.vpc_id == "" ? 1 : 0}'

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: cs/v1alpha1/managedkubernetes
  labels:
    testing.upbound.io/example-name: terway_vswitches
  name: terway-vswitches
spec:
  forProvider:
    cidrBlock: ${element(var.terway_vswitch_cidrs, count.index)}
    count: '${length(var.terway_vswitch_ids) > 0 ? 0 : length(var.terway_vswitch_cidrs)}'
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc_id == "" ? join("", alicloud_vpc
    zoneId: ${data.alicloud_enhanced_nat_available_zones.enhanced.zones[count.index].zone_id}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: cs/v1alpha1/managedkubernetes
  labels:
    testing.upbound.io/example-name: vswitches
  name: vswitches
spec:
  forProvider:
    cidrBlock: ${element(var.vswitch_cidrs, count.index)}
    count: '${length(var.vswitch_ids) > 0 ? 0 : length(var.vswitch_cidrs)}'
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc_id == "" ? join("", alicloud_vpc
    zoneId: ${data.alicloud_enhanced_nat_available_zones.enhanced.zones[count.index].zone_id}
