// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type NetworkRuleInitParameters struct {

	// Description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Network Rule Name.
	NetworkRuleName *string `json:"networkRuleName,omitempty" tf:"network_rule_name,omitempty"`

	// Allowed private network addresses.
	SourcePrivateIP []*string `json:"sourcePrivateIp,omitempty" tf:"source_private_ip,omitempty"`
}

type NetworkRuleObservation struct {

	// Description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the resource supplied above.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Network Rule Name.
	NetworkRuleName *string `json:"networkRuleName,omitempty" tf:"network_rule_name,omitempty"`

	// Allowed private network addresses.
	SourcePrivateIP []*string `json:"sourcePrivateIp,omitempty" tf:"source_private_ip,omitempty"`
}

type NetworkRuleParameters struct {

	// Description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Network Rule Name.
	// +kubebuilder:validation:Optional
	NetworkRuleName *string `json:"networkRuleName,omitempty" tf:"network_rule_name,omitempty"`

	// Allowed private network addresses.
	// +kubebuilder:validation:Optional
	SourcePrivateIP []*string `json:"sourcePrivateIp,omitempty" tf:"source_private_ip,omitempty"`
}

// NetworkRuleSpec defines the desired state of NetworkRule
type NetworkRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NetworkRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NetworkRuleInitParameters `json:"initProvider,omitempty"`
}

// NetworkRuleStatus defines the observed state of NetworkRule.
type NetworkRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NetworkRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NetworkRule is the Schema for the NetworkRules API. Provides a Alicloud KMS Network Rule resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alicloud}
type NetworkRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sourcePrivateIp) || (has(self.initProvider) && has(self.initProvider.sourcePrivateIp))",message="spec.forProvider.sourcePrivateIp is a required parameter"
	Spec   NetworkRuleSpec   `json:"spec"`
	Status NetworkRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkRuleList contains a list of NetworkRules
type NetworkRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkRule `json:"items"`
}

// Repository type metadata.
var (
	NetworkRule_Kind             = "NetworkRule"
	NetworkRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NetworkRule_Kind}.String()
	NetworkRule_KindAPIVersion   = NetworkRule_Kind + "." + CRDGroupVersion.String()
	NetworkRule_GroupVersionKind = CRDGroupVersion.WithKind(NetworkRule_Kind)
)

func init() {
	SchemeBuilder.Register(&NetworkRule{}, &NetworkRuleList{})
}
