// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PolicyInitParameters struct {

	// Network Rules in JSON struct.
	AccessControlRules *string `json:"accessControlRules,omitempty" tf:"access_control_rules,omitempty"`

	// Description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// KMS instance .
	KMSInstanceID *string `json:"kmsInstanceId,omitempty" tf:"kms_instance_id,omitempty"`

	// Allowed permissions (RBAC)Optional values:"RbacPermission/Template/CryptoServiceKeyUser" and "RbacPermission/Template/CryptoServiceSecretUser".
	Permissions []*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// Policy Name.
	PolicyName *string `json:"policyName,omitempty" tf:"policy_name,omitempty"`

	// The resources that the permission policy allows to access.Use "key/${KeyId}" or "key/"  to specify a key or all keys.Use "secret/${SecretName}" or "secret/" to specify a secret or all secrets.
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`
}

type PolicyObservation struct {

	// Network Rules in JSON struct.
	AccessControlRules *string `json:"accessControlRules,omitempty" tf:"access_control_rules,omitempty"`

	// Description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the resource supplied above.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// KMS instance .
	KMSInstanceID *string `json:"kmsInstanceId,omitempty" tf:"kms_instance_id,omitempty"`

	// Allowed permissions (RBAC)Optional values:"RbacPermission/Template/CryptoServiceKeyUser" and "RbacPermission/Template/CryptoServiceSecretUser".
	Permissions []*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// Policy Name.
	PolicyName *string `json:"policyName,omitempty" tf:"policy_name,omitempty"`

	// The resources that the permission policy allows to access.Use "key/${KeyId}" or "key/"  to specify a key or all keys.Use "secret/${SecretName}" or "secret/" to specify a secret or all secrets.
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`
}

type PolicyParameters struct {

	// Network Rules in JSON struct.
	// +kubebuilder:validation:Optional
	AccessControlRules *string `json:"accessControlRules,omitempty" tf:"access_control_rules,omitempty"`

	// Description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// KMS instance .
	// +kubebuilder:validation:Optional
	KMSInstanceID *string `json:"kmsInstanceId,omitempty" tf:"kms_instance_id,omitempty"`

	// Allowed permissions (RBAC)Optional values:"RbacPermission/Template/CryptoServiceKeyUser" and "RbacPermission/Template/CryptoServiceSecretUser".
	// +kubebuilder:validation:Optional
	Permissions []*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// Policy Name.
	// +kubebuilder:validation:Optional
	PolicyName *string `json:"policyName,omitempty" tf:"policy_name,omitempty"`

	// The resources that the permission policy allows to access.Use "key/${KeyId}" or "key/"  to specify a key or all keys.Use "secret/${SecretName}" or "secret/" to specify a secret or all secrets.
	// +kubebuilder:validation:Optional
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`
}

// PolicySpec defines the desired state of Policy
type PolicySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyInitParameters `json:"initProvider,omitempty"`
}

// PolicyStatus defines the observed state of Policy.
type PolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Policy is the Schema for the Policys API. Provides a Alicloud KMS Policy resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alicloud}
type Policy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accessControlRules) || (has(self.initProvider) && has(self.initProvider.accessControlRules))",message="spec.forProvider.accessControlRules is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.kmsInstanceId) || (has(self.initProvider) && has(self.initProvider.kmsInstanceId))",message="spec.forProvider.kmsInstanceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.permissions) || (has(self.initProvider) && has(self.initProvider.permissions))",message="spec.forProvider.permissions is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.policyName) || (has(self.initProvider) && has(self.initProvider.policyName))",message="spec.forProvider.policyName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.resources) || (has(self.initProvider) && has(self.initProvider.resources))",message="spec.forProvider.resources is a required parameter"
	Spec   PolicySpec   `json:"spec"`
	Status PolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyList contains a list of Policys
type PolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Policy `json:"items"`
}

// Repository type metadata.
var (
	Policy_Kind             = "Policy"
	Policy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Policy_Kind}.String()
	Policy_KindAPIVersion   = Policy_Kind + "." + CRDGroupVersion.String()
	Policy_GroupVersionKind = CRDGroupVersion.WithKind(Policy_Kind)
)

func init() {
	SchemeBuilder.Register(&Policy{}, &PolicyList{})
}
