apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: NetworkACLAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/networkaclattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    networkAclId: ${alicloud_network_acl.default.id}
    resourceId: ${alicloud_vswitch.default.id}
    resourceType: VSwitch

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/networkaclattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 192.168.0.0/16

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/networkaclattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: ${cidrsubnet(alicloud_vpc.default.cidr_block, 8, 2)}
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    zoneId: ${data.alicloud_zones.default.zones.0.id}
