apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Table
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/table
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    associateType: VSwitch
    description: test-description
    routeTableName: ${var.name}
    vpcId: ${alicloud_vpc.defaultVpc.id}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/table
  labels:
    testing.upbound.io/example-name: defaultVpc
  name: defaultvpc
spec:
  forProvider:
    vpcName: ${var.name}
